### ISSUE TITLE
Document Design Systems team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/design-systems#105]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the Design Systems team to help match your project with available volunteers.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [x] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
URL of the project's homepage on the HfLA website:  [INSERT PROJECT URL HERE]
Times that VRMS shows for your meetings: 
Design Systems Weekly meeting. Monday 6:30pm, 1 hour

**Comment by ExperimentsInHonesty** [comment]
Design Systems Weekly meeting. Monday 6:30pm, 1 hour 
 - [ ] day: Monday
   - [ ] start_time: 6:30
      - [ ] AM
      - [x] PM
   - [ ] duration_in_min: 60
   - [ ] name_of_meeting: Team Meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain

**Comment by ExperimentsInHonesty** [comment]
UI/UX meeting. ???, ???, 1 hour
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min: 60
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty All meeting times have been completed. Shall I close this Issue?
