### ISSUE TITLE
Create new Figma Document for Design Systems template

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#114]
### Overview
We need to create a new Figma document in order for product teams to copy for their projects. We currently have a Figma document that the Design systems team use for their WIP. The team new two Figma files - Design Systems Template and Design Systems Team

### Action Items

- [x] Set up a meeting with Bonnie and UX/UI Lead 
- [x] Add steps to this Issue.
- [x] Create two new Figma files Design Systems Template and Design Systems Team
- [x] Add team to new Figma
- [x] Move all pages from [old Figma file](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems-Team?node-id=1885%3A38079) to [new figma file](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Main-Figma?node-id=0%3A1)
- [x] Delete pages of old Figma file, besides cover page.
- [x] Include link to new file on cover page of old file

### Resources/Instructions
Design systems team [Figma file](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/UX-UI-Community-of-Practice?node-id=882%3A3934)

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty @rcurtis2 What time and date works for the both of you. I am unable to attend any weekend meetings.

**Comment by rcurtis2** [comment]
@Hanastevenson I can do anytime Monday 9/27 or Tuesday 9/28 after 4:00 pm PT.

**Comment by rcurtis2** [comment]
All pages have been moved over to the [new figma file]( https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma?node-id=2%3A24).
@Hanastevenson let's meet briefly to discuss deleting the old pages.

**Comment by Hanastevenson** [comment]
@rcurtis2 
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by rcurtis2** [comment]
All pages have been moved over to the new figma file.
@Hanastevenson I believe you mentioned meeting briefly to discuss deleting the old pages. If meeting is no longer necessary, then let me know and I'll move forward with just deleting the old figma.

**Comment by Hanastevenson** [comment]
@rcurtis2 Let's put some time in next week to close this out.

**Comment by Hanastevenson** [comment]
@rcurtis2 and PM have been through this and it needs to be deleted. Discuss in #89

**Comment by Hanastevenson** [comment]
@rcurtis2 I don't have admin rights to remove content from all the pages bar the front page. Please delete the content in all the pages bar the front cover which redirects users to the new projects.

**Comment by allthatyazz** [comment]
- 4/8/2022 I contacted the previous PM for the project to inquire about the status of this issue. 
- 4/11/2022 It is confirmed that all the previous files pages are successfully moved to the new file. Ryan is the owner of the previous file. No big trouble would arise from not deleting the content of the previous file.
