### ISSUE TITLE
Create cover for the Design System Figma Template.

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#115]
### Overview
We need to create a Figma cover for the Design System Template so that users can easily identify it in 'Recently Viewed' in their Figma account.

### Action Items

- [x] Review how the Design Systems Team Cover can differ from the Design System Template cover.
- [x] Create a new cover for the Design Systems Template.

### Resources/Instructions
<img width="634" alt="Screenshot 2021-09-22 at 16 42 22" src="https://user-images.githubusercontent.com/6236085/134436241-5a67e504-1b32-4957-a79f-6e49cbcd1677.png">

[Figma File ](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/UX-UI-Community-of-Practice?node-id=882%3A3934)

**Comment by kelenelee** [comment]
found this issue – we already made a cover page to start usability testing
