### ISSUE TITLE
Design Meeting Agenda for Sept 22, 2021

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/design-systems#116]
Design Meeting Agenda for Sept 22, 2021

### Overview
Weekly meeting to review and make decisions about our work on the Design System Figma file.

### Action Items

- [x] Discuss new meeting time
- [x] Review final grid designs
- [x] Review shadow and radius designs
- [x] Discuss icons and spacing

**Comment by rcurtis2** [comment]
![image](https://user-images.githubusercontent.com/82791147/134459823-d312d05a-4aa6-45ea-9f4e-bc65f62b9093.png)

**Comment by Hanastevenson** [comment]
@rcurtis2 Are there any new Issues as a result from this meeting?

Also, I am mentioned in the above meeting note (Grids) I didn't add anything to the Figma document.

**Comment by rcurtis2** [comment]
![image](https://user-images.githubusercontent.com/82791147/134840971-327cbe2d-246f-4cdb-ba92-96e394adbb1a.png)

**Comment by rcurtis2** [comment]
@Hanastevenson, apologies, that was a typo, I added new notes with a correction
There were no new issues, aside from the review of the research plan that I mentioned in Slack

**Comment by rcurtis2** [comment]
This issue can be marked as closed/marked as done.
