### ISSUE TITLE
Finalizing Github setup for new team members

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#12]
### Overview
All team members need to have 2 Factor Authentication setup on their Github accounts. And it is good (but optional) if they have their Hack for LA membership marked public.

### Action Items

- [x]  Invite all members to this project 
- [x] After hackforla github admin adds the new person to our github and to team, and notifies you, then send them the message via slack and ask them to follow up with you when completed with 2FA and membership public.
- [x]  When completed, ask hfla github admin to check it.

### Once you have accepted (invite comes via email), please do the following:
Mark your own membership public
https://help.github.com/en/articles/publicizing-or-hiding-organization-membership#changing-the-visibility-of-your-organization-membership
Setup two factor authentication on your account
hackforla/governance#20_

**Comment by Hanastevenson** [comment]
@cconner57 @lorenzejay @hanapotski @qiqicodes @nasimbiglari @BobbyBishopUX @irisxie @daniellex0 @rcurtis2 @anekkk    @AdesinaBernard @ahoang94  

Please confirm that you have set up 2 Factor Authentication setup on your Github accounts.

**Comment by nasimbiglari** [comment]
Profile is public and 2 factor is set.

**Comment by AdesinaBernard** [comment]
Done!

**Comment by lorenzejay** [comment]
just got 2 factor auth setup

**Comment by cconner57** [comment]
Both task done ✓

**Comment by irisxie** [comment]
Public and 2-factor authentification activated

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty Are you able to check off the last action?

- [ ]  When completed, ask HfLA Github admin to check it.

**Comment by Hanastevenson** [comment]
Needs to be checked in the next Stakeholder/PM meeting - https://github.com/hackforla/design-systems/issues/89
