### ISSUE TITLE
Create logo for the Design System project

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#13]
### Overview
Create a logo for this project so that it can be used across the website and documentation

### Action Items

- [x] Find out the typeface that is in the Hack for LA logo.
- [x] Change the mockup logo with the new typeface, reference lock up example below.
- [x] Create one version using #030D2D as the typeface colour
- [x] Create one version using #FFFFFF as the typeface colour

<img width="473" alt="Screenshot 2021-07-16 at 16 39 36" src="https://user-images.githubusercontent.com/6236085/126018081-2aa454aa-a7e9-48f4-9ff0-373b7ee99084.png">
Create another layout similar to the following, ignore the kerning, it's just an example.
<img width="1236" alt="Screenshot 2021-07-16 at 16 39 54" src="https://user-images.githubusercontent.com/6236085/126018137-3c9a0cf5-3885-415e-a72e-a132845ad5b9.png">

### Resources/Instructions
[Figma link](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=968%3A4146)

**Comment by Hanastevenson** [comment]
Update - after discussions with Bonnie. We have decided to tweak the above logo and use for the time being. 
This project will need a separate logo and name. Once tweaks have been made this Issue will be moving to the Icebox.

**Comment by Hanastevenson** [comment]
Anh Hoang is working on this card. Unable to assign awaiting Admin to allow access.

**Comment by Hanastevenson** [comment]
@ahoang94 I'm setting a deadline for this for the 9th August.

**Comment by ahoang94** [comment]
@Hanastevenson I've made mockups using two free-use typefaces that could serve as dupes for the current HfLA logo font. The [Figma link](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=968%3A4146) has been added to the Resources/Instructions section of the issue.

**Comment by Hanastevenson** [comment]
@ahoang94 The example typefaces look very close, thank you for sourcing them.  I'm leaning towards SaxMono however it would be great to see the option 2 example with reduced tracking. Are you able to do a version where the copy aligns with the sides of the HfLA logo. You may have already done this, and decided it is unbalanced, let me know.

**Comment by ahoang94** [comment]
@Hanastevenson Are you asking for the "Design Systems" text to match the width of the HfLA bug? 

I have updated the Figma file to include horizontal mockups, which provides for a larger view of the fonts. Also, everything is now in vector format to enable editing and manipulation in Figma.

**Comment by Hanastevenson** [comment]
@ahoang94 Thank you for the Mock ups. I've created and tweaked the logo a couple of times. Let me know your thoughts,  we can progress to the next steps.
<img width="834" alt="Screenshot 2021-08-11 at 13 53 26" src="https://user-images.githubusercontent.com/6236085/129102108-b5240920-1daf-41da-9e7f-ddd8f9fb4075.png">

**Comment by Hanastevenson** [comment]
@ahoang94 As per our meeting last night please progress with the logos we selected.
<img width="678" alt="Screenshot 2021-08-12 at 13 20 35" src="https://user-images.githubusercontent.com/6236085/129266942-12da84d2-be06-4935-9771-0870372ba103.png">

**Comment by ahoang94** [comment]
@Hanastevenson The Figma file has been updated with logo variations we last discussed. These variations are contained in the blue rectangle on the page.
![Screen Shot 2021-08-14 at 12 17 59 PM](https://user-images.githubusercontent.com/85914721/129457958-f03ef546-7f3e-4b0e-863e-e605a2b2ae01.png)

**Comment by Hanastevenson** [comment]
@ahoang94 Great. Please present this at tonights weekly meeting.
