### ISSUE TITLE
Identify and recruit key users to read and review draft Design Guide

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#16]
### Overview
Identify and recruit key users to read draft Design Guide so that they can provide feedback.

### Action Items

- [ ] Collate list of users
- [ ] Add their details to the below document
- [ ] Add the link to the document to this ticket so that the assignees can send the draft to the users.

### Resources/Instructions
[Google sheet listing targeted users](https://docs.google.com/spreadsheets/d/1yn9O6S-ea0Ge6SzcySC89-JDG1nFi0108uzXL0vIZ9A/edit?usp=sharing)

**Comment by kelenelee** [comment]
merged with https://github.com/hackforla/design-systems/issues/15
