### ISSUE TITLE
Invitation message/ details

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#163]
### Overview
Interview information includes invitation message and the detail of invitation along with the availability of the group for the interviews. 
### Action Items

 **Invitation message**
- [x] Include the invitation msg 
- [x] Make any essential edits on the script

**Invitation details**

- [x] Create a table with the title of "Invitation details"
- [x] Include the name of the participants we are contacting
- [x] Include the name of the person sending the invitation msg
- [x] Include the date of sent msg
- [x] Include the name of person sending the reminder msg 
- [x] Include the date of sent reminder msg 

### Resources
[Screener link ](https://docs.google.com/forms/d/1v2x9GT08Vu2YRytoxN6LC8xlw-1QSpTUJHGehQShR68/edit)
[Interview detail ](https://docs.google.com/document/d/1wjpJCL7FsG2ly-u0eusIt3OR1b-tsc2zPZqSHFgZOFk/edit)
[Research plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit#)

**Comment by Hanastevenson** [comment]
@navarroliuanthony please add the screener to the ticket under resources.

**Comment by Hanastevenson** [comment]
@nasimbiglari to update
