### ISSUE TITLE
Setting up Calendly account

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#164]
### Overview
We need to open up a candenly account so that we can use it this for finding appropriate time slots for interviews and as well sending reminder for the meeting. Dependent on #161 

### Action Items

- [x] Set up calendly account
- [x] Add the link  to the research plan
- [x] Add the link to the participants document. 
- [x] Set up the reminder email - paste the script from the research plan 

### Resources/Instructions
[calendly](https://calendly.com/)
[Research Plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit)
[Participant Document](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit#gid=0)

**Comment by kelenelee** [comment]
@JeannyRen @navarroliuanthony @avknutson @nasimbiglari were assigned the following task on Nov 16 2021 (#221 #224 #225 #226 : 
```
All Research team members need to have an understanding of how Calendly works so that they can schedule and send reminders.

- [ ] Sign in to Calendly https://calendly.com/hfladesignsystems
- [ ] Set up an example meeting 
- [ ] Set up an example reminder email
```

They decided to use Lettuce meet on Nov 24 2021.
