### ISSUE TITLE
Developers interview script

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#167]
### Overview
This document includes a full guide for developers  interview. It includes the introduction, questions and wrap section. This will also be used as a guide for the interviewer.
### Action Items

- [ ] Create a google form "developers script"
- [ ] include introduction, questions for developers, and wrap up
- [ ] Check with research lead

### Resources/Instructions
[Stakeholder script](https://docs.google.com/forms/d/1qCMwu-uXn5CzNeKXN26oejAhMW7_0Xk_ZgoojjZjMwQ/edit) to be used as a template
[Final interview questions](https://docs.google.com/document/d/1fLzb_hrqgfjioXxDDOOMfMgT2oJ3Gi3h1snCOAWWEcc/edit#heading=h.2egvzr5n6rn3)

**Comment by Hanastevenson** [comment]
@avknutson Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by avknutson** [comment]
Progress: This ticket has been completed.
