### ISSUE TITLE
Team Members to read the draft guide and provide feedback

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#17]
### Overview
Team Members to read the draft guide and provide feedback so that we all have a shared understanding.

### Action Items

- [x] Read the guide
- [x] Provide feedback within the document using 'comments'. Longer conversations should be discussed in the Design Systems Slack channel.

###
Team please comment below once you have read the guide.
- [x] Hana 
- [x] Danielle
- [x] Ciara 
- [x] Lorenze 
- [x] Ryan
- [x] Chris 
- [x] Hannah 
- [x] Bobby 
- [x] Bernard 
- [x] Anh 
- [x] Iris
- [x] Nas
- [x] Anastasia

### Resources/Instructions
[Draft Design Guide](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)

**Comment by Hanastevenson** [comment]
To be discussed in an August weekly meeting.

**Comment by AdesinaBernard** [comment]
I have read the guide and have a general understanding of the content.

**Comment by Hanastevenson** [comment]
Setting the deadline for this for the 9th August.

**Comment by qiqicodes** [comment]
I have read the guide.

I think our next step is to figure out our MVP of the guideline. And where we want to stage our design system, ie. Figma, Storybook, etc...

**Comment by Hanastevenson** [comment]
@cconner57 @nasimbiglari @anekkk Please could you read the guide by the end of the weekend as I have blocked out Monday to go through it.

**Comment by nasimbiglari** [comment]
I enjoyed reading through this guide. It was easy to follow and helped me understand the whole process more.
