### ISSUE TITLE
Post interview guide

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#177]
### Overview
There will be few tasks to do after finishing up each interview. This document is a guide for the interviewers and note takers to use .

### Things that needs to be included

- [x] Uploading the recording process #87 
- [x] Updating the [participants profile document ](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit#gid=0)
- [x] Uploading the video for transcription

### Resources/Instructions
[Post interview guide](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit) -

**Comment by Hanastevenson** [comment]
To be discussed in the next UXR meeting on the 11/09/21.

**Comment by Hanastevenson** [comment]
As a team this needs to be discussed, @nasimbiglari to set meeting.
