### ISSUE TITLE
Dovetail Tutorial

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#178]
### Overview
We will be using Dovetail to analyze the data collected in the interviews.. In this document we gather the FAQs, tutorials, and examples that we need to study to be more prepared to start using this program.

### The document should Include
- [x] FAQ
- [x] Tutorials
- [x] Examples

### Resources/Instructions

[Dovetail Tutorial slides](https://docs.google.com/presentation/d/1HilJGwrXEO8BR_mvLzR6CYzm2PUCYbCPV_hvNZ203ro/edit#slide=id.p)

**Comment by kelenelee** [comment]
#141
