### ISSUE TITLE
Tidy Figma file

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#18]
### Overview
The current Design Systems figma file has been a dumping ground from the research and exploration phase. The file needs to be organised, structured and labelled correctly so that a new team member can navigate around the file without confusion.

### Action Items

- [x] Delete unused pages
- [x] Change the name of the file and include an intro to Design System page
- [x] Add link to the figma document to the Design System project page. https://github.com/hackforla/design-systems/projects/1#card-65078956
- [ ] - [ ] Tidy and rename current pages, links with #33 

### Resources/Instructions
[Figma document](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/UX-UI-Community-of-Practice?node-id=882%3A3934)

**Comment by daniellex0** [comment]
Progress: Have not had a lot of time to make progress with this- should have more time this week and especially next week.
Blocks: limited time
Availability: flexible, especially available next week
ETA: 2 weeks

**Comment by Hanastevenson** [comment]
<img width="946" alt="Screenshot 2021-08-11 at 11 21 02" src="https://user-images.githubusercontent.com/6236085/129082457-b08a3b37-186b-4188-b1d6-0788600a8f68.png">
@daniellex0 I've created a key and tidied up the Pages section. Team members will now be able to identify the WIP pages and finished UI. I'll leave the Pages under 'Research' for you to organise.
