### ISSUE TITLE
Stakeholder and PM Agenda Week of the 1st November

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#184]
### Overview
A weekly meeting to discuss project board, Issues, product management techniques.

### Action Items

- [x] Discuss https://github.com/hackforla/website/issues/2255#issuecomment-948311247
- [x] Adding people to the Design System project on the HfLA website.
- [x] Show labels from Roadmap
- [x] Login into the VRMS
- [x] Wiki > Home panel formatting. (Will explain in meeting)
- [x] Show how the Design Team save resources.
- [x] How to remove people from having access to the Shared Drive.

### Links
<img width="555" alt="Screenshot 2021-10-26 at 09 40 33" src="https://user-images.githubusercontent.com/6236085/138923303-acc3c7da-0a18-4100-bfb1-b1f7d0f58637.png">
<img width="936" alt="Screenshot 2021-10-26 at 09 44 30" src="https://user-images.githubusercontent.com/6236085/138923891-b197b2a7-dbaa-4749-9694-7e3e3f9f18dd.png">

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson Please add us talking about the leadership roles for this page to the agenda
https://www.hackforla.org/projects/design-systems
