### ISSUE TITLE
Create one sheet

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#2]
### Overview
We need to create the one sheet in order have organisational and team alignment.

### Action Items

- [x] Work on this issue https://github.com/hackforla/product-management/issues/271
- [x] Include logo on the one sheet #13 

### Links

[Draft](https://docs.google.com/document/d/1DsKRts479ibNi2EIdOzGeWv9sEY_eMMmy6mw_x6fFqo/edit#heading=h.n7lqzt5pn1610)

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson sent me the draft on 2021/07/19 and I just finished my edits.  

Thanks so much for getting that awesome first draft together.  I have made some edits to make it shorter (reworded a few things and only removed one thing).  I do have a question about one item and put a comment on the doc 

> In August 2020, Hack for LA was in the midst of rapid growth of new volunteers. New designers and developers joined projects without clear systems in place to standardize their work, scale teams and _progress was stalled._

its the part I put in italics above.

**Comment by daniellex0** [comment]
@Hanastevenson this is the usual update format:

Please provide update:

Progress:
Blockers:
Availability:
ETA:

**Comment by Hanastevenson** [comment]
Progress: The one sheet has been edited and copy is ready to be reviewed and submitted to Bonnie. One blocker.
Blockers: Awaiting for the logo to be designed so we can add it to the one sheet. 
Availability: Flexible
ETA: Next week.
