### ISSUE TITLE
Otter tutorial

### ISSUE THREAD

**Issue by JeannyRen** [hackforla/design-systems#216]
### Overview
We will be using Otter (Otter.ai) to record and transcribe the interviews.. In this document we gather the FAQs, tutorials, and examples that we need to study to be more prepared to start using this program. 

### The document should Include
- [x] FAQ
- [x] Tutorials
- [x] Examples

Linked to #87 

### Resources/Instructions
[Otter Tutorial slides work version](https://docs.google.com/presentation/d/1yNikkxfgtN4CVU1FoU6nttpZ24h6CqIiEbJWY7UG6do/edit#slide=id.p)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by JeannyRen** [comment]
The Otter tutorial has been updated and is finished. There is a link to this tutorial in the interview recording Google Doc file, so that it is easy to find.
