### ISSUE TITLE
Explore Design Systems Guide for developers

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#22]
### Overview
The current Design Guide is tailored towards a design. How might we include content that would be relevant for a developer.

### Action Items
- [ ] discussion with UI & Devs to figure out the guideline for our Design System project
- [ ] component based thinking, communicate and visualize the components 

### Resources/Instructions
[InVision Design System Handbook](https://www.designbetter.co/design-systems-handbook/introducing-design-systems)

**Comment by kelenelee** [comment]
closed, appears to be addressed in [current version of guide](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit)
