### ISSUE TITLE
UXR meeting agenda 11/22/21

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#228]
### Overview
The agenda for this week's Design Systems research team.

### Action Items

- [x] Discuss the topics on figjam.
- [x] Discuss the outreach for interview participants.
- [x] Editing the interview questions to fit 45 min time limit.
- [x] Discuss next tickets.
- [x] Discuss-Calendly

### Resources/Instructions
[Figjam](https://www.figma.com/file/DWs6sVSCJvH1y6J5FvapfO/UXR?node-id=0%3A1)

**Comment by JeannyRen** [comment]
Additional recruitment techniques discussed:
- Start with the PM and interview them and ask them if they can promote this to their team
- Target the people we do know in hfla and ask them to promote this for us.
- Approach the CoP leads to help with recruitment.

**Comment by nasimbiglari** [comment]
The team decided to work on the questions this week to cut at least 5 questions from each interview questions so it can fit it in the 1 hour time frame.
