### ISSUE TITLE
Create a Design Systems branded template

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#234]
### Overview
As a team we will be producing a number of insights report, therefore we need to have a Google slides template in order to save time and be consistent with our outputs.

### Action Items
Discover what page templates need to be designed.
Produce mid - fidelity document with stated pages.
Present said document to PM and team in weekly meeting
Create new document with feedback from team and create template document in 

### Resources/Instructions
[Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing)

**Comment by ahoang94** [comment]
@Hanastevenson I have made a first draft of a slide deck template [here](https://docs.google.com/presentation/d/1ACobat6E4qvgctEUMvOMHPIKFBNM1WFGcexIp1omj6M/edit?usp=sharing). It is purposely minimalist in design to allow for users to add their own photos and graphics as needed.

As you know, I will be leaving the DS team in the new year, but I'd be happy to make revisions based on the team's feedback as needed.
