### ISSUE TITLE
UXR MEETING AGENDA 11/30

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#237]
### Overview
The agenda for this week's Design Systems research team.

### Action Items

- [x] Trimming down the interview questions
- [x] Discuss next tickets
- [x] Plan the first interview
- [x] Discuss Blockers
### Resources/Instructions
[Backlog
](https://github.com/hackforla/design-systems/projects/1?card_filter_query=label%3A%22role%3A+research%22)

**Comment by JeannyRen** [comment]
Brief note for analysis: do users define/interpret DS users as individual persons or through means of their roles?

**Comment by nasimbiglari** [comment]
Team discussed the questions that could be deleted or combined. We will be meeting again on Thursday 4:00pm pst to continue our conversation.

**Comment by nasimbiglari** [comment]
Interview questions for all roles are finalized. We will be moving to interviewing phase next week.
