### ISSUE TITLE
Create Design System user personas

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#24]
### Overview
 Create user personas help us to understand our users' needs, experiences, behaviours and goals. 

### Action Items

- [ ] Identify key users (roles, expertise level etc..)
- [ ] Create a new Issue for each role and assign 
- [ ] Attach individual Issues to this card
- [ ] Reference #32  
- [ ] Reference this card #10 

### Links/Resources
Here is a great of articles.
https://medium.com/beakerandflint/personas-74c4e1c12ee2

**Comment by Hanastevenson** [comment]
Reading: 
https://medium.com/user-experience-design-1/personas-e60c1c06ead1
https://medium.com/user-experience-design-1/personas-jtbd-user-needs-goals-pain-points-7eaa81976f0
https://medium.com/user-experience-design-1/personas-arent-the-problem-your-methodology-is-5c020f88561b

**Comment by kelenelee** [comment]
moved to #431

**Comment by Leah0996** [comment]
@allthatyazz
