### ISSUE TITLE
Revise the Figma and Wiki audit report

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#240]
### Overview
The UX/UI team individually created insight reports for the figma and wiki audit followed by the UX/UI lead combining them into one report. The PM will revise the document and provide notes.
### Action Items

- [ ] Review all individual reports
- [ ] Review combined report
- [ ] Present at the next Monday meeting.

### Resources/Instructions

[Insight Reports](https://drive.google.com/drive/u/0/folders/1teY-wD3APs-R_KM-AguGIiie_gxX8LNf)

[Figma Audit](https://docs.google.com/spreadsheets/d/1FLMtxKobteA-dJ7ZK59-Ddn5abVOxJQFCZCJRNNvKM4/edit?usp=sharing)
[Wiki Audit](https://docs.google.com/spreadsheets/d/1Fc4TvyZA3uukK7461Q_VSwtKEGS-i7UIaWvBt1W7keU/edit?usp=sharing)

Ryan's wiki audit
[Anh wiki audit](https://docs.google.com/presentation/d/17UHAral8XionjUYci4oZzLZ_TaStwE3sr0Z509JMluE/edit?usp=sharing)
Bernard wiki audit

[Combined Wiki Insights](https://docs.google.com/presentation/d/1eJTsd8kCjJpmP4iVvmsrhQXxenDC3BqDSibAKCFLRKM/edit?usp=sharing)

Ryan's Figma audit
[Anh Figma Audit](https://docs.google.com/presentation/d/1y1lyETGTRG0GovMXkJhsScq847oLhnd2cdi6u9fLxug/edit?usp=sharing)
[Bernard Figma Audit](url)

Combined document

**Comment by kelenelee** [comment]
has been presented according to video file in google drive folder
