### ISSUE TITLE
Create a new open role for Research role

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#247]
### Overview

Discussions with the team have highlighted that a number of team members are currently interviewing and will be leaving the project in the new year.  With an influx of new joiners for HfLA in January 2022, we need to create a open role ticket for a research role. 

### Action Items

- [x] Review the following resources below
- [x] Write a open role for a researcher 
- [x] Add copy to this Issue
- [x] Inform PM and ask for feedback

### Resources/Instructions
[Example Research open role]( https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ux-researcher.md
)
[Open role board for Research](https://github.com/hackforla/UI-UX/projects/2)

**Comment by nasimbiglari** [comment]
Researcher position has been posted. Here is the content: 

Project: Design system
Duration: Open-ended (8-10 hour weekly)
Volunteer opportunity: (1-2) UX Researcher needed.
As a volunteer, you will collaborate with the UXR team to conduct user interviews and usability tests( Both qualitative and quantitative). You also will be working with various methodologies to analyze the found data and present it to the team. The team includes a research lead as well as another researcher. 
The design system project would be a fantastic addition to your portfolio. This position gives you an opportunity to not only sharpen your research skills but also improve your communication cross-functionally.
Who to communicate if you are interested: @Hana Stevenson in Slack 
When we meet:  Design system meeting:  Mondays: 6:30-7:30 PST
                            UXR team meeting: Thursdays 11:00-11:30 PST
