### ISSUE TITLE
Create open role for the UX/UI lead

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#250]
### Overview

As discussed with the UX/UI team lead, they will be interviewing and will be leaving the project in January, With an influx of new joiners for HfLA in January 2022, we need to create a open role ticket for a UX/UI team lead so that there is time for the new and current lead to work together on a handover process.

### Action Items

- [x] Review the following resources below
- [x] Write a open role for a UX/UI
- [x] Add copy to this Issue
- [ ] Inform PM and ask for feedback

### Resources/Instructions
[Example UI open role]( https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ui-designer.md)
[Example UX open role](https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ux-designer.md)
[Open role board for Research](https://github.com/hackforla/UI-UX/projects/2)

**Comment by rcurtis2** [comment]
[Card Link](https://github.com/hackforla/UI-UX/projects/3#card-76172698)

**Card Copy:**
**Project Name**: Hack for LA Design Systems

**About the Project:**
[The Design System](https://www.hackforla.org/projects/design-systems) initiative seeks to empower volunteers with the tools, documentation and templates for creating and maintaining a design system for their HfLA projects. 

**Volunteer Opportunity**: Project is looking a Design Lead to replace the current lead who will be offboarding at the end of January.

**Some Design Lead Responsibilities:**
- Present status updates at the Weekly meeting.
- Guide team members to create tickets
- Create Design meeting agenda at least 1 day before the meeting.
- [Read more](https://github.com/hackforla/design-systems/wiki/UX-UI-Role-Overview)

**Duration**: Need ASAP

**Who to communicate your interest to**
- Slack channel link: #[design-systems](https://hackforla.slack.com/archives/CH2U1CB9Q)

- Slack name of person to contact in the channel @Ryan Curtis 
[Read more about the project](https://github.com/hackforla/design-systems/wiki)
