### ISSUE TITLE
Extracting themes- interview-12/12

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#252]
### Overview
As a team we have decided that we want to alternate responsibilities in the interview procedure so everyone on the team would get a chance to get hands on experience on all aspects of interview process.
An interview was conducted by two members of the research team, the researchers who were not involved with the interview process are tasked to listen, analyze and share findings with team.

### Action Items

- [x] Listen to the interview.
- [x] Extract the themes in preparation of affinity mapping.
- [x] add the themes to the figjam.

### Resources/Instructions
[12/12 Interview](https://drive.google.com/drive/u/0/folders/1EMx3He3F_EKwFV9tGqG-T8yR86xbcLVv)
[Figjam](https://www.figma.com/file/DWs6sVSCJvH1y6J5FvapfO/UXR?node-id=0%3A1)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by navarroliuanthony** [comment]
1. In progress. Have listened to recording for the first time.
2. None yet
3. REgular 6 hours
4. By Monday

**Comment by navarroliuanthony** [comment]
All done!
