### ISSUE TITLE
 Onboarding to the Research team

### ISSUE THREAD

**Issue by JeannyRen** [hackforla/design-systems#253]
### Overview
Insights from the Figma and Wiki document have highlighted that onboarding into a team can be improved. With new joiners starting in January 2022, we need to create a template ticket for a joiner to work on in their first week. This could also be an experiment to see if a dedicated onboarding ticket could be an option for other teams. 

### Action Items

- [x] Discuss as a team what should be in the ticket, what do people need to know about the project as a whole.
- [x] Where to guide them, wiki, drive, books etc...

This issue is linked to #246 

### Resources/Instructions
[Draft onboarding document](https://docs.google.com/document/d/1SZ8dNbssAquIRTeRK80q0eP0Vl4a9ZNZgMhhDq9YHEE/edit?usp=sharing)
[Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing)
[Wiki](https://github.com/hackforla/design-systems/wiki)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.
