### ISSUE TITLE
UXR meeting agenda 1/4/22

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#254]
### Overview
This is the agenda for the UX research meeting.

### Action Items

Discuss: 

- [x] Availability
- [x] Open tickets
- [x] Things to be done
- [x] Blockers

### Resources/Instructions

[Research plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit#) for future tickets

**Comment by JeannyRen** [comment]
Team discussed the members' availability for the coming and next month. The UXR lead will communicate this information to PM.

Team discussed interview planning (approaching 3 respondents), future interview planning, the planning of the theme extraction of the December interviews, and future recruiter outreach. UXR will contact PM with the regards to the later. 

Blockers: UXR will discuss with PM with regards to the future recruitment outreach.

**Comment by Hanastevenson** [comment]
@nasimbiglari can this Issue be closed?
