### ISSUE TITLE
User interview analysis | participant 1

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#258]
### Overview
As a team we have decided that we want to alternate responsibilities in the interview procedure so everyone on the team would get a chance to get hands on experience on all aspects of interview process.
An interview was conducted by two members of the research team, the researchers who were not involved with the interview process are tasked to listen, analyze and share findings with team.

### Action Items

- [ ] Listen to the interview.
- [ ] In preparation of the affinity mapping exercise, generate sticky notes with the themes, ideas, and understandings that you have derived from the interview in Figjam.
- [ ] Finish organizing the sticky notes with the team.
- [ ] After the sticky notes organization, funnel the insights into the following elements in order to better prepare for the insight reports: user pain points, user needs, organizational needs (if applicable), themes, key insights, and if applicable other themes that are of research interest for a later point time.
- [ ] Put together the insights in your box in Interview figjam.
- [ ] Inform the leads

### Generate sticky notes guidelines
Please, read the following guidelines for the sticky note generation exercise. In this way, we increase our understanding during the sorting.
- [ ] Put -**Q**- on the sticky note if you write down a direct quote from the interview including the regarding time stamp through the following format: -**min: 2.28**-.
- [ ] If you have a larger code and you want to leave out a part or certain words, please indicate that you have done so by replacing that piece of text with the following -**[...]**-. In that way, we at least know that there is a piece of information missing from the regarding quote.
- [ ] Put -**I**- if you write down an insight that you derived from the interview.

### Resources/Instructions
[Interview uploads
](https://drive.google.com/drive/u/0/folders/1t3QrCAs1EBHBktebonpOb7OBVe73SpHL)
[Interview Figjam](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam?node-id=0%3A1)
[Nielsen Norman Group article on Affinity mapping](https://www.nngroup.com/articles/affinity-diagram/)

**Comment by Hanastevenson** [comment]
@avknutson is this assigned to you. Please discuss with @nasimbiglari if you need to complete before moving on.
