### ISSUE TITLE
Organise Research Google Drive

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#270]
### Overview
There are new joiners starting the research team. The Research folder in the Design System Google Drive  needs to be reorganised so that team members are able to easily find files. The folder needs to be organised so that any team member regardless of role can find and access files.

### Action Items

- [x] Team leads to discuss issues with the current organisation of these files
- [x] Organise the file

### Resources/Instructions
[Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing)

**Comment by JeannyRen** [comment]
Completed the organization of the Research team folder on the Google Drive. @nasimbiglari, please cross-check if the organization makes sense. Plus, I want to make sure that we are on the same page regarding the user interview folder (the organization of uploads, etc.).

**Comment by JeannyRen** [comment]
Hi @Hanastevenson, we reviewed it. If you are okay with the current organization, we can close the ticket.
