### ISSUE TITLE
Research Lead Responsibilities - Wiki 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#272]
### Overview
We are currently adding content to the research section of the Wiki. In section we will include responsibilities to the research lead. This will also act as a reference for any other product team wanting to use the Design System wiki as a template. 

### Action Items

- [ ] Review the [Wiki content ](https://github.com/hackforla/design-systems/wiki/Research-Lead-responsibilities)
- [ ] Add the content to onboarding
- [ ] Send to PM for Feedback

### Resources/Instructions
[Onboarding/wiki template](https://docs.google.com/document/d/16TK_B88DMcZpRkvSxPchOVO4aR4XVTZ3vt-RYTjqrpQ/edit#)

**Comment by kelenelee** [comment]
it looks like [this page has been written](https://github.com/hackforla/design-systems/wiki/Research-Lead-responsibilities). closing to reduce board clutter

**Comment by kelenelee** [comment]
wiki page was deleted to reduce sidebar clutter. job responsibilities are currently under "background" until the job descriptions are rewritten
