### ISSUE TITLE
New volunteer onboarding tasks

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#274]
Copy the template below. Click the green "New Issue" button, and paste the template in.

# Conduct and logistics 
- [ ] Accept and abide by [our expectations](https://github.com/hackforla/design-systems/wiki/Getting-Started), including the HfLA code of conduct and norms
- [ ] Be available for the [weekly meetings](https://github.com/hackforla/design-systems/wiki/Getting-Started)
- [ ] Be able to contribute the [minimum number of hours a week](https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.gc50dc3b32b_1_40)
- [ ] Introduce yourself on the [Design Systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q)
- [ ] Get added to our [Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing)
  - [ ] Add yourself to the [Team Roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI/edit#gid=1806338047).
  - [ ] Comment on this issue and @ mention the PM, confirming that you have added yourself to the roster
- [ ] Enable two-factor authentication on your Github account
- [ ] Upload a profile picture to your Github account

# Project management 101
- [ ] Read through [glossary of project terms](https://github.com/hackforla/design-systems/wiki/Glossary-of-project-terms) 
- [ ] Read [How Hack for LA uses Kanban](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit)
- [ ] Add the following to this issue:
  - [ ] label "size 1 pt"
  - [ ] project "onboarding"
  - [ ] milestone "velocity"
  - [ ] assignee, you!

# About design systems
- [ ] Read about the [history of our DS project](https://github.com/hackforla/design-systems/wiki/Introduction-and-History)
- [ ] Read chapter 1 of _Design Systems_ by Alla Kholmatova, one of the key books people refer to when discussing design systems [PDF](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf) [Kindle](https://www.amazon.com/Design-Systems-Smashing-eBooks-Kholmatova-ebook/dp/B076H49W1G) [Hard cover](https://www.amazon.com/Design-Systems-practical-creating-languages/dp/3945749581)
  - [ ] Comment your key learnings in the [Kholmatova discussion thread](https://github.com/hackforla/design-systems/discussions/198)
- [ ] Watch Jennie Yip's Figma conference talk, ["Reimagining Atlassian Design System"](https://www.youtube.com/watch?v=_pfyLVXTVSQ)
  - [ ] Comment your key learnings in the [Atlassian DS discussion thread](https://github.com/hackforla/design-systems/discussions/170)

### More educational resources 
(These are optional, but will help deepen your understanding of design systems.)
- [ ] [Invision's Design Systems Handbook](https://www.designbetter.co/design-systems-handbook)
- [ ] [Defining Design Systems](https://medium.com/eightshapes-llc/defining-design-systems-6dd4b03e0ff6) - 7 minute read
- [ ] [Design Systems podcast](https://podcast.clearleft.com/season01/episode01/) (15 min)
- [ ] [Picking Parts, Products & People](https://medium.com/eightshapes-llc/picking-parts-products-people-a06721e81742)

# Role-specific tasks
If your role is one of the following, complete the tasks for that role.

### Role: Design 
- [ ] Follow the [experience profile guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit#slide=id.p) to create an experience profile on the [experience board](https://github.com/hackforla/UI-UX/projects/5) HfLA has created an experience profile so that members can use it to track their courses at Hack for LA. It also helps the team leads to identify what skills you have not completed during your time at HfLA. The profile is a template for all UX/UI/Researchers therefore not all skills are applicable. 
  - [ ] Add profile link as a comment on this issue
- [ ] Read the [history of the UX/UI work](https://github.com/hackforla/design-systems/wiki/UX-UI-Project-History)
- [ ] For a comprehensive overview of each part of a design system, please view [HflA’s Design System Guide for Designers](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit)
- [ ] Read about [Double Diamond](https://medium.com/design-council/the-double-diamond-15-years-on-8c7bc594610e) is and how it works
- [ ] Review [this Figma file](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1) to further understand Stage 2A (outlined in history of UX/UI work) of project
- [ ] Watch [Figma's tutorials](https://www.youtube.com/watch?v=dXQ7IHkTiMM&ab_channel=Figma) on using Figma. There are other helpful tutorials on Youtube made by independent creators. 
### Role: Research 
- [ ] Follow the [experience profile guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit#slide=id.p) to create an experience profile on the [experience board](https://github.com/hackforla/UI-UX/projects/5) HfLA has created an experience profile so that members can use it to track their courses at Hack for LA. It also helps the team leads to identify what skills you have not completed during your time at HfLA. The profile is a template for all UX/UI/Researchers therefore not all skills are applicable. 
  - [ ] Add profile link as a comment on this issue
- [ ] Read the [Research Plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit#)
- [ ] Review the [recruiting process](https://docs.google.com/document/d/1wjpJCL7FsG2ly-u0eusIt3OR1b-tsc2zPZqSHFgZOFk) we use for the interview study
- [ ] Review our [interview session procedures](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit#)
- [ ] Read about [how to affinity diagram](https://www.nngroup.com/articles/affinity-diagram/)
- [ ] Read our [insights from the stakeholder interview](https://drive.google.com/drive/folders/1pUyX4rNLs0je5XZrcEdC-6n1YLQjONBb)

**Comment by kelenelee** [comment]
deleted the following
```
  - [ ] [Problem statement](https://docs.google.com/spreadsheets/d/1G7GvLnvqc7XSIgDNoK2c0NPw0UKcmvkyyduRQY3wXrI/edit#gid=0)
  - [ ] [Problem statement document coding - open coding](https://docs.google.com/spreadsheets/d/1UyQsUkGB3McEyK7YI-R6eM-dwhRphJVB94XbD00lQK0/edit#gid=0)
  - [ ] [Research objectives](https://docs.google.com/document/d/16fLMrwmJI6y0Hdh5sij_wKvwGT7eCuBvX9kIswmL7vQ/edit#). This document includes the latest version of our problem statement and research objectives. The section section has the older version of the problem statement and research objectives. 
```

**Comment by kelenelee** [comment]
moved into issue templates https://github.com/hackforla/design-systems/tree/main/.github/ISSUE_TEMPLATE
