### ISSUE TITLE
Research discovery phase history 

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#277]
### Overview
To retain the institutional knowledge within the Design Systems project it is important for newboarders to read up on why and how the Design System project was initiated. They need to understand how the project's aims and objectives have evolved over time through informed research insights. We need to create a Research  Discovery phase which sits inside #267 and also the Research role overview in the Wiki.

### Action Items

- [x] Read about the initiation and motivation for the Design Systems' project
- [x] Read the initial problem statement and research objectives
- [x] Read the revised problem statement and research objectives
- [x] Read the insight reports of the stakeholder interviews and user interviews
- [x] Write up the history of the discovery phase's user research so far in a few brief paragraphs
- [x] Please send to PM before posting

### Resources/Instructions
[Discovery history work in progress](https://docs.google.com/document/d/1EmJKj-KWt-0gJ5wxy2gPJnfOm3COQqGRt41VaJPKFco/edit)
[Research Plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit#) 
[Problem statement](https://docs.google.com/spreadsheets/d/1G7GvLnvqc7XSIgDNoK2c0NPw0UKcmvkyyduRQY3wXrI/edit#gid=0)
[Problem statement document coding - open coding](https://docs.google.com/spreadsheets/d/1UyQsUkGB3McEyK7YI-R6eM-dwhRphJVB94XbD00lQK0/edit#gid=0)
[Research objectives](https://docs.google.com/document/d/16fLMrwmJI6y0Hdh5sij_wKvwGT7eCuBvX9kIswmL7vQ/edit#)
 Location of the insight reports

**Comment by Hanastevenson** [comment]
Please reference https://github.com/hackforla/design-systems/wiki/UX-UI-Project-History

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by nasimbiglari** [comment]
I will be moving it to review section. The document is written, I need to check with PM regarding the titles of each section. I am not sure if we are using specific titles throughout the history documents of all teams.
