### ISSUE TITLE
Create artwork for the HfLA website

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#28]
### Overview
In order to place our project on the HfLA website we need to design artwork for the project card and project header.

### Action Items

- [x] Await logo lock up #13 
- [x] Design project card 600 x 400 image
- [ ] Design project header 1500 x 700 hero image (please do not put project title on hero image)

### Resources/Instructions
Reference design mock-up designed by Hana Stevenson

<img width="918" alt="Screenshot 2021-07-22 at 14 48 09" src="https://user-images.githubusercontent.com/6236085/126713766-c2790fd0-5758-43a1-9c0c-78a9ee65bcc9.png">

[Figma file](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=915%3A3934)

**Comment by Hanastevenson** [comment]
Anh Hoang is working on this card. Unable to assign awaiting Admin to allow access.

**Comment by Hanastevenson** [comment]
@ahoang94 Setting a deadline for this for the 9th August.

**Comment by Hanastevenson** [comment]
@ahoang94 Please update the following
- **Progress:** _How much progress have you made on the issue?_
- **Blocks:** _Are you facing any blockers?_
- **Availability:** _How much time do you have to work on it this week?_
- **ETA:** _When do you think it will be completed?_

**Comment by ahoang94** [comment]
@Hanastevenson 

I have a first draft of this ready in Figma! For the sake of verisimilitude, I created the gradient + header text that's shown on all Project pages on the HfLA website, but that can be easily hidden.

[https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=915%3A3934](url)

**Comment by Hanastevenson** [comment]
@ahoang94 Great first draft, nice usage of the brand colours on the infographic. I've iterated on your design and placed it in situ. I have two favourites, which I have not pointed out as I'd like your thoughts. Happy to chat through on Monday.

<img width="1356" alt="Screenshot 2021-08-20 at 19 30 26" src="https://user-images.githubusercontent.com/6236085/130308019-5fea8a14-7fd1-4aff-9913-4ea96858cd5a.png">

**Comment by Hanastevenson** [comment]
@ahoang94 As per our discussion please update the coding illustration and the speech bubble illustration.

**Comment by ahoang94** [comment]
@Hanastevenson All of the requested changes have been made to the hero image banner. I also added a subtle glow shadow to the elements to create some depth.

The project card has also been edited slightly to create a fuller background.
![Screen Shot 2021-08-24 at 8 35 35 PM](https://user-images.githubusercontent.com/85914721/130722333-6c2b5b91-07d5-4d88-ba31-c0b658e92c84.png)

**Comment by Hanastevenson** [comment]
This is the artwork that has been selected for the website.

![DS HFLA project card](https://user-images.githubusercontent.com/6236085/131415166-0d9245ee-7417-4466-a5f4-5d14fdfc7139.jpg)
![FINAL Hero Image](https://user-images.githubusercontent.com/6236085/131415170-eebe4b7b-c1d3-428c-a3a1-12392701bc6a.jpg)
