### ISSUE TITLE
Individual interviews, participants 1-11

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#280]
#### Dependencies
- https://github.com/hackforla/design-systems/issues/374
- https://github.com/hackforla/design-systems/issues/326
- https://github.com/hackforla/design-systems/issues/162
- https://github.com/hackforla/design-systems/issues/177

Recruiting spreadsheet https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk

Analysis Figma file https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam?node-id=0%3A1
# Interviews

- [x] P1 interviewed by @JeannyRen
- [x] P2 interviewed by @JeannyRen
- [x] P3 interviewed by @navarroliuanthony
- [x] P4 interviewed by @avknutson
- [x] P5 interviewed by @hdchangie #336
- [x] P6 interviewed by @kmedhi
- [x] P7 interviewed by @kmedhi
- [x] P8 interviewed by @rosaliechung #351
- [x] P9 interviewed by @kelenelee
- [x] P10 interviewed by @cunninghamej
- [x] P11 interviewed by @hdchangie

#### Template
```
### Overview
This ticket will prepare the interviewer to be on the right track for conducting a successful user interview. All the steps has been thoroughly explained in the [interview guide](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit). It's crucial to read and study this document before to have a better understanding of the process.

### Action Items
**Make sure you read:**
- [ ] The best practices before the interview.
- [ ] Things to do before the interview
- [ ] Things to do after the interview

### Resources/Instructions
[Interview guide
](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit)
[Participants Interview
](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit)
```
- Note-taking #281 
- Analysis #279

**Comment by kelenelee** [comment]
| P# | Interviewer | Note-taker | Analyzers |
| - | - | - | - |
| 1 | # @ | # @ | # @ |
| 2 | # @ | # @ | #324 @navarroliuanthony @kelenelee |
| 3 | # @ | # @ | #355 @navarroliuanthony @rosaliechung |
| 4 | # @ | # @ | #356 @hdchangie |
| 5 | # @ | # @ | #398 @kelenelee |
| 6 | # @ | #345 @rosaliechung | #357 @rosaliechung #365 @kelenelee |
| 7 | # @ | #342 @JeannyRen  | #400 @hdchangie @navarroliuanthony |
| 8 | #351 @rosaliechung  | # @ | # @ |
| 9 | # @ | # @ | #366 @kelenelee @hdchangie |
| 10 | # @ | #364 @JeannyRen | # @ |
| 11 | # @ | # @ | #389 @kelenelee |
