### ISSUE TITLE
Create new link for Research meeting 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#282]
### Overview
The research meeting needs to be a Zoom meeting rather than Google meet. 

### Action Items
- [x] log into 1 password
  - [x] go to zoom vault 
- [x] open spreadsheet 
   - [x] read instructions
   - [x] add new record for meeting onto schedule
   - [x] choose an available zoom link (being mindful of the other teams that might be using the link before or after your team meeting time.
- [x] Create a new recurring meeting in the zoom account you choose
- [x] Edit the invite calendar link to include the new invite URL
- [x] Inform PM of new link
- [x] Update the link in this column Project Info column on the board.
- [x] Update the link in the wiki [Getting Started page](https://github.com/hackforla/design-systems/wiki/Getting-Started)

**Comment by allthatyazz** [comment]
Completed as part of Issue #352 .
