### ISSUE TITLE
Create new link for All team meeting

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#283]
### Overview
The Design System team have a number of new joiners to who are based on the East coast. The all team meeting on Monday time will be changed to accommodate their timezone. Dependent on the popular vote in the Slack channel.

### Action Items
- [x] Create a new link
- [x] Edit the invite calendar link
- [x] [Update the link in this column ](https://github.com/hackforla/design-systems/projects/1#card-65086075)
- [x] Update the link in the wiki [Getting Started page](https://github.com/hackforla/design-systems/wiki/Getting-Started)
- [x] Discuss with Bonnie in https://github.com/hackforla/design-systems/issues/89#issuecomment-1015777418

**Comment by ExperimentsInHonesty** [comment]
You can open an issue on the VRMS repo by using this template for [meeting time change](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by Hanastevenson** [comment]
Issue has been created on the VRMS repo. https://github.com/hackforla/VRMS/issues/964
