### ISSUE TITLE
01:A Design System Reading

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#284]
'Design Systems' by Alla Kholmatova is one of the key books people refer to when discussing design systems.

### Action Items
- [x] Read chapter 1 
- [x] Add your comments and key learnings to [Discussion thread](https://github.com/hackforla/design-systems/discussions/198)

_**Optional but educational:**_
- [ ] Download and read Invision [Design Systems Handbook](https://www.designbetter.co/design-systems-handbook)
- [ ] Defining [Design Systems](https://medium.com/eightshapes-llc/defining-design-systems-6dd4b03e0ff6) - 7 minute read
- [ ] Read or listen to this 15 minute podcast [Design Systems](https://podcast.clearleft.com/season01/episode01/)
- [ ] Read [Picking Parts, Products & People](https://medium.com/eightshapes-llc/picking-parts-products-people-a06721e81742) A 6 minute read.

### Resources/Instructions
Design Systems by Alla Kholmatova
* [There is a kindle option to buy. ](https://www.amazon.com/Design-Systems-Smashing-eBooks-Kholmatova-ebook/dp/B076H49W1G)
* [Hard cover book ](https://www.amazon.com/Design-Systems-practical-creating-languages/dp/3945749581)
* There is also an online version from [Smashing Magazine.](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf)

**Comment by kelenelee** [comment]
done @nasimbiglari @JeannyRen

**Comment by JeannyRen** [comment]
Okay, noted 👍
