### ISSUE TITLE
Design High-Fidelity Screens for Figma Foundation

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/design-systems#295]
### Overview
Based on the Figma foundation work within the [Figma file](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/?node-id=2%3A26) team members should build out their own version of high-fidelity screens. 

### Action Items

- [x] Design 6 screens for the following sections:

- Foundations Introduction
- Project Figma Cover Artwork
- Creating a Start Page
- Incorporating a Cover Image
- Creating a File Menu
- Creating a Plugin Library

### Resources/Instructions

- Be sure to incorporate the content already written out in the existing screens
- You do not need to imitate the layout of what's already existed, feel free to use any of the included mood board examples on [this Figma page](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/?node-id=2%3A26) OR find your own inspiration!

**Comment by Hanastevenson** [comment]
@rcurtis2 No need to finish this for next week, as this will be one of the first UI designs the new joiners will be working on as well.

**Comment by kelenelee** [comment]
- [ ] #299 
- [ ] #321 
- [ ] #322
