### ISSUE TITLE
Design High-Fidelity Screens for Figma Foundation

### ISSUE THREAD

**Issue by AdesinaBernard** [hackforla/design-systems#299]
### Overview
Based on the Figma foundation work within the [Figma file](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/?node-id=2%3A26) team members should build out their own version of high-fidelity screens. 

### Action Items

- [ ] Design 6 screens for the following sections:

- Foundations Introduction
- Project Figma Cover Artwork
- Creating a Start Page
- Incorporating a Cover Image
- Creating a File Menu
- Creating a Plugin Library

### Resources/Instructions

- Be sure to incorporate the content already written out in the existing screens
- You do not need to imitate the layout of what's already existed, feel free to use any of the included mood board examples on [this Figma page](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/?node-id=2%3A26) OR find your own inspiration!

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by Hanastevenson** [comment]
@AdesinaBernard since you are leaving the project, shall I close this Issue?

**Comment by Hanastevenson** [comment]
I am closing this ticket since there has been no communication.
