### ISSUE TITLE
Create ReadMe file

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#3]
### Overview
We need to create a ReadMe file for new starters joining the project.

### Action Items

- [x] PM to add Project title and description, How to contribute and Contact information
- [x] Developer to Include Installation instructions

### Resources/Instructions
https://github.com/hackforla/design-systems

**Comment by Hanastevenson** [comment]
@qiqicodes are we at the stage where we can include 'installation instructions' in the Read Me?

**Comment by Hanastevenson** [comment]
# Read me as 8/23/2021 

# Project title and description

The Design System initiative seeks  to empower volunteers with the tools, documentation and templates for creating and maintaining a design system for their HfLA projects.  As Hack for LA continues to scale it has become more essential to create consistent documentation and standards for deliverables. 

### Project context

For more information on the project development, refer to: Design Systems Project One Sheet. You can also read more about our project on our [Wiki.](https://github.com/hackforla/design-systems/wiki)

### Technology used

- GitHub: [Design Systems project board](https://github.com/hackforla/design-systems/projects/1)
- Slack: [Design-System](https://hackforla.slack.com/archives/CH2U1CB9Q)


# How to contribute

To join the team, contact the Product Manager, [Hana Stevenson](https://hackforla.slack.com/archives/DJ32EQPSL), on our HfLA Slack and ask if there are any available volunteer opportunities. If there are no open roles please add yourself to the 'People wanting to join the project' [team roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI/edit#gid=1806338047) 

-  The entire team has a weekly meeting on Monday's 6:30pm - 7:30pm PST via [Zoom](https://us02web.zoom.us/j/88447401964?pwd=cUkyNFNKVGZRckxzRkdrT1luVVJ3dz09)
-  The Research team within this project meet on Thursday's 11:00am - 11:44am PST via [Zoom](https://ucdavis.zoom.us/j/9086200793)
-  The UX/UI team within this project meet on Wednesday's 7:30pm - 8:30pm PST via [Zoom](https://us02web.zoom.us/j/83882486384)
-  The Developement team within this project do not have a fixed day of the week. Together team decided on a day. 


## Installation instructions

1. Step-by-step instructions help new contributors get a development environment up and running quickly.
2. You'll want to find the balance between being specific enough for novices to follow, without being so specific that you reinvent the wheel by providing overly-basic instructions that can be found elsewhere.
3. Feel free to adapt this section and its sub-sections to your own processes.
4. Alternatively, you can move everything from *Installation instructions* through *Testing* to a separate **Contributing.md** file to keep your **ReadMe.md** more succinct.


### Working with issues

- Explain how to submit a bug.
- Explain how to submit a feature request.
- Explain how to contribute to an existing issue.

To create a new issue, please use the blank issue template (available when you click New Issue).  If you want to create an issue for other projects to use, please create the issue in your own repository and send a slack message to one of your hack night hosts with the link.


### Working with forks and branches

- Explain your guidelines here.


### Working with pull requests and reviews

- Explain your process.


### Testing

- Provide instructions.


# Contact info

 Product Manager - [Hana Stevenson](https://hackforla.slack.com/archives/DJ32EQPSL), on our HfLA Slack.



### Licensing

Include details about the project's open source status.

*this readme file sourced from [Jessica Sand](http://jessicasand.com/other-stuff/just-enough-docs/)*

**Comment by Hanastevenson** [comment]
# Working Draft

# Hack for LA Design Systems

The Design System initiative seeks  to empower volunteers with the tools, documentation and templates for creating and maintaining a design system for their HfLA projects.  As Hack for LA continues to scale it has become more essential to create consistent documentation and standards for deliverables. 

### Project context

For more information on the project development, refer to: Design Systems Project One Sheet. You can also read more about our project on our [Wiki.](https://github.com/hackforla/design-systems/wiki)

### Technology used

- GitHub: [Design Systems project board](https://github.com/hackforla/design-systems/projects/1)
- Slack: [Design-System](https://hackforla.slack.com/archives/CH2U1CB9Q)


# How to contribute

To join the team, contact the Product Manager, [Hana Stevenson](https://hackforla.slack.com/archives/DJ32EQPSL), on our HfLA Slack and ask if there are any available volunteer opportunities. If there are no open roles please add yourself to the 'People wanting to join the project' [team roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI/edit#gid=1806338047) 

-  The entire team has a weekly meeting on Monday's 6:30pm - 7:30pm PST via [Zoom](https://us02web.zoom.us/j/88447401964?pwd=cUkyNFNKVGZRckxzRkdrT1luVVJ3dz09)
-  The Research team within this project meet on Thursday's 11:00am - 11:44am PST via [Zoom](https://ucdavis.zoom.us/j/9086200793)
-  The UX/UI team within this project meet on Wednesday's 7:30pm - 8:30pm PST via [Zoom](https://us02web.zoom.us/j/83882486384)
-  The Development team within this project do not have a fixed day of the week. Together team decided on a day. 

# Contact info

 Product Manager - [Hana Stevenson](https://hackforla.slack.com/archives/DJ32EQPSL), on our HfLA Slack.



### Licensing

Include details about the project's open source status.

*this readme file sourced from [Jessica Sand](http://jessicasand.com/other-stuff/just-enough-docs/)*

**Comment by qiqicodes** [comment]
The [developer's contributing guide](https://github.com/hackforla/design-systems/wiki/Developer-Contributing-Guide) is ready for our current project progress.
