### ISSUE TITLE
Update HfLA website: team members and check all info

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#302]
### Overview
A number of people have left the DS team and we have an influx of new joiners. The [HfLA DS project](https://www.hackforla.org/projects/design-systems) needs updating. 

### Action Items

As per discussion in the [stakeholder meeting,](https://github.com/hackforla/design-systems/issues/89#issuecomment-1015777418) Gather the following:
- People to add
  - [x] Name
  - [x] GitHub handle
  - [x] Role
   - [x] SLACK ID
- [x] List people to remove:
  - [x] name only
- [x] Open a new issue on the hackforla.org website repo to review all the project details and submit any changes
  - [ ] Add a link to the new issue to the resources below
- [ ] Have Bonnie prioritize the issue.

### Resources/Instructions
- ~[Google document](https://docs.google.com/document/d/1Cdv4vYxltM3Pi8QYfsSWZpDXAH-m0BuGgAkHJ0vRK8A/edit?usp=sharing)~ don't need, [list is below](https://github.com/hackforla/design-systems/issues/302#issuecomment-1031935412)
- Open Issue on hack for LA website repo to project card [here](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [New issue for editing on hfla website](https://github.com/hackforla/website/issues/2745)

**Comment by ExperimentsInHonesty** [comment]
### Add  Team members:
Name: Kelene Lee
Role: Researcher
Slack ID: U02U49VDV2L
GitHub Handle:kelenelee

Name: Rosalie Chung
Role: Researcher
Slack ID: U02T55RNL1M
GitHub Handle:rosaliechung

Name: Kashmiri Medhi
Role: Researcher 
Slack ID: U02T0QMNBT9
GitHub Handle: kmedhi

Name: Dongchen Hou
Role: Researcher
Slack ID: U02QPKCB7UN
GitHub Handle:hdchangie

Name: Wataru Inoue
Role: UX/UI Designer
Slack ID: U02SMT4H4LR
GitHub Handle:winoue90

Name: Alena Yanovich
Role: UX/UI Designer
Slack ID: U02R5908WF2
GitHub Handle: alenayaovich

### People to remove:
Bernard Adesina
Ryan Curtis
Anna Knutson
Anastasia Nekrasova
Anh Hoang

**Comment by allthatyazz** [comment]
### Add  Team members:
Name: Yasaman Roostaeian
Role: Product Manager
Slack ID: U033GFQ1UQM
GitHub Handle:allthatyazz


Name: Wataru Inoue
Role: Lead UX/UI Designer
Slack ID: U02SMT4H4LR
GitHub Handle:winoue90

Name: Tammy Trinh
Role: UX/UI Designer
Slack ID: U02RZRF34DA
GitHub Handle:tamalatrinh

Name: Nana Yaa Ansah
Role: UX/UI Designer
Slack ID: U020E4AAQ3G
GitHub Handle:nansah

Name: Kelene Lee
Role: Researcher
Slack ID: U02U49VDV2L
GitHub Handle:kelenelee

Name: Dongchen Hou
Role: Researcher
Slack ID: U02QPKCB7UN
GitHub Handle:hdchangie

Name: Eric J Cunningham
Role: Researcher
Slack ID: U02V6PA5NJY
GitHub Handle:cunninghamej





### People to remove:
Hana Stevenson
Bernard Adesina
Ryan Curtis
Anna Knutson
Anastasia Nekrasova
Anh Hoang

**Comment by allthatyazz** [comment]
### Add  Team members:
Name: Yasaman Roostaeian
Role: Product Manager
Slack ID: U033GFQ1UQM
GitHub Handle: allthatyazz


Name: Wataru Inoue
Role: Lead UX/UI Designer
Slack ID: U02SMT4H4LR
GitHub Handle: winoue90

Name: Tammy Trinh
Role: UX/UI Designer
Slack ID: U02RZRF34DA
GitHub Handle: tamalatrinh

Name: Kelene Lee
Role: Researcher
Slack ID: U02U49VDV2L
GitHub Handle: kelenelee

Name: Dongchen Hou
Role: Researcher
Slack ID: U02QPKCB7UN
GitHub Handle: hdchangie

Name: Eric J Cunningham
Role: Researcher
Slack ID: U02V6PA5NJY
GitHub Handle: cunninghamej


Name: Sandra Berjan
Role: UX Writer
Slack ID: U03753VQBSR
GitHub Handle: sandraberjan

Name: Joyce Chang
Role: Researcher
Slack ID: U02U727NYM9
GitHub Handle: tfeng95725



### People to remove:
Nasim Biglari
Jeanette Renema
Hana Stevenson
Bernard Adesina
Ryan Curtis
Anna Knutson
Anastasia Nekrasova
Anh Hoang

**Comment by JeannyRen** [comment]
@allthatyazz I will assign you for the time being, feel free to assign this ticket away :-)
