### ISSUE TITLE
02: My Experience Profile

### ISSUE THREAD

**Issue by hdchangie** [hackforla/design-systems#306]
###Overview
HfLA has created an experience profile so that members can use it to track their courses at Hack for LA. It also helps the team leads to identify what skills you have not completed during your time at HfLA.

### Action Items
- [x] Read the [experience profile guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit#slide=id.p) 
- [x] Create experience profile
- [x] Add link as a comment before closing

### Resources/Instructions
[Link to experience board](https://github.com/hackforla/UI-UX/projects/5)

**Comment by hdchangie** [comment]
https://github.com/hackforla/UI-UX/issues/197

**Comment by JeannyRen** [comment]
Hi @hdchangie ! I noted your experience profile. Do you have any questions about this issue, or do you want me to close it?

**Comment by hdchangie** [comment]
Thanks, @JeannyRen! It's completed and can be closed (which is done by Nas already).
