### ISSUE TITLE
02: My Experience Profile: Kashmiri Medhi

### ISSUE THREAD

**Issue by kmedhi** [hackforla/design-systems#308]
###Overview
HfLA has created an experience profile so that members can use it to track their courses at Hack for LA. It also helps the team leads to identify what skills you have not completed during your time at HfLA.

### Action Items
- [x] Read the [experience profile guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ/edit#slide=id.p) 
- [x] Create experience profile
- [x] Link to profile: [UI/UX Experience Profile: Kashmiri Medhi](https://github.com/hackforla/UI-UX/issues/213)

### Resources/Instructions
[Link to experience board](https://github.com/hackforla/UI-UX/projects/5)

**Comment by JeannyRen** [comment]
Hi @kmedhi, do you have any questions about your experience profile? You can shoot me a message :-)

**Comment by kmedhi** [comment]
@JeannyRen Thanks for checking in! I just followed the tutorial and finished the task.
