### ISSUE TITLE
Split the Second draft into separate documents

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#312]
### Overview
The second draft of the Design System guide is far too long and needs to be split into multiple documents which will represent different pages on the Tool kit page. 

### Action Items

- [x] Divide the content into the [following sections.](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/?node-id=2%3A21)

### Resources/Instructions
[Second Draft of Guide](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit?usp=sharing)

**Comment by kelenelee** [comment]
there was no section on setting up a figma file. otherwise I have separated the long doc into separate docs.
