### ISSUE TITLE
Create a survey for new joiners to HfLA for onboarding onto their teams.

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#313]
### Overview
The first user research results showed the research team that the project onboarding and offboarding process may possibly be an important driver of information loss. With this survey we wish to verify challenges and successes in the project onboarding and offboarding processes. The results will be input for the development of user personas and journeys; later informing the design team. 

### Action Items
- [x] Analysis of user interviews with regards to the project onboarding process
- [x] Prioritizing the importance of insights
- [x] Formalizing the key concepts
- [x] Translation of the key concepts into measurements (survey questions)
- [x] Creating survey
- [x] Look for Survey platform avenues for free plan possibilities
- [x] Inform PM

### Resources/Instructions
[Research discovery phase Figjam](https://www.figma.com/file/DWs6sVSCJvH1y6J5FvapfO/Research---Discovery-Phase--FigJam)
[UXR Interview Figjam](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam)
[Survey draft](https://docs.google.com/document/d/1zuFgBkTl_4RzNJbCZvIXVWoj5z6RMOOQwFPRP-PUNQI/edit#)

**Comment by Hanastevenson** [comment]
@JeannyRen as discussed. Please add content to this ticket.

**Comment by JeannyRen** [comment]
@rcurtis2, in prep for our meeting please see the section on the onboarding analysis in the UXR interview Figjam and the work up till now in the Research Discovery Phase Figjam. It is Tuesday evening now and I will continue drafting the survey tomorrow :-)

**Comment by JeannyRen** [comment]
First draft is ready, working on finalizing the survey.

**Comment by Hanastevenson** [comment]
@JeannyRen added feedback to the document.

**Comment by JeannyRen** [comment]
@JeannyRen brief note: Free plan of typeform can only register 10 respondents per month.

**Comment by JeannyRen** [comment]
@Hanastevenson @nasimbiglari We can get a free Plus plan at SoGoSurvey (for Hack for LA), I just had a conversation with them and they will send me the necessary links.

**Comment by JeannyRen** [comment]
@Hanastevenson and @allthatyazz. This week I have finalized the survey development so far. This issue will be followed by issue #350 to program and pilot the onboarding survey.
