### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#32]
### Overview
This card is a reference to pause in the issue that it is linked to. Accessibility is important to bring in at the beginning to have it be properly integrated into a project. Below are the specific action items that need to be considered the issues it is linked to. 

Please reach out to Ciara (Kiki) Salmon
- Slack: Ciara Salmon

Kiki is a resource in accessibility and can assist in this process. You can also educate your self on typical accessibility considerations from this [Accessibility Document](https://drive.google.com/drive/folders/12Jl0yPWBWLe0vkczy1wBonyfEFx39iHI?usp=sharing)

### Action Items
Links with 
- interview script #29 
Action items:

- [ ] Review interview questions to add open ended questions regarding current accessibility standards for each script

- Insight/analysis (no card at this time) 
Action items:

- [ ] Just want to confirm accessibility is considered in analysis

- Persona #24 
Action items:

- [ ] Show how accessibility is current considered or not considered in each persona
- [ ] Consider not just how accessibility needs to go into the design system but also how we create the design system to meet persona needs (our population is very neurodiverse and have different physical abilities) 

- Create journey map #10 
Action items:

- [ ] Consider where opportunities are for accessibility in journey map 

### Resources/Instructions
Will add

**Comment by Leah0996** [comment]
@allthatyazz

**Comment by Leah0996** [comment]
Is it possible I can get access to the accessibility document? @allthatyazz
