### ISSUE TITLE
Walk through the current Figma File

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#33]
### Overview
We need to have an understanding of the current Figma so that we can learn about the research previously conducted.

### Action Items

- [x] Arrange a time in the next two weeks (26th July - 9th July)
- [x] Walk through the document 
- [ ] Record the meeting and upload to the Drive

### Resources/Instructions
[Figma Document](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=28%3A4)

**Comment by daniellex0** [comment]
1. Progress: We had a meeting first going over the goals of the Figma design system file, and our follow-up meeting was to design a button component for the developers. Our next meeting will be covering this topic and our approach to cleaning up the Figma file
2. Blocks: other meetings we had to have first
3. Availability: flexible
4. ETA: 2 weeks
