### ISSUE TITLE
Explore how we might guide a user through a Figma Foundation document

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#34]
### Overview
The Figma document needs to include instructions/information alongside the designs.  How might we guide people through a Figma document.

### Action Items

- [ ] Explore the different ways in which designers could use Figma creatively. Think signposting, links etc..
- [ ] Collate research into a document to share with a group

### Resources/Instructions
[Figma Document](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=28%3A4)
Links to Issues #33

**Comment by kelenelee** [comment]
current usability tests are exploring this https://github.com/hackforla/design-systems/issues/376
