### ISSUE TITLE
P7 Interview

### ISSUE THREAD

**Issue by kmedhi** [hackforla/design-systems#340]
Overview

This ticket will prepare the interviewer to be on the right track for conducting a successful user interview. All the steps has been thoroughly explained in the [interview guide](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit). It's crucial to read and study this document before to have a better understanding of the process.
Action Items

Make sure you read:

- [x] The best practices before the interview.
- [x] Things to do before the interview
- [x] Things to do after the interview

Resources/Instructions

[Interview guide
](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit)
[Participants Interview](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit)

**Comment by kmedhi** [comment]
The tasks have been completed. @JeannyRen

**Comment by JeannyRen** [comment]
Thank you @kmedhi. I will close the ticket now :-)
