### ISSUE TITLE
Create new calendar invite for the All Team meeting

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#344]
### Overview
The PM has left the project. The invite was previously being sent from the PM's personal email account therefore a new one needs to be created.

### Action Items

- [x] Create a new invite with the following information:
- Reoccurring - Monday's 5:30-6:30 PST (no need to update any info on the website)
- Use the same Zoom link - https://us02web.zoom.us/j/88447401964?pwd=cUkyNFNKVGZRckxzRkdrT1luVVJ3dz09
- Create a new Slack reminder for Monday's.
- Use email addresses found in the Roster
- [x] Slack Hana Stevenson (old PM) so she can delete the old calendar invite

### Resources/Instructions
[Roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI/edit?usp=sharing)

**Comment by allthatyazz** [comment]
The new Calendar invite has been sent to all active members.

**Comment by allthatyazz** [comment]
Further progress about this issue can be viewed here : 
- #352
