### ISSUE TITLE
Creating Calendar/ Zoom setup for each team meeting

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#352]
### Overview
We need to have accurate Google calendar invites and professional links for zoom set up so that new team members can easily join meetings without fearing the interruption due to the time limit.

#### Details
The Calendar invites need to be owned by designsystems@hackforla.org and editable by any attendee. 

### Action Items
- [x] Document your experience trying to join the team
- [x] Ask team when their meetings are in Slack
- [ ] Get invited to any meeting that uses Google Calendar 
- [x] Identify who the owners are for the Calendar invites
- [ ] If Calendar invites exist, 
  - [ ] the owner should check the box for Modify Event (under Guest permission)
  - [ ] ask the owner to "change ownership" to designsystems@hackforla.org
 - [x] Update Wiki with the accurate times for the meetings
 
### Resources/Instructions
[The Wiki Page with the meeting times](https://github.com/hackforla/design-systems/wiki/Getting-Started#getting-started)

**Comment by allthatyazz** [comment]
Prior to attending the UXR meeting on Tuesday 2/22, Both Bonnie and I asked team members to add me to the calendar invite but since no one added me, I had to attend the meeting through a zoom link posted on Slack.

**Comment by ExperimentsInHonesty** [comment]
Key takeaways from process so far
1. it dosent seem like they have a calendar invite.
2. they are making use of private group chats which means that you can't join and see the history
3. they are not using the zoom accounts available via the org.

**Comment by ExperimentsInHonesty** [comment]
### Ideal process
1. Someone messages in the channel that they would like to join the team.
2. If you they don't specific their role, someone asks them.
3. They are directed at the wiki
4. The wiki has steps for them to get onboarded.

### Onboarding
This will get customized for this team.  However a typical process is 
1. A prework issue (see example from [hfla website](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2C+good+first+issue%2C+role%3A+user+research&template=pre-work-template---ux.md&title=Pre-work+Checklist%3A+Researcher%3A+%5Breplace+brackets+with+your+name%5D).  prework issues for other roles can be found [here](https://github.com/hackforla/website/issues/new/choose))

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz Hana provided links to these issues in the chat.  please also make sure you annotate this issue will all info related to it from the chat or phone/zoom conversations 😀
- #331 
- #344

**Comment by allthatyazz** [comment]
- 2022-02-23 
  - I contacted Hana (the previous PM) and requested a zoom meeting at her convenience. I also asked about the Calendar invites situation which was an urgent issue at hand. 
- 2022-02-24
  - Hana responded to my meeting request and I sent a zoom link to her.
  - In the meantime, Hana messaged #design-systems Slack and messaged ```I’ve responded to the Yasaman,
Before I left I created a number of tickets to update the zoom links (as discussed in our PM meetings with Bonnie, Jeanette, and Nas)
The all agenda meeting needs to have a new calendar invite  please review this ticket - https://github.com/hackforla/design-systems/issues/344
Ryan (UX/UI) has left the project and there needs to be a new Zoom link as he was using his own personal one.
https://github.com/hackforla/design-systems/issues/331
Please discuss this ticket with the research team https://github.com/hackforla/design-systems/issues/331```
  -Hana and I had a 40-minutes meeting about the history of the project, the roadmap that has been defined by Hana, some common problems about onboarding new joiners, and the Github issues Hana created for the new PM. These issues are detailed and meant to serve as step-by-step instructions for the new PM.

**Comment by allthatyazz** [comment]
My observations so far : 
 - except for All team meetings, there is no specific Calendar Invites.
 - As per #344, It is easier to set up a new Calendar invite rather than asking the previous PM to modify the previous invite. 
 - There is essentially no UX/UI meeting because there is no active team member.

**Comment by allthatyazz** [comment]
New Calendar Invite for All Team meeting has been set up and all the active members have been added to the invite. The zoom link for this event seems to belong to one of HfLA's zoom accounts.

**Comment by allthatyazz** [comment]
@ExperimentsInHonesty  In order to set up a professional zoom link for Design Systems Research meetings, I need to first gain access to the  Google document "how-to: meeting assignment" with instructions about using Zoom accounts. Can you grant the access?

**Comment by allthatyazz** [comment]
As of 2/28/2022, calendar invites have been set up for all the DS team meetings. All these invites have been organized and owned by designsystems@hackforla.org. The day/time of the meetings is as follows. 

  - All Team meetings on Mondays at 5:30 pm- 6:30 pm PST
  - Research team meetings on Tuesdays at 11:00 am -11:45 am PST
  - UX/UI team meetings on Tuesdays at 6:00 pm- 7:00 pm PST

**Comment by allthatyazz** [comment]
New Zoom links were created for research and UX/UI  teams on 3/3/2022 using HfLA's accounts. The calendar invites and GitHub's board all should reflect the new links. The previous PM used to put the meeting links on the team's Wiki page. Based on my talks with Bonnie, it is decided that the meeting links are better to be removed from the Wiki but remained on GitHub's board.
