### ISSUE TITLE
Create interview questions & script for designers

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#36]
### Overview
As a team we have identified that a designer of a HfLA project would be a user of a Design System.
We need to create user journey map to understand user needs and pain points in creating design systems.

This Issue links to #10 

### Action Items

- [x]  Review our interview goals and objectives
- [x] Create interview questions
- [x]  Add to the below document " Final Questions"
- [x]  Inform UX Research Lead when this has been completed

### Resources/Instructions
[Designers Questions](https://docs.google.com/document/d/1AKkga6ewbK8og331SIKpghkY4nDALkHehgUCExFbRZY/edit)
[Interview guide development history](https://docs.google.com/document/d/1fLzb_hrqgfjioXxDDOOMfMgT2oJ3Gi3h1snCOAWWEcc/edit?usp=sharing)
[[Final questions] ](https://docs.google.com/document/d/1fLzb_hrqgfjioXxDDOOMfMgT2oJ3Gi3h1snCOAWWEcc/edit?usp=sharing)
[List of people to interview](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit?usp=sharing)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by Leah0996** [comment]
@allthatyazz
