### ISSUE TITLE
Interview Protocol Revision 

### ISSUE THREAD

**Issue by rosaliechung** [hackforla/design-systems#374]
### Overview
In a recent research meeting, we discussed reframing our interview protocol for the question about defining design systems to make participants feel more comfortable during the interview. This ticket represents the work of rewording that section of the interview protocol.

### Action Items
- [x] Make edits to original interview protocol using track changes.
- [x] Update the finalized/approved edits into each interview protocol (for PMs, developers, designers). 

### Resources/Instructions
[Interview protocol](https://docs.google.com/document/d/1fLzb_hrqgfjioXxDDOOMfMgT2oJ3Gi3h1snCOAWWEcc/edit#heading=h.2egvzr5n6rn3)

**Comment by rosaliechung** [comment]
@nasimbiglari @JeannyRen - I made the edits to the "master" interview questions document (see link on this issue). Can you check the language to make sure it's okay and then I can copy/paste it into each interview protocol document?

**Comment by JeannyRen** [comment]
@rosaliechung. I love it. Thank you so much for helping us out :-) You can copy paste it into each interview protocol document. As a general note, we should also copy paste it into the individual (PM/Designer/Developer) interview folder.

**Comment by rosaliechung** [comment]
Yes, I just fixed it on the rest of the document as well as in each interview and note-taking document in the individual PM/designer/developer folders. I did not do track changes and just copied and pasted the new edits in. Let me know if you have any questions or need anything else!

**Comment by JeannyRen** [comment]
@rosaliechung thank you so much! Your work is much appreciated!

**Comment by kelenelee** [comment]
- [ ] https://github.com/hackforla/design-systems/issues/177
