### ISSUE TITLE
Building Personas for the Figma Foundations Tutorial

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#375]
### Overview
Based on the Figma foundations tutorial, team members should build out their own version of a Persona / or personas who would use the tutorial. The goal of this exercise is to create empathy with users who are about to use our tutorial and implement some changes to their projects' Figma file.

### Action Items

- [x] Create a persona who will use the tutorial. We have some information about the persona who is a UX designer for one of the Hack for LA's projects. You can base the persona on yourself too, but there is extra information in the resource section as well. 
- [x] The persona should have at least these 4 sections: a name, a picture, relevant goals, and frustrations. 
- [x] Be sure to include your persona in the [FigJam](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1). 
- [x] Comment here once you completed the task.

### Resources/Instructions
- You can review the [interviews](https://drive.google.com/drive/folders/1kX4hkM8kV5lncdqeEQf7lAZH7Rq6wTkb?usp=sharing) that our UXRs conducted with HfLA's designers.

**Comment by winoue90** [comment]
I've made a rough persona to begin with and added it to the Figjam to the right of the affinity map for the Figma Foundation pages.

**Comment by tamalatrinh** [comment]
I started working a proto persona and added it to the Figjam below Wataru's persona.

**Comment by allthatyazz** [comment]
@hangjoyce has also completed her persona for the project. This issue would be closed.
