### ISSUE TITLE
Plan the cover page usability test

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#377]
### Overview
We need to have a proper research plan for the usability studies aimed at measuring the success of Figma Foundations.

### Details
HfLA’s Design Systems (DS) team has conducted a series of audits on 22 HfLA projects’ main Figma files since November 2021. The audits revealed a lack of consistency in the way each team creates and maintains their Figma files. In response to the needs of HfLA’s Executive Director ( Stakeholder)  and with the aim of creating consistency across the organization, the DS team proposed a guide called Figma Foundations. Figma Foundations includes a set of instructions and templates for current and future teams at HfLA to adopt. 

### Action Items
 - [x] #396 
 - [x] Receive feedback from designers
 - [x] Incorporate the feedback into the research plan
 - [x] Finalize the Research script before the first test
 

### Resources/Instructions
[Figma Foundations]( https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A7)
[Initial Research plan](https://docs.google.com/document/d/1ZKyFtjGlgBsmbFV1M56IwPxN9PUDP9_U4CA4Yd4QYxc/edit?usp=sharing) 
[Reworked research plan](https://docs.google.com/document/d/1vFq7jCgjapp7PLdycnDU3UFvowJIk4zZWwbas6BvtCw/edit?usp=sharing)

**Comment by kelenelee** [comment]
Usability research plan template

## 1. Required readings

- [ ] [About usability testing](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)
- [ ] [Types of usability testing methods](https://www.usability.gov/how-to-and-tools/methods/running-usability-tests.html)
- [ ] [Writing a plan and types of metrics](https://www.usability.gov/how-to-and-tools/methods/planning-usability-testing.html)
- [ ] [Myopic metrics](https://medium.com/delta-cx/your-cx-and-ux-metrics-are-myopic-9470d5956969)
- [ ] [Recruiting](https://www.usability.gov/how-to-and-tools/methods/recruiting-usability-test-participants.html)

## 2. Writing the sections of the plan

- [ ] **Scope** (what is being tested)
- [ ] **Purpose** (why is this being tested, concerns, questions, goals for the test)
- [ ] **Sessions** (length, buffer between sessions)
- [ ] **Equipment** (software) used to conduct and record test
- [ ] **Participants** (number, type, recruiting methods)
- [ ] **Scenarios** (what task the participant will be asked to complete)
- [ ] **Method** (think-aloud or probing)
- [ ] **Researcher roles** (who does what)
- [ ] **Questions asked** (before and after task)
- [ ] **Metrics** for success

## 3. Testing

- [ ] Read through and discuss the plan with fellow researchers
- [ ] Pick one facilitator and at least one note-taker
- [ ] Paste the finalized research plan in Github comments and link the Google Doc draft
- [ ] Run a pilot at least a few days before a real session, and make notes how the pilot went in Github issues comments

**Comment by kelenelee** [comment]
Appears to be done!
