### ISSUE TITLE
Weekly Label Check

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/design-systems#378]
### Overview
We need to perform a weekly check on issues to make sure they all conform to our label and milestone schema.

### Action Items
- [ ]  Check to see if there are any issues that have not yet been added to [project board](https://github.com/hackforla/design-systems/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
     - [ ] if yes, add to project board 
- [ ] Check the following to make sure that they are all 0 open (Links for checking to make sure that all issues either have a ___ or a ____ missing label)
   - [feature](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Feature+-++Agenda%22+-label%3A%22Feature+-+Audit%22+-label%3A%22Feature+-+Book%22+-label%3A%22Feature+-+Developer+Research%22+-label%3A%22Feature+-+HfLA+Website%22+-label%3A%22Feature+-+Interviews%22+-label%3A%22Feature+-+Onboarding%22+-label%3A%22Feature+-+survey%22+-label%3A%22Feature+-+Team+Infrastructure%22+-label%3A%22Feature+-+Video%22+-label%3A%22Feature+-+Wiki+Audit%22+-label%3A%22Feature+-+Wiki%22+-label%3A%22feature%3A+Guide+Creation%22+-label%3A%22feature%3A+missing%22+-label%3A%22Feature+User+Journey%22+-label%3A%22P+-+Feature+-+Figma+Component+Draft%22+-label%3A%22P+-+Feature+-+Figma+Foundation%22+-label%3A%22P+-+Feature+Draft+Guide%22+-label%3A%22P+-+Feature+FF+V1%22+)
   - [role](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+Design+Lead%22+-label%3A%22role%3A+Design%22+-label%3A%22Role%3A+Development%22+-label%3A%22Role%3A+Org%22+-label%3A%22Role%3A+PM%22+-label%3A%22role%3A+missing%22+-label%3A%22Role%3A+Research+Lead%22+-label%3A%22Role%3A+Research%22)
   - [size](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+1pts%22+-label%3A%22size%3A+2+pts%22+-label%3A%22size%3A+3+pts%22+-label%3A%22size%3A+5+pts%22+-label%3A%22size%3A+8+pts%22+-label%3A%22size%3A+13%2B+pts%22+-label%3A%22size%3A+missing%22)
      - [ ] Add any label missing (e.g., a new feature label go added to the project, but didn't yet get added here) and update link 
- [ ] if changes were made, recheck to make sure all links ended up 0 open
- [ ] Audit for issues with Missing labels (to determine if we are making progress)
   - [ ] Copy this audit report format to a comment below
```
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] feature, ending at
   - [ ] project, ending at 
   - [ ] role, ending at
   - [ ] size, ending at
   - [x] milestone, ending at (don't have yet, go ahead and skip)
```
   - [ ] perform audit, adding your numbers to your audit report comment
      - [feature](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)
      - [project](https://github.com/hackforla/design-systems/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
      - [role](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)
      - [size](https://github.com/hackforla/design-systems/issues?q=is%3Aopen+is%3Aissue+label%3A%22size%3A+missing%22)

### Epic
   - [epic]()

#### Icebox issue
- [ ] [Icebox Issues w no dependency](https://github.com/hackforla/design-systems/projects/1?card_filter_query=-label%3Adependency#column-15133574)

**Comment by allthatyazz** [comment]
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] feature, ending at 8
   - [ ] project, ending at 5
   - [ ] role, ending at 44
   - [ ] size, ending at 14
   - [x] milestone, ending at (don't have yet, go ahead and skip)

**Comment by allthatyazz** [comment]
This issue will be moved to the backlog because we are still in the process of cleaning up our project board and reducing the number of labels.
