### ISSUE TITLE
Design introduction page/section

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#382]
### Overview
We need an introduction page/section for Figma foundations so that users will have a proper landing page and direction on how to use the tutorials+ templates. 

### Action Items
 - [x] Work on the UI to maintain consistency between this page and the rest of the tutorials. 
 - [x] Include a How-To section in a few easy steps  
 - [x] Track your progress by your adding a comment here

### Resources/Instructions
 - The mood boards on the original Figma Foundations' draft can be helpful.

**Comment by sandraberjan** [comment]
I created an alternate draft of the introduction page in the Figma file under "Sandra's Copy".

**Comment by allthatyazz** [comment]
- During the week of 3/28-4/1, the introduction page expanded to an introduction section includung 1 main page for the intro and two subpages for the "how-to" and "additional resources".  
   - On 4/4, during the Stakeholder meeting, the name of this page was changed to " Start Here". Also, all three different pages merged into a single page. The rationale was to reduce the cognitive load for the users and make the navigation process smoother. The stakeholder also stressed the need for consistency between the pages. 
    
 @sandraberjan  you can add your comment here to document your progress. There is no right or wrong and you can never go wrong by being too detailed.

**Comment by sandraberjan** [comment]
I started working on a second version of the intro page to fix the information architecture by

- moving some of the copy from the intro frame to the two subpages
- deleting any text that is unnecessary

**Comment by sandraberjan** [comment]
04/06 Insights and Progress

1. I started documenting my process directly in the Figma file to

> be transparent with my thinking and decision making

> preserve anything that could be useful later

> show non-writers the "backend" of achieving the final concise and clear text

2. added goal this week: research how to do the above more effectively

**Comment by sandraberjan** [comment]
04/11 Completed the reorganized Version 2 copy for all three frames. Tagged Tammy in comments in the Figma file.
