### ISSUE TITLE
Give feedback on cover page usability test plan

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#386]
### Overview
The design team needs to provide input for the usability study so that the research team can incorporate the input into the usability study scripts or prompts. 
### Action Items

- [x] #377 
- [x] Create the FigJam
- [x] Provide Input
- [x] Inform the research team
- [x] update plan doc

### Resources/Instructions
The [Figjam](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1)

**Comment by sandraberjan** [comment]
Added my input 04/10

**Comment by kelenelee** [comment]
moderator script prompts have been pared down to reduce the amount of hints given to the user. 

Moderator is now required to send the task prompt to the participant via Zoom chat. If there are other methods of delivering the task that can be more easily seen while the participant is screen sharing, then the plan should be updated to reflect that.

Note-taking protocol was updated as well and in the future people will take notes via [this spreadsheet](https://docs.google.com/spreadsheets/d/18ColipRIA1ugKp9u6BYS7rCrf8-ybiskpb428aJqkys/).

Based on P3 results, we are considering that Figma newbies are not to be a participant profile and therefore should not be recruited for or designed for

**Comment by allthatyazz** [comment]
- On 5/24/2022 the revised test plan will be discussed at the research team's meeting. This note will be updated with the relevant info.

**Comment by sandraberjan** [comment]
05/25 I gave feedback on moderator script wording via comments in the google doc of the updated plan.

**Comment by kelenelee** [comment]
During today's research meeting, we were discussing the interview analysis strategies #431 and didn't have time to discuss the updated HFK research plan. @sandraberjan and @allthatyazz left some great comments in the doc. 

So far the updated methodology is good. The facilitating details still need to be more aligned with the content of the GitHub issue templates.

I'm consulting my mentor from Delta CX on possible improvements to the plan, including the structure of the tests - whether we should keep testing each component/page, and if so, should we bother including the Kit's intro page in the prototype. Once I get that feedback and incorporate it into the doc, then we can probably be done with this task and close the issue.

**Comment by kelenelee** [comment]
Update, Deb gave some interesting feedback 
- our team's work is teaching people how to use a design system, not actually making one ourselves 
- we may need to study end users of HfLA products to better understand how they perceive product branding
- we should lean more on existing practices of design systems to inform how we teach others
- therefore the current state of the HFK contextual inq may need more radical revisions later. for now the smaller edits to the cover page plan is done.
