### ISSUE TITLE
Initializing React App with Button Component in TypeScript

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#39]
### Overview
Current Hack for LA React projects use UI component libraries, such as Material-UI and Semantic-UI, to build their in-house components.

Based on [Stage 1 Component Research & Finding](https://github.com/hackforla/design-systems/wiki/Research-&-Finding:--Hack-for-LA-React-Project-Components), we have no need to create a full-fledged UI component library. We plan to document our Design System with a handful of simple components.

Our next steps in making the design system MVP is to finalize tech stack and explore various documentation tools with one in-house button component.

### Action Items
- [x] Initialize React App in TypeScript
- [x] Initialize Button Component

### Resources/Instructions
[Design Systems’ Figma for Button Component](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=0%3A1)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by kelenelee** [comment]
- [ ] #40 
- [ ] #97 
- [ ] #121
