### ISSUE TITLE
 User interview Designer #11 - note taker 

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#390]
### Overview
This ticket will prepare the note taker for a successful user interview. All the best practices has been thoroughly explained in the [interview guide](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit). It's crucial to read and study this document before the interview in order to increase the understanding of the interview process and to confirm the recording procedures.

### Action Items
**Make sure you read:**
- [x] The best practices before the interview.
- [x] Things to do before the interview
- [x] Things to do after the interview

**Make sure that you:** 
- [x] Know how the recording procedures work
- [x] Confirm with the UXR leads that one of them will be available for recording purposes

### Resources/Instructions
[Interview guide](https://docs.google.com/document/d/1VYCMj7JtDFvBtrs7hQKGdC0Jelkq07HYtwtlNWb-QSw/edit)
[Participants Interview](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit)
[Otter recording tutorial](https://docs.google.com/document/d/1TLG1mmzImDCRcyLpktrTSHUb5nJB7xP4AsMNeE0PCG4/edit)

**Comment by kelenelee** [comment]
interview w p11 completed [today, apr 8](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit#gid=0) with dongchen interviewing and me [notetaking in figma](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam?node-id=499%3A5913). figma notes [copied to google doc](https://drive.google.com/drive/u/1/folders/1gxits9IxKgYvrKrLlM0i9Hk29_63X-GH)

awaiting close

**Comment by allthatyazz** [comment]
Great job!
