### ISSUE TITLE
Usability test the cover page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/design-systems#393]
Dependency:

- [ ] #386 
- [ ] #396

**Comment by cunninghamej** [comment]
First usability test conducted on 4/13/22.

**Comment by kelenelee** [comment]
draft of facilitator / moderator issue template 

### Facilitating Action Items

- [ ] Rehearse script out loud
- [ ] Meet with note-taker 10 minutes before
- [ ] Send message to participant to double check availability
- [ ] Wait 15 minutes if participant is late
- [ ] Record the session
- [ ] Remain neutral – you are there to listen and watch. If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” Do not jump in and help participants immediately and do not lead the participant. If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Watch Slack for backchanneled questions from note-takers
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the correct FF page that was tested
- [ ] 

draft of note-taker issue template

Action Items

- [ ] Review script questions
- [ ] Pull up note-taking template
- [ ] Use Slack to backchannel questions you want the facilitator to ask
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant.
