### ISSUE TITLE
Participant 1 analysis

### ISSUE THREAD

**Issue by cunninghamej** [hackforla/design-systems#394]
**Assignees, make a comment with the template below.** Once you finish your analysis, come back to the checklist above and check off your name.
- [x] @hdchangie 
- [ ] @cunninghamej 
- [x] @tamalatrinh
- [x] @winoue90 
- [x] @kelenelee 
- [x] @sandraberjan 
- [ ] @allthatyazz 

```
# Analysis
After completing these subtasks, scroll up to the top to check off the main task.
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the [recording in Drive](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T) and observe participant behavior, and [take notes here](https://docs.google.com/spreadsheets/d/1kPUgCmxFp2X3cm33GvCbd41JzrfOYQye). Ideally the notes should be detailed enough to take you at least 1.5 times the length of the recording (i.e., a 30-min video will take at least 45 min to take notes on)
- [ ] Add [your insights in this Figma](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam)
- [ ] Below, summarize your recommendations for the design, future tests, the facilitating, etc. future tests, the facilitating, etc. 
```

**Comment by allthatyazz** [comment]
I added a template for note-taking/analysis.  Please use the spreadsheet to add your notes and observations.

**Comment by cunninghamej** [comment]
Thanks for the additions @allthatyazz and @kelenelee

**Comment by hdchangie** [comment]
I have uploaded the notes of participant #1 usability test to the Google Drive using Yas's template: https://docs.google.com/spreadsheets/d/1QhOP0h9a-BGuSCMwVlg85gJSb1ukxRZD/edit#gid=621061198

**Comment by kelenelee** [comment]
draft of analysis issue template

### Analyzing Action Items

- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Comment on this analysis issue who has been assigned to analyze the video
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as critical (If we do not fix this, users will not be able to complete the scenario), serious (many users will be frustrated if we do not fix this; they may give up) or minor (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by sandraberjan** [comment]
I completed the task according to @cunninghamej instructions. 04/19

**Comment by allthatyazz** [comment]
Wataru and Tammy completed the task as well.

**Comment by kelenelee** [comment]
# Analysis
After completing these subtasks, scroll up to the top to check off the main task.
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the [recording in Drive](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T) and observe participant behavior, and [take notes here](https://docs.google.com/spreadsheets/d/1kPUgCmxFp2X3cm33GvCbd41JzrfOYQye). Note-taking should take at least 1.5 times the length of the recording (i.e., a 30-min video will take at least 45 min to take notes on)
- [ ] Add [your insights in this Figma](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam)
- [ ] Below, summarize your recommendations for the design, future tests, the facilitating, etc.

**Comment by allthatyazz** [comment]
- The notes, and recommendations after P1, P2, P3 tests can be all found within these two documents. Please refer to this comment for the context. https://github.com/hackforla/design-systems/issues/394#issuecomment-1116691190
    -  The [recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) 
    -  The [notes spreadsheet](https://docs.google.com/spreadsheets/d/18ColipRIA1ugKp9u6BYS7rCrf8-ybiskpb428aJqkys/edit?usp=sharing)
