### ISSUE TITLE
Kanban board - cleanup & protocol recommendations

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#395]
5/4 update: this issue got way too unwieldy so some sections have been moved to separate issues
- #396  
- #412
- #408 
- #422 
  - #406

@allthatyazz originally tasked me with reorganizing our team's [Google Drive](https://drive.google.com/drive/u/0/folders/0ACLGQ8FFW2MCUk9PVA) and [Project Management](https://github.com/hackforla/design-systems/projects/1) board. Leave your feedback on the changes in the [discussion](https://github.com/hackforla/design-systems/discussions/403)

### Columns
- [x] Deleted unnecessary columns to remove horizontal scrolling
  - [x] Deleted "New Issue Approval" column. Newly created issues awaiting review now live in `Add cards (# new)`
  - [x] Deleted "Ice Box" column
  - [x] Deleted "Questions / Review" column
    - [x] Replaced with new orange label `?`
- [x] Cleaned up Start Here column
  - [x] Removed onboarding-related content, because it is unlikely and ill-advised that newcomers will be beginning their Github journey via the main Kanban board
  - [x] Add link to new issue templates 
  - [x] Apply # heading formatting to board cards
- [x] Added emojis to column names and wrote column names in all caps, to separate visual hierarchy from bolded issue or card titles
### Issues
- [x] Closed depreciated, redundant, or junk issues
- [x] Moved Ice Box and New Issue Approval issues to Backlog
- [x] Moved documentation-related issues to a new project board
  - [x] Created three new milestones for documentation tasks related to the project revival in August, the team lineup changing in January, and the PM transition in February
- [x] Moved onboarding-related issues to a new project board. (Not sure if this is a permanent solution, as Github is a lot to take in for newcomers on top of DS domain knowledge.)
- [x] Removed child issues from Kanban board, and kept "parent" issues. Edited parents to include issue numbers of copied issue templates, to create more contextual stories. Kanban done column went down from ~270 to ~30. Child issue assignees have been added to the parents. 
  - https://github.com/hackforla/design-systems/issues/164
  - https://github.com/hackforla/design-systems/issues/326
  - https://github.com/hackforla/design-systems/issues/341
  - https://github.com/hackforla/design-systems/issues/280
  - https://github.com/hackforla/design-systems/issues/44
  - https://github.com/hackforla/design-systems/issues/58
  - https://github.com/hackforla/design-systems/issues/209
  - https://github.com/hackforla/design-systems/issues/154
  - https://github.com/hackforla/design-systems/issues/109

**Comment by kelenelee** [comment]
ideas 
- move onboarding and offboarding tasks to a different project board 
- prioritize clearing of new issue approval and questions/review columns
- can issues worked on by multiple people be combined into one issue?
- is there a way to block issues without labels from being submitted?
- cross link Github issues, Google Drive files, and Figma links at all times

**Comment by kelenelee** [comment]
small tasks
- [ ] Cleaned up [team roster spreadsheet](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI/edit#gid=516267752) and deleted duplicate file of waitlist

**Comment by allthatyazz** [comment]
> Moving things outside of the PM Board
> 
> * move onboarding and offboarding tasks to a different project board
 
This would be a logical choice since onboarding/offboarding does not occur as frequently.  Also if the purpose of Onboarding issues (first tickets for new joiners) is to train new joiners and make them more comfortable with the GitHub environment, we can expose the new joiners to a less crowded project board. 

> * move project info board to wiki page
> 
I looked at the other HfLA projects. It seems most projects use the project info column for the main Github board.

**Comment by allthatyazz** [comment]
@kelenelee  For the GitHub columns, we are required to follow the order you find here https://github.com/hackforla/.github/projects/2

**Comment by kelenelee** [comment]
@allthatyazz Hi, thanks for commenting. Feels different from talking on Slack, but this is fun to try out!

> This would be a logical choice since onboarding/offboarding does not occur as frequently. Also if the purpose of Onboarding issues (first tickets for new joiners) is to train new joiners and make them more comfortable with the GitHub environment, we can expose the new joiners to a less crowded project board.

My thoughts exactly!! I can help with making it.

> For the GitHub columns, we are required to follow the order you find here https://github.com/hackforla/.github/projects/2

Thank you for catching that and I'm sorry I moved things around 😅 But I think I disagree with the template. I have a hunch that this column order is contributing a bit to everyone's confusion.

**Comment by allthatyazz** [comment]
Let’s start making a new board for  onboarding. The columns can be as simple as the templates, In progress, questions and Done. What do you think? 
 We have some issues related to onboarding/offboarding in the weekly operations. We can maybe move those to the new board as well? 

> > For the GitHub columns, we are required to follow the order you find here https://github.com/hackforla/.github/projects/2
> 
> 
> Volunteers will be looking at first few columns the most. If I were to pick the columns that I reference the most, they would be Prioritized Backlog and In Progress, not Start Here and Ice Box.
> 
100% agree about the Ice Box. It was the most confusing for me when I joined the project.

**Comment by kelenelee** [comment]
@allthatyazz I created [the onboarding board](https://github.com/hackforla/design-systems/projects/4). I also rewrote [the wiki article](https://github.com/hackforla/design-systems/wiki/Your-first-issues). In the future I hope DS newcomers are sent there without hiccups.

I agree that the weekly operations column could be moved elsewhere. I don't think they should be moved to the new board. I will keep thinking... 

For the main board, it would be amazing if Backlog and In progress could be moved further left.

**Comment by kelenelee** [comment]
Observation: Github columns have optional automation, for example: 
- issue opened = move to "Backlog" 
- issue closed = move to "Done"
If there is no automation in place for Backlog, new issues created "await triage" next to the Filter cards search box. You can see it in action at the Onboarding board. 

Arguably we could get rid of the New Issue Approval column as well.

**Comment by kelenelee** [comment]
As a test, I deleted some board columns.

**Comment by kelenelee** [comment]
I also wonder if epics can be separate boards

**Comment by allthatyazz** [comment]
> I created [the onboarding board](https://github.com/hackforla/design-systems/projects/4). I also rewrote [the wiki article](https://github.com/hackforla/design-systems/wiki/Your-first-issues). In the future, I hope DS newcomers are sent there without hiccups.
> 
> I have moved the onboarding issues from Weekly Operations to the Onboarding board.
 
I saw the changes. The onboarding board looks great along with the Wiki article. I found all your Wiki revisions very useful. We can expect the new joiners to have a smoother onboarding experience from now on.  The next step really would be to improve the onboarding tickets themselves. Our UX writer, @sandraberjan can be a great help to improve the copy and IA further. I encourage you two to start working together.  

> To be honest, having an issue house a template with the actual work in the comments has never made sense to me. I think templates can live in the wiki. Each time a task recurs, it should be its own issue. Then we won't need a "Weekly Operations" column, either.

Your observation is true to some extent. In many project management instances, the comments on an issue are not any less than the main body of the issue (the very first comment). The comments are meant to show the progress in a timeline format and naturally, everybody knows that each comment is an update about "the actual work."  For some recurring tasks, if we create a new issue every time, we can hardly comprehend the process and track the progress. 

If our goal is to simplify the project board, we can move the templates to a separate project board.  Currently, we have a project board called [Guides and Templates for Design Systems](https://github.com/hackforla/design-systems/projects/3). We can utilize that board to include all our templates. We can rename the columns to whatever the templates are going to be used for (e.g. Usability study templates or Interview Templates).

> We could even move agendas to Discussions.

It is not an ideal solution either. It is not common among HfLA projects to include the meeting agendas on any other board other than project management. If a PM from another project wants to add an item to our agenda ( we have instances in the past), they have to be able to find the agenda from a consistent board.

**Comment by allthatyazz** [comment]
Looking at other HfLA's projects, I found the following teams' first columns interesting: 

 - [website team](https://github.com/hackforla/website/projects/7) 
 - [Home Unite US](https://github.com/hackforla/HomeUniteUs/projects/3)

**Comment by kelenelee** [comment]
> Looking at other HfLA's projects, I found the following teams' first columns interesting
Looks like the first column is largely dependent on what filters the members frequently use

**Comment by allthatyazz** [comment]
@kelenelee  Very nice job editing the first comment of this issue. Few things: 
 - Moving the meeting agendas outside of the main project board is out of the question. Agendas are not any less than other issues the team is working on. They are the only issues reflecting the time and energy that team members spend during the weekly meetings. If the purpose of an issue is to show the work is getting done by the volunteers, agenda issues are exactly fulfilling that purpose. 
- I get why you feel Agendas do not belong to the project board because they are naturally different than other issues/ or tasks.
- The previous PM used to keep Agendas in the "in progress" column. One of my first moves as the PM was to create the weekly operations column to separate the agendas from the other in-progress tasks/issues. Now we decided to reduce the number of columns, the agendas can live under the first column. 
-  The naming of each Agenda should start with the name of the team. I renamed all the agendas again to add DS in front of the name. If you would like to know the reasoning please view [this page](https://github.com/orgs/hackforla/projects/5) to know why.

**Comment by kelenelee** [comment]
@allthatyazz I just took a look at the agenda project board and OHHH I get it now!!! Thanks so much for clarifying and helping me understand

**Comment by allthatyazz** [comment]
I just noticed that yesterday. After my meeting with Bonnie, I did more digging in HfLA's repository to gather more information.  I suspect that there is more stuff at play that we are not aware of (just yet). Also, you can read the notes from Yesterday's PM meeting.

**Comment by kelenelee** [comment]
Just read through those meeting notes. Thank you for writing them – they were also very helpful.

**Comment by allthatyazz** [comment]
@navarroliuanthony @hdchangie Hi Please feel free to provide your feedback on the research templates.

**Comment by kelenelee** [comment]
As of now, the Kanban transformation is complete. User feedback has been good so far but no observations were done. If an observational study can be done, a new issue will be created.

**Comment by kelenelee** [comment]
sooo maybe multiple projects is too out-of-sight, out-of-mind?... will need the input of others
