### ISSUE TITLE
Issue Templates - Protocol and FF usability test tasks

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#396]
DS will be doing at least 5 usability tests of the Figma Foundation template prototype. I have been tasked with creating Github issue templates so that researchers may duplicate them to make their own issues. #376 

A usability test will be conducted on each [FF page](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k), and therefore each test will require the above individual issues

- Cover page
- Start page
- File menu
- DS page
- Plugin library
- Individual component page

I don't have any experience conducting usability tests. But I know where to find good guides on best UXR practices, and so I'll start from there.

I also believe that the data we have collected via the interviews do not give us enough granular detail of user tasks to justify conducting usability studies. I am concerned that, even with my best template writing, that these usability tests may not result in reliable data and are not in the best interest of the DS end users. 

This task has turned into a greater evaluation of how templates should be handled in the future. 

# Templates as issues vs issue templates
- [x] Delete unused new issue templates. This was before I knew that deleting `.md` from the file name would hide it from the new issue templates page. Regardless, these templates exist in other HfLA repos and there will be no problems with re-adding them if it becomes necessary to do so. In the future making a lot of issue templates should not be a problem as long as the issue template folder is updated to reflect the team's needs at the given time. Also, the templates page orders templates in alphabetical order of the file name. This can be used to customize the order in which templates are displayed.
- [x] Create new issue templates that our team can use, removing issues that are "templates". Templates and copies as individual issues create a lot of repetition and spam and makes it harder for future people to sift through the board. Templates will now be copied in the comments of 1 issue. The main body of the issue will contain tasks with people's Github handles. This way, the wheel of tasks completed will accurately reflect issue progress, instead of the subtasks remaining unchecked.
  - [x] Automate labels in issue templates (projects and milestones cannot be automated, unfortunately)
  - [x] Add directions to add certain labels and milestones within the issue
  - [x] Write tips on how to write a good issue in the standard issue template

### Templates for the usability studies
- [x] Research usability best practices
  - [x] Find resources to link in the templates, to help HfLA researchers quickly learn how to conduct the study
- [x] [Experiment with the best content for templates to contain, while minimizing markdown writing and project board clutter
](https://www.figma.com/file/Yv8hGuiraQVgrlNz1BF0gN/DS-labels%2C-milestones%2C-project-board-organization?node-id=0%3A1)
- [x] Create templates for revising the plan, and conducting, taking notes, and analyzing a session
- [x] Create an issue for recruiting participants

**Comment by kelenelee** [comment]
I don't have any experience conducting usability tests. But I know where to find good guides on best UXR practices, and so I'll start from there.

I also believe that the data we have collected via the interviews do not give us enough granular detail of user tasks to justify conducting usability studies. I am concerned that, even with my best template writing, that these usability tests may not result in reliable data and are not in the best interest of the DS end users.

**Comment by kelenelee** [comment]
### Resources on how to conduct a usability test
- https://www.usability.gov/how-to-and-tools/methods/running-usability-tests.html

**Comment by kelenelee** [comment]
## Action Items

- [ ] Select 5 people that match the end user profile outlined in the plan
- [ ] Add them to [the recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0)
- [ ] Contact them individually on Slack using the message template
- [ ] Update [the recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when a usability session is scheduled

### Message template

>

**Comment by kelenelee** [comment]
## 1. Required readings

- [ ] [About usability testing](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)
- [ ] [Types of usability testing methods](https://www.usability.gov/how-to-and-tools/methods/running-usability-tests.html)
- [ ] [Writing a plan and types of metrics](https://www.usability.gov/how-to-and-tools/methods/planning-usability-testing.html)
- [ ] [Myopic metrics](https://medium.com/delta-cx/your-cx-and-ux-metrics-are-myopic-9470d5956969)

## 2. Writing the sections of the plan

### Constraints
- [ ] **Scope** (what is being tested)
- [ ] **Purpose** (why is this being tested, concerns, questions, goals for the test)
- [ ] **Scenarios** (what task the participant will be asked to complete)
- [ ] **Method** (think-aloud or probing)
- [ ] **Metrics** for success
- [ ] **Discussion guide** (questions asked before and after task)

### Logistics 
- [ ] **Sessions** (length, buffer between sessions)
- [ ] **Equipment** (software) used to conduct and record test
- [ ] **Participants** (number, type, recruiting methods)
- [ ] **Researcher roles** (who does what)



## 3. Review

- [ ] Read through and discuss the plan with fellow researchers
- [ ] Pick one facilitator and at least one note-taker
- [ ] Paste the finalized research plan in Github comments and link the Google Doc draft
- [ ] Run a pilot at least a few days before a real session, and make notes how the pilot went in Github issues comments

**Comment by kelenelee** [comment]
Facilitating

```
- [ ] Meet with note-taker 10 minutes before
- [ ] Send message to participant to double check availability
- [ ] Wait 15 minutes if participant is late
- [ ] Record the session
- [ ] Remain neutral – you are there to listen and watch. If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” Do not jump in and help participants immediately and do not lead the participant. If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Watch Slack for backchanneled questions from note-takers
```

**Comment by kelenelee** [comment]
Note-taking

```
- [ ] Review script questions
- [ ] Pull up note-taking template
- [ ] Use Slack to backchannel questions you want the facilitator to ask
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant.
```

**Comment by kelenelee** [comment]
Analyzing

```
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as critical (If we do not fix this, users will not be able to complete the scenario), serious (many users will be frustrated if we do not fix this; they may give up) or minor (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test
```

**Comment by kelenelee** [comment]
technically this task is complete. however this process has opened up a whole new project to rethink how we use github generally. See issue #395

**Comment by kelenelee** [comment]
I am revising the templates to better reflect the iterative nature of the FF tests

Kelene
> piggybacking on this to ask if Yas or Wataru could write down the plan for round 1, 1.5, etc of testing, mentioned in last night’s all-hands meeting. I can’t find any documentation on it

Wataru
> The whole round 1 and 1.5 isn't necessarily a official thing that was documented. It was just the way I described it to confirm if my understanding of the bigger picture was what Yas had in mind.

Yas
> Yes as Wataru mentioned we never discussed the naming of the rounds. But from the very beginning, the iterative nature has been baked into the process when we shifted the direction towards the FF ( we discussed it numerous times during meetings.)  If you are looking for a specific written document, take a look at UX/UI discovery Figjam. There should be a series of slides that I put there very early on when I presented my vision for the FF to the team.

**Comment by kelenelee** [comment]
tasks have been completed. you can see the issue templates here by clicking the green button "New issue" which appear on individual issues and on the "issues" page of the secondary nav

**Comment by allthatyazz** [comment]
Amazing progress!
