### ISSUE TITLE
Style Button

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#40]
### Overview
Current Button Component from Design Systems projects need styling before exploring the documentation tool

### Action Items
- [ ] Style Button with styled component
- [ ] Research on best practice for variants for styled-components and Typescript
   - [ ] Should we use switch statement for two types of button variants
- [ ] Create variant dictionary for button colors
- [ ] Create Themes, ie. Colors from theme.ts

### Resources/Instructions
[Design Systems’ Figma for Button Component](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=0%3A1)
[Styled Component Doc](https://styled-components.com/)
[Theming and Theme Switching with React and styled-components](https://css-tricks.com/theming-and-theme-switching-with-react-and-styled-components/)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by qiqicodes** [comment]
Styled button merged to main branch
