### ISSUE TITLE
Draft research report on PMs 

### ISSUE THREAD

**Issue by hdchangie** [hackforla/design-systems#402]
### Dependency
- [x] #431 
### Overview
After conducting interviews with 7 PMs and extracting insights, the goal of this task is to collate the findings from the 7 interview analyses and synthesize them into a research report with key findings and recommendations that can be shared among team members and stakeholders. 

### Action Items
- [x] go over the interview[ Figjam](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam?node-id=0%3A1) and synthesize interview insights on PMs
- [x] find themes and insights that are shared across analyses insights
- [x] summarize, outline, and synthesize the insights into high-level (key) findings
- [ ] list out recommendations based on key findings
- [ ] further qualitative research on sporadic and idiosyncratic findings that cannot be subsumed under key findings
- [ ] generate deliverable: put key findings, minor findings, and recommendations into the template. 

### Resources/Instructions
[Synthesis of PMs interview](https://docs.google.com/document/d/1zEK7z1vV3NT0FKMA7zsvGpIHfJ75XNElI0kcRs237AA/edit?usp=sharing) 
[Figjam](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/UXR-Interview-figjam?node-id=0%3A1) file

**Comment by allthatyazz** [comment]
- The final report produced by the research team members is listed below. 
  - 08/30/2022 A  [slide deck](https://docs.google.com/presentation/d/1P4aEbqbZrDyddhFJruvZ1h0zdwzl_r0y/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by Kelene.
 -  On 03/17/2023, I personally put together [a version of the slide deck ](https://docs.google.com/presentation/d/1kJzdGj_03iSns8A01c5BACq6azePJYk2/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true)based on the previous slide decks by other team members. This version has borrowed from Designer reports that Dongchen put together.
