### ISSUE TITLE
Create research report and slide deck template 

### ISSUE THREAD

**Issue by hdchangie** [hackforla/design-systems#404]
### Overview
This template will be useful for researchers to have a basic outline of reporting important findings and recommendations at any stage of the research (explorative, evaluative). The template includes two formats, one of which is a written report and another is a slide deck. 

### Action Items

- [x] Synthesize important components of a research report
- [x] Put down the components in a single file by following a logical manner
- [x] Incorporate the team's design system in the written report format and slide deck format, including but not limited to, colors, fonts, typography, etc. 
- [x] share the template to Google Drive. 
- [x] notify PMs and other researchers 

### Resources/Instructions
[Google Drive ](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing)

**Comment by hdchangie** [comment]
The research report template (written report format) can be found here: https://docs.google.com/document/d/1ZiY6ofV7VhMYZ-OsFFrZ6M-sFrvemVIP/edit?rtpof=true

**Comment by kelenelee** [comment]
@hdchangie i found this? https://github.com/hackforla/design-systems/issues/234

**Comment by hdchangie** [comment]
@kelenelee yes, I also found this one, and its color scheme matches our team's DS which is great. I am also trying to use it as a foundation to make it more geared toward a research slide deck.
