### ISSUE TITLE
Improved privacy of interview recordings

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#405]
Need help brainstorming better places to store interview recordings. Right now their location in Drive is not ideal for privacy / confidentiality of the interview content
- [ ] Move recording files and transcripts to a location where only current members of research team can access them

**Comment by allthatyazz** [comment]
I will add this item to the agenda for the PM and Stakeholder meeting.

**Comment by allthatyazz** [comment]
This issue is discussed during PM/Stakeholder interview on 4/20/2022. For details please read the meeting notes here https://github.com/hackforla/design-systems/issues/89#issuecomment-1104402533

**Comment by kelenelee** [comment]
thank you so much @allthatyazz I am closing this
