### ISSUE TITLE
Start page participant 1

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#407]
# Recording
- [ ] Decide who is going to record the call with Zoom Pro. If there is no Zoom Pro available, use Otter as a backup to transcribe the audio
- [ ] Comment beelow the [DS Google Drive](https://drive.google.com/drive/folders/0ACLGQ8FFW2MCUk9PVA) link of the recording files
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg)

# Facilitating
### Prepare
- [ ] Review the plan #406 and [usability test session tips](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)
  - [ ] Read the script out loud. 
  - [ ] Run a pilot with someone on the team pretending to be the participant.

#### Day of
- [ ] Send a reminder to the participant via Slack direct message.
- [ ] Open Slack to your DMs with the note-taker, and keep it in the background. This is to receive any questions the note-taker might want you to ask (use your best judgment according to usability testing best practices as to whether the question is worth asking).
- [ ] Start the meeting room 10 minutes before. Wait 15 minutes if participant is late.

### During
- [ ] Turn video off when they start sharing their screen.
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.

# Note-taking
### Prep
- [ ] Review the plan #406 and [usability test session tips](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)

#### Day of
- [ ] Open Slack to your DMs with the facilitator, and keep it in the background. This is in case you think of questions you want the facilitator to ask the participant, or if anything happens during the session
- [ ] Have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU) ready
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late

### During

- [ ] Keep your video off
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant.

# Analysis

- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior, and make your notes here
- [ ] List problems and classify them as critical (If we do not fix this, users will not be able to complete the scenario), serious (many users will be frustrated if we do not fix this; they may give up) or minor (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Provide feedback on session protocol to next facilitator
- [ ] Revisit previous participant analyses as more people participate in the usability test

**Comment by kelenelee** [comment]
# Participant 1
Lead by @_____
Note-takers @_____
Analysis by @_____ @_____ @_____
Video recording link: _________
Analysis file: _________

# Participant 2
Lead by @_____
Note-takers @_____
Analysis by @_____ @_____ @_____
Video recording link: _________
Analysis file: _________

# Participant 3
Lead by @_____
Note-takers @_____
Analysis by @_____ @_____ @_____
Video recording link: _________
Analysis file: _________

# Participant 4
Lead by @_____
Note-takers @_____
Analysis by @_____ @_____ @_____
Video recording link: _________
Analysis file: _________

# Participant 5
Lead by @_____
Note-takers @_____
Analysis by @_____ @_____ @_____
Video recording link: _________
Analysis file: _________

**Comment by kelenelee** [comment]
# Participant 1 

Session lead by @______
Note-takers @______
Analysis by @______ @______ @______
Video recording link: ______
Analysis file: ______

### 2. Before the session

- [ ] Send message to participant to double check availability.
- [ ] Note-takers, have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU/edit#gid=676557520) ready.
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late.
- [ ] Have Slack ready in the background. Note-takers, if you think of questions to ask the participant, send them in Slack to the facilitator.

### 3. During the session
- [ ] Record the call
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. Facilitators: If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the folder for the FF page that was tested

### 4. Analysis
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as **critical** (If we do not fix this, users will not be able to complete the scenario), **serious** (many users will be frustrated if we do not fix this; they may give up) or **minor** (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by kelenelee** [comment]
# Participant 1 

Session lead by @______
Note-takers @______
Analysis by @______ @______ @______
Video recording link: ______
Analysis file: ______

### 2. Before the session

- [ ] Send message to participant to double check availability.
- [ ] Note-takers, have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU/edit#gid=676557520) ready.
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late.
- [ ] Have Slack ready in the background. Note-takers, if you think of questions to ask the participant, send them in Slack to the facilitator.

### 3. During the session
- [ ] Record the call
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. Facilitators: If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the folder for the FF page that was tested

### 4. Analysis
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as **critical** (If we do not fix this, users will not be able to complete the scenario), **serious** (many users will be frustrated if we do not fix this; they may give up) or **minor** (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by kelenelee** [comment]
# Participant 1 

Session lead by @______
Note-takers @______
Analysis by @______ @______ @______
Video recording link: ______
Analysis file: ______

### 2. Before the session

- [ ] Send message to participant to double check availability.
- [ ] Note-takers, have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU/edit#gid=676557520) ready.
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late.
- [ ] Have Slack ready in the background. Note-takers, if you think of questions to ask the participant, send them in Slack to the facilitator.

### 3. During the session
- [ ] Record the call
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. Facilitators: If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the folder for the FF page that was tested

### 4. Analysis
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as **critical** (If we do not fix this, users will not be able to complete the scenario), **serious** (many users will be frustrated if we do not fix this; they may give up) or **minor** (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by kelenelee** [comment]
# Participant 1 

Session lead by @______
Note-takers @______
Analysis by @______ @______ @______
Video recording link: ______
Analysis file: ______

### 2. Before the session

- [ ] Send message to participant to double check availability.
- [ ] Note-takers, have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU/edit#gid=676557520) ready.
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late.
- [ ] Have Slack ready in the background. Note-takers, if you think of questions to ask the participant, send them in Slack to the facilitator.

### 3. During the session
- [ ] Record the call
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. Facilitators: If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the folder for the FF page that was tested

### 4. Analysis
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as **critical** (If we do not fix this, users will not be able to complete the scenario), **serious** (many users will be frustrated if we do not fix this; they may give up) or **minor** (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by kelenelee** [comment]
this was a test of the FF usability templates, closing now

**Comment by Leah0996** [comment]
@allthatyazz
