### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by JohnHaoHuang** [hackforla/design-systems#410]
# Logistics 
- [x] Complete [Hack for LA onboarding](https://www.hackforla.org/getting-started).
- [x] Set aside at least 6 hours of time a week to attend our [weekly meetings](https://github.com/hackforla/design-systems/wiki/How-to-join-the-HfLA-DS-team) and complete DS work.
- [x] On the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q), introduce yourself and request access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, and [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663). @ the PM and your team lead in your message.
  - [x] Once you have access, add yourself to [our roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI).
- [x] Read about [how Github works](https://github.com/hackforla/design-systems/wiki/Using-GitHub).
- [x] Look at the settings to the right of your issue 
  - [x] Add yourself as **assignee** 
  - [x] Choose the **label** `role: _` and then your role
  - [x] Choose the **project** `Learn about design systems`.
- [x] Click the `⭐ Star` icon at the top right of the page. It should turn into `⭐ Starred`.

# About design systems
- [x] Read chapter 1 of _[Design Systems](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf)_ by Alla Kholmatova.
  - [x] As you read, take notes, and paste your notes in the [discussion thread](https://github.com/hackforla/design-systems/discussions/198).
- [x] Read the [insight report from the stakeholder interview](https://drive.google.com/file/d/1QITYZvn2oFB4y9eakQjhQURrk-QS72Oj)

# Role-specific tasks
Complete the tasks for your role only (you may delete the other tasks that don't apply).
- [x] Once you're completely done, comment on this issue and @ the PM and your team lead.

### Role: Design
- [x] Click the green button `Submit new issue` on [this page](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME). This issue will generate under HfLA's UX/UI community of practice and is meant to track the skills you learn during your time at HfLA.
- [x] Read [HfLA’s Design System Guide for Designers](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit).
- [x] Learn about [double diamond](https://medium.com/design-council/the-double-diamond-15-years-on-8c7bc594610e).
- [x] Review [this Figma file](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1) to further understand Stage 2A of the project.
- [x] Watch [Figma's tutorials](https://www.youtube.com/watch?v=dXQ7IHkTiMM&ab_channel=Figma) on using Figma.

**Comment by kelenelee** [comment]
Good to meet you today @JohnHaoHuang I've edited your issue to be more concise. If you have any questions, please @ me here or message us in Slack.

**Comment by JohnHaoHuang** [comment]
@kelenelee Thanks for the update!
