### ISSUE TITLE
Conducting  Cover page usability test - Participant 3

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#413]
# Overview

Based on the analysis of P1 and P2, @kelenelee and @hdchangie made recommendations for the design of the Start Here and Cover Page pages of the HfLA Figma Kit. 

@sandraberjan @allthatyazz @kelenelee met the day before the P3 session to combine the recommendations and designers' work in progress into the Figma file that P3 saw. Other designers were unavailable to attend this collab session where many changes were made. In the future, we hope to check that the design team is better informed and onboard with what's being tested.

### Changes made
- name change from Figma Foundations to HfLA Figma Kit
- each item in checklist of Cover Page reqs had a screenshot of Figma as a how-to
- Start Here copy sections were merged and shortened

### [P3 recording file](https://drive.google.com/file/d/1KWdUf9XsC2_ssP1cUzm7UjC06wjFZFeU/view?usp=sharing)

# Facilitating

### Prep
- [x] Review the plan and [usability test session tips](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)
  - [ ] Read the script out loud. 
  - [ ] Run a pilot with someone on the team pretending to be the participant.
- [x] Decide who is going to record the call with Zoom Pro. If there is no Zoom Pro available, use Otter as a backup to transcribe the audio
- [x] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1KEf3kw9SRUqYAVtcDTTiWmg5TcMyeWb5MLU4oHETwVk/edit#gid=488330268)

#### Day of
- [x] Send a reminder to the participant via Slack direct message.
- [x] Open Slack to your DMs with the note-taker, and keep it in the background. This is to receive any questions the note-taker might want you to ask (use your best judgment according to usability testing best practices as to whether the question is worth asking).
- [x] Start the meeting room 10 minutes before. Wait 15 minutes if participant is late.

### During
- [x] Turn video off when they start sharing their screen.
- [x] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.

# Note-taking

### Prep
- [x] Review the plan and [usability test session tips](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)

#### Day of
- [ ] Open Slack to your DMs with the facilitator, and keep it in the background. This is in case you think of questions you want the facilitator to ask the participant, or if anything happens during the session
- [ ] Have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU) ready
- [x] Be present in the meeting room 10 minutes before. Wait 15 minutes if the participant is late

### During
- [x] Keep your video off
- [x] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant.

**Comment by kelenelee** [comment]
this is a test of a template

**Comment by kelenelee** [comment]
## Participant `#`

Facilitator: @_________
Note-taker: @_________
Video recording link: https://docs.google.com/..........

### Before the session 

- [ ] #406 
- [ ] #415 
- [ ] Read about [what usability testing is](https://www.usability.gov/how-to-and-tools/methods/usability-testing.html)
- [ ] On the day of the session, send a reminder to the participant via Slack direct message.
- [ ] Note-takers, have your [note-taking template](https://docs.google.com/spreadsheets/d/1MGU7DhhZmj7pkX9RIv5e8JUfnu78EWPU/edit#gid=676557520) ready.
- [ ] Be present in the meeting room 10 minutes before. Wait 15 minutes if participant is late.
- [ ] Have Slack ready in the background. Note-takers, if you think of questions to ask the participant, send them in Slack to the facilitator.

### During the session
- [ ] Record the call
- [ ] Remain neutral – you are there to listen and watch. Do not jump in and help participants immediately and do not lead the participant. Facilitators: If the participant asks a question, reply with “What do you think?” or “I am interested in what you would do.” If the participant gives up and asks for help, you must decide whether to end the scenario, give a hint, or give more substantial help.
- [ ] Update [recruiting spreadsheet](https://docs.google.com/spreadsheets/d/1wrx3dQXbti8kHvRdQFHuarW34DVnj0LNBs5nr3HDfBg/edit#gid=0) when session is done
- [ ] Upload recording to [Google Drive](https://drive.google.com/drive/u/0/folders/1XmT-fMEY5L82acY3aQC98v7misBPmDXb), under the folder for the FF page that was tested

**Comment by kelenelee** [comment]
# Participant `#`
Analyzed by: @_________ @_________ @_________ @_________
Analysis link: https://docs.google.com/..........

### Analysis
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the recording and observe participant behavior
- [ ] If the plan laid out quant metrics, use a spreadsheet to calculate the metrics. If the plan laid out qual metrics, use Figma to record observations.
- [ ] List problems and classify them as **critical** (If we do not fix this, users will not be able to complete the scenario), **serious** (many users will be frustrated if we do not fix this; they may give up) or **minor** (users are annoyed, but this does not keep them from completing the scenario)
- [ ] Revisit analysis findings as more people participate in the usability test

**Comment by allthatyazz** [comment]
- The test will be conducted on 5/13/2022 at 11:30 AM PST.  
 - Kelene is the moderator and Sandra is the notetaker. 
 - The moderator, notetaker, and PM have been coordinating the logistics via Slack constantly.

**Comment by kelenelee** [comment]
Ran out of time to do the usual prep action items because of the last minute prototype. [Recommendations doc](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit#heading=h.kl2jn8b02cz6) has been updated with summary of P3 analysis and recommendations.
