### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by hannahchatham** [hackforla/design-systems#416]
# Logistics 
- [ ] Complete [Hack for LA onboarding](https://www.hackforla.org/getting-started).
- [ ] Set aside at least 6 hours of time a week for HfLA work.
  - [ ] Agree to attend our [weekly meetings](https://github.com/hackforla/design-systems/wiki/How-to-join-the-HfLA-DS-team).
- [ ] For your issue: click `Star` at the top right of the page. Add yourself as **assignee**, choose the **label** `role: your-role`, and the **project** `Learn about design systems`.
- [ ] In the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q), introduce yourself and request access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, and [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663). @ the PM and your team lead in your message.
  - [ ] Once you have access, add yourself to [our roster](https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI).
- [ ] Read about [how Github works](https://github.com/hackforla/design-systems/wiki/Issues-101-and-glossary).

# About design systems
- [ ] Read chapter 1 of _[Design Systems](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf)_ by Alla Kholmatova.
  - [ ] As you read, take notes, and paste your notes in the [discussion thread](https://github.com/hackforla/design-systems/discussions/198).
- [ ] Read the [insight report from the stakeholder interview](https://drive.google.com/file/d/1QITYZvn2oFB4y9eakQjhQURrk-QS72Oj)

# Role-specific tasks
Complete the tasks for your role only (you may delete the other tasks that don't apply).
- [ ] Once you're completely done, comment on this issue and @ the PM or your team lead.

### Role: Design
- [ ] Submit [this issue template](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME) and use [this guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ) for help.
- [ ] Read [HfLA’s Design System Guide for Designers](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit).
- [ ] Learn about [double diamond](https://medium.com/design-council/the-double-diamond-15-years-on-8c7bc594610e).
- [ ] Review [this Figma file](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1) to further understand Stage 2A of the project.
- [ ] Watch [Figma's tutorials](https://www.youtube.com/watch?v=dXQ7IHkTiMM&ab_channel=Figma) on using Figma.

### Role: Research
- [ ] Submit [this issue template](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME) and use [this guide](https://docs.google.com/presentation/d/1YK7HAiW8-XPI57G8LfY2dgjxN7JknTE0262mhcvhLhQ) for help.
- [ ] Learn about [double diamond](https://nngroup.com/articles/discovery-phase).
- [ ] Read our [research plan](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo).
- [ ] Read our [insights from the stakeholder interview](https://drive.google.com/drive/folders/1pUyX4rNLs0je5XZrcEdC-6n1YLQjONBb).

### Role: Developer
- [ ] Read the [research from the previous lead developer](https://github.com/hackforla/design-systems/wiki/Appendix).

**Comment by kelenelee** [comment]
closing after Zoom convo with Hannah on 4/27
