### ISSUE TITLE
Cleanup of homepage, readme, and wiki

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#422]
- #395 was getting long and unwieldy so I have moved wiki cleanup tasks here, and wiki rewrites at #406

# Action Items 
- [x] Deleted or combined 32 stubs to declutter wiki IA and Pages nav. 
- [x] Uncheck Releases and Packages in the [DS repo homepage](https://github.com/hackforla/design-systems) sidebar.
- [x] Add a description to the repo sidebar

Through testing of the [fork](https://github.com/kelenelee/testing-design-systems?organization=kelenelee&organization=kelenelee), the description cannot handle bullet lists or links. This is probably because the description populates as 1 paragraph of plain text under [HfLA's list of repositories](https://github.com/orgs/hackforla/repositories). 

While we should still have some kind of description for the repo instead of it saying "No description provided," it's not clear whether something as simple as a sentence will help newcomers onboard or current members navigate and find information. Bulleted links would have been much more helpful for team members' tasks.

- [x] Update readme to better serve current DS team needs. Right now it takes many clicks for people to get to the Kanban board. It's possible for the beginning of the readme to have a link that goes directly there.

**Comment by kelenelee** [comment]
@allthatyazz can we get permission to edit the repo description? I might need to experiment with the copy?...

**Comment by allthatyazz** [comment]
@kelenelee Last time, I asked Bonnie how we can edit it, Bonnie responded that "What do you want the description to be? Put in the chat, [and] I'll edit it". So the implications for us:
 - We cannot receive the permission to edit 
 - We can do experimentations elsewhere like in the Figma file or even a through a GitHub poll or something

**Comment by kelenelee** [comment]
Thanks @allthatyazz. Because I forgot to document it (haha how ironic) I forgot that I forked this repo, and in the fork I can push description copy as many times as I want.

**Comment by allthatyazz** [comment]
@kelenelee Very smart! I was thinking that you can even take the screenshots of your fork each time you change something and then use the screenshots in a poll or something if you want to collect some feedback from the team.

Also, I have a question for you. By any chance, do you have any screenshots from our original GitHub board?

**Comment by kelenelee** [comment]
@allthatyazz I don't have any old screenshots... I really regret not taking a screenshot of it. I think I'll go through old meeting recordings and see if it's there

**Comment by allthatyazz** [comment]
Try your best but if you could not get any good screenshots, then no worries at all. I guess we can use the other teams' boards as a reference too.

**Comment by kelenelee** [comment]
Hi @allthatyazz I've settled on a draft description. I don't have alternatives so I don't think I need to create a poll. 
```
Empowering every HfLA team to create their own design system. 📌 Please see our `readme` for more info. 
```

[You can see a demo with the description here.
<img width="1009" alt="Screen Shot 2022-06-01 at 6 40 48 PM" src="https://user-images.githubusercontent.com/97491788/171513470-ad486494-7886-4a44-99f7-2d6eafd88480.png">](https://github.com/kelenelee/testing-design-systems)

**Comment by allthatyazz** [comment]
Bonnie has been sick and our meeting cut short. We would do this once she becomes better.

**Comment by allthatyazz** [comment]
We completed the checklist during 11/7 Stakeholder meeting and added more tag lines. We ended up keeping the release.
