### ISSUE TITLE
Add team members and set permission roles for the Design System Figma file

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#43]
### Overview
The current Design System Figma file was previously the UX/UI Community of practice file. This project started as a community of practice project before Design Systems was defined as a project. There are a large number of users who have an Edit role and are not attached to this project. Some Design System team members only have a View Only role. In order for the team to work collaboratively on this document the roles permissions need to change. We also need to be able to add future members to this file. 

### Action Items

- [ ] Invite team to the Figma file.

### Resources/Instructions
[Figma Document](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/UX-UI-Community-of-Practice?node-id=882%3A3934)

**Comment by nasimbiglari** [comment]
I have access to the file.

**Comment by Hanastevenson** [comment]
@daniellex0 to include this in ticket #106

**Comment by Hanastevenson** [comment]
Ticket redundant - please reference - #114
