### ISSUE TITLE
My 1st Issue! Learn about design systems and using Github

### ISSUE THREAD

**Issue by kangina-tech** [hackforla/design-systems#433]
# Logistics 
- [x] Complete [Hack for LA onboarding](https://www.hackforla.org/getting-started).
- [x] Set aside at least 6 hours of time a week to attend our [weekly meetings](https://github.com/hackforla/design-systems/wiki/How-to-join-the-HfLA-DS-team) and complete DS work.
- [x] In the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q), introduce yourself and request access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663), and Github repo. @ the PM and your team lead in your message. 
  - [x] Once you have access, add yourself to [our roster]([https://docs.google.com/spreadsheets/d/1Y65x1bC8tys80Xf7VjC0dVK7kQshlHwbLm6JpvNcMcI](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1544900430)).

### Exploring GitHub
You won't be able to do some of these tasks until we update your Github account's permissions.
- [x] At the top right of your issue, or any other webpage under `hackforla/design-systems`, you'll see a row of settings. Click `Pins` and select the checkbox `Profile`. This way, you'll be able to find DS via your profile. 
  - [x] Click `⭐ Star` at the top right of the page (not the dropdown). The button should turn into `⭐ Starred`. 
- [x] To the right of your issue, you'll see a list of settings. Make yourself an **assignee**.
  - [x] Select the **label** `role: _` (your role).
  - [x] Select the **project** `Learning about design systems`.
- [x] Read about [what Github is and how it works](https://github.com/hackforla/design-systems/wiki/Using-GitHub).

# About design systems
- [x] Read chapter 1 (pages 18-45) of _[Design Systems](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf)_ by Alla Kholmatova.
  - [x] Take notes as you read, and paste your notes in the [discussion thread](https://github.com/hackforla/design-systems/discussions/198).
- [x] Read the [insight report from the stakeholder interview](https://drive.google.com/file/d/1QITYZvn2oFB4y9eakQjhQURrk-QS72Oj)

# Role-specific tasks
Complete the tasks for your role only (you may delete the other tasks that don't apply).
- [x] Once you're completely done, comment on this issue and @ the PM or your team lead.

### Role: Design
- [x] Click the green button `Submit new issue` on [this page](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME). This issue will generate under HfLA's UX/UI community of practice and is meant to track the skills you learn during your time at HfLA.
- [x] Read [HfLA’s Design System Guide for Designers](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit).
- [x] Learn about [double diamond](https://medium.com/design-council/the-double-diamond-15-years-on-8c7bc594610e).
- [x] Review [this Figma file](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1) to further understand Stage 2A of the project.
- [x] Watch [Figma's tutorials](https://www.youtube.com/watch?v=dXQ7IHkTiMM&ab_channel=Figma) on using Figma.

**Comment by kelenelee** [comment]
@kangina-tech amazing I'll go ahead and close this, thank you :)

Btw, I haven't officially added these to the onboarding checklist yet, but I recommend checking out these two files: 

- [DS team's audit of other HfLA team's Figma files](https://drive.google.com/file/d/1QMdhVjvYIOU8e5uFpf8tvvOim-mUrwjz)
- [DS team's interview with the HfLA stakeholder](https://drive.google.com/file/d/1npVQG1by8_l5iB7jUmZ9_OzGtQ-6czU0)

Tbh they might be more important/helpful than some of the "Role: Design" action items. Sorry for adding more stuff to your plate.
