### ISSUE TITLE
My 1st issue! Learn about design systems and using Github

### ISSUE THREAD

**Issue by rachelita2** [hackforla/design-systems#438]
- [x] In the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q), introduce yourself and request access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663), and Github repo. @ the PM and your team lead in your message. You won't be able to proceed with your onboarding tasks until we've given you access.

# Github

### Repository settings

<img width="300" alt="Screen Shot 2022-08-29 at 1 30 41 PM" src="https://user-images.githubusercontent.com/97491788/187262497-40a362d4-b91b-4eb0-8dc3-804aa8afdc1a.png">
At the top right of this page, you should see these repository settings.

- [x] Click `Pins` and select the checkbox `Profile`. This way, you'll be able to find DS via your profile. 
- [x] Click `⭐ Star` at the top right of the page (not the dropdown). The button should turn into `⭐ Starred`. 
### Issue settings
<img width="150" alt="Screen Shot 2022-08-29 at 1 58 38 PM" src="https://user-images.githubusercontent.com/97491788/187267671-c7f9e82a-de2f-49f2-9b2d-2a22b5ce1d15.png">
To the right of this page, you should see these issue settings.

- [x] Make yourself an assignee.
- [x] Select the label `👤 (your role)`.
- [x] Select the project `Learning about design systems` and change the status to "In progress."
### Navigating our wiki
<img width="500" alt="Screen Shot 2022-08-29 at 2 26 29 PM" src="https://user-images.githubusercontent.com/97491788/187272041-a7861dab-b3b9-4636-8873-f1e100e318b9.png">

At the top of this page, find "Wiki." 
- [x] Under "Pages," read the "Documentation 101" article about how GitHub works.

### The HfLA UX/UI Community of Practice
The UX/UI CoP is a repository for all of HfLA's UX designers and researchers, across teams. 
- [x] Submit [this UX/UI CoP issue](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME). This issue will generate under the CoP repository, and is meant to track the skills you learn during your time at HfLA.
<img width="488" alt="Screen Shot 2022-08-30 at 10 47 56 AM" src="https://user-images.githubusercontent.com/97491788/187470660-c25f1e75-4252-4a75-b9a1-5103b18acb15.png">

- [x] At the very top of this page, find "Issues." Here you'll be able to find all issues that you've created or been assigned to, regardless of which repository it's a part of.
# Drive
<img width="350" alt="Screen Shot 2022-08-29 at 1 50 28 PM" src="https://user-images.githubusercontent.com/97491788/187265863-c0baa0dd-a13f-429a-b380-c5aea4c00dca.png">

On our [Google Drive](https://drive.google.com/drive/u/0/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp), you should see these folder settings.

- [x] Add this folder to your Starred. This will allow you to access our folder from the left sidebar.
- [x] Add yourself to our roster.
- [x] Under "Research" > "Design system best practices," find the PDF of Alla Kholmatova's _Design Systems_ book and read chapter 1 (pages 18-45).
- [x] Under "Research" > "Stakeholder," listen to the stakeholder interview.

# Yay!
- [ ] Once you're completely done with all action items on this issue, add a comment below and @ the PM and your team lead.

**Comment by rachelita2** [comment]
@allthatyazz @kelenelee Finished with most of my 1st issue/onboarding stuff but the link for "read about Github is and how it works" doesn't work.

**Comment by allthatyazz** [comment]
@rachelita2 Great progress Rachel! Sorry about the broken link. I will wait for @kelenelee to respond back about the intended link but in the meantime, you can take a look at this issue on [GitHub Documentation](https://github.com/hackforla/design-systems/wiki/Documentation-101#how-github-organizes-documentation) written by Kelene and the storytelling is spot-on.

**Comment by allthatyazz** [comment]
OMG ! @kelenelee The onboarding checklist looks so good and user-friendly.

**Comment by kelenelee** [comment]
Thank you - i'm going to try out this checklist instead because of the images and getting the new person accustomed to navigating Figma and Github, instead of direct links that create a vacuum kind of feeling.

**Comment by rachelita2** [comment]
@kelenelee sorry for so many questions but now I can't find the "Research" link anymore to listen to the stakeholder interview. I think that's the last thing I have to do to complete onboarding. Is it somewhere on the page that I screen-shotted here?
<img width="1440" alt="Screen Shot 2022-09-01 at 10 35 44 AM" src="https://user-images.githubusercontent.com/110951589/187941368-6dcbe097-0aeb-49e7-8bd6-b4a5de2a55bd.png">

**Comment by kelenelee** [comment]
@rachelita2 it's the "Figma Kit Research" folder
