### ISSUE TITLE
Documentation Tools Initial Research - Storybook 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#44]
### Overview
Explore Storybook, figure out how easy it is to understand the documentation tool's doc. Figure out how easy is configuration for a React App.

### Action Items
- [ ] How long did exploring take, from research to base template? 
   - [ ] Log time
- [ ] Is the tool’s documentation easy to understand? 
   - [ ] Did you have to use other dev’s GitHub repo to understand the docs
- [ ] Figure out settings:
   - [ ] What is the out of the box setting? 
   - [ ] What addons are available?
- [ ] What are the pros?
   - [ ] What do you like about this tool?
- [ ] What are the cons? 
   - [ ] What are your struggles with this tool?

### Resources/Instructions
* [Storybook Docs](https://storybook.js.org/)
* [DS Google Doc - exploring documentation tool](https://docs.google.com/document/d/11P0zerv0kshcd8KtqmKePg20fBv-wczskrM4CUHWngE/edit)

**Comment by qiqicodes** [comment]
How long did exploring take, from research to base template?
* 40+ min

 Is the tool’s documentation easy to understand?
* Storybook's documentation and GitHub ReadMe are easy to understand
* cli command to setup storybook `npx sb init`
* current setup guide [storybook readme](https://github.com/storybookjs/storybook/blob/master/app/react/README.md)

 Figure out settings:
* The box setting is a boilerplate with button, header, introduction stories and page
* [Addons](https://storybook.js.org/docs/react/addons/introduction) are available

 What are the pros?
* Easy to set up
* Lots of features
* Good documentation
* Clean interface
* Lots of resources because people use this documentation tool 

 What are the cons?
 * There are lots of resources, accidentally created a deprecated version of storybook.


<details>
<summary>Click to View Screen Captures of Storybook</summary>
<img src="https://im4.ezgif.com/tmp/ezgif-4-b133cf58ebeb.gif">
</details>

**Comment by kelenelee** [comment]
- [ ] #45
- [ ] #47 
- [ ] #51
