### ISSUE TITLE
My 1st issue! Learn about design systems and using Github

### ISSUE THREAD

**Issue by rsschacht** [hackforla/design-systems#442]
You'll need to complete [Hack for LA onboarding](https://www.hackforla.org/getting-started) before beginning this checklist. If you're deciding between HFLA teams, you can request in our Slack channel to observe one of our all-hands meetings first.

# Slack
- [x] Introduce yourself in the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q). Request a recurring 1-on-1 meeting with your team lead, and that the PM grant you access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663), and Github repo. (Until you have access, some of the following links will not work.) @ the PM and your team lead in this message. 
  - [ ] Check your calendar and accept the invites to our recurring meetings. You might occasionally be asked to attend a meeting outside of your function.
- [ ] Update your Slack profile in the HFLA workspace. Under **Title**, type in your role and the name of the team (i.e. "UX Writer, Design Systems"). 
  - [ ] Under **Pronunciation**, type in any pronunciation guidelines and your preferred pronouns. 

<img width="500" alt="Screen Shot 2022-11-08 at 6 12 39 PM" src="https://user-images.githubusercontent.com/97491788/200696071-b9f6dfe4-5af6-4d4a-8a27-b38c61305ff9.png">

# GitHub
Doing the following tasks on desktop is recommended.

### Profile settings 
<img width="300" alt="Screen Shot 2022-08-29 at 1 30 41 PM" src="https://user-images.githubusercontent.com/97491788/187262497-40a362d4-b91b-4eb0-8dc3-804aa8afdc1a.png">

- [ ] At the top right of this very webpage, you'll see a row of dropdown menus. Click "Pins" and select the "Profile" checkbox. Now, you and all Github members will be able to find DS via your profile (`github.com/yourusername`). 
  - [ ] Click "⭐ Star" so the button turns into `⭐ Starred`. Now, people will be able to find your profile from [our repository's homepage](https://github.com/hackforla/design-systems).

<img width="150" alt="Screen Shot 2022-08-29 at 1 58 38 PM" src="https://user-images.githubusercontent.com/97491788/187267671-c7f9e82a-de2f-49f2-9b2d-2a22b5ce1d15.png">

### Issue settings
- [x] Below the Pins and Star settings, you'll see a list of more settings, starting with "**Assignee**" at the top. Add your Github username as an assignee.
  - [x] Select the **label** `role: _` (your role).
  - [x] Select the **project** `Learning about design systems`.
  - [ ] Click `🚧 BACKLOG` to open a dropdown, and select `✈️ IN PROGRESS`.
### About project documentation
<img width="500" alt="Screen Shot 2022-08-29 at 2 26 29 PM" src="https://user-images.githubusercontent.com/97491788/187272041-a7861dab-b3b9-4636-8873-f1e100e318b9.png">

- [x] At the top of this page, find "Wiki." Under "Pages," read the "Documentation 101" article about how project documentation works.

<img width="488" alt="Screen Shot 2022-08-30 at 10 47 56 AM" src="https://user-images.githubusercontent.com/97491788/187470660-c25f1e75-4252-4a75-b9a1-5103b18acb15.png">

- [x] At the very top of this page, find "Issues." Here you'll be able to find all issues that you've created or been assigned to, regardless of which repository it's a part of.
# Drive
- [x] In [our Google Drive folder](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp), add yourself to our roster spreadsheet.
- [x] Under "Tutorials", find the PDF of Alla Kholmatova's _Design Systems_ book and read chapter 1 (pages 18-45).
- [x] Under "User Insights" > "Stakeholder", listen to the stakeholder interview. You can follow along with the transcript.
# Other readings
- [ ] Learn about [user-centered design](https://www.nist.gov/itl/iad/visualization-and-usability-group/human-factors-human-centered-design) (more [terms and definitions](https://www.iso.org/obp/ui/#iso:std:iso:9241:-210:ed-2:v1:en)) and [task analysis](https://www.youtube.com/watch?v=tEx8R4ePwmk).
- [ ] If you're a designer or writer, watch Figma's [official Figma tutorials](https://www.youtube.com/playlist?list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4). Read about the [differences between frames and groups](https://www.figma.com/best-practices/groups-versus-frames/) ([part 2](https://www.figma.com/best-practices/groups-versus-frames/frames/), [part 3](https://www.figma.com/best-practices/groups-versus-frames/summary/)).

# Yay!
- [ ] Once you're completely done with all action items on this issue, add a comment below and @ the PM and your team lead.

**Comment by allthatyazz** [comment]
Access to Drive, Figma, GitHub, and calendar granted. Drive permission would be updated once you start your first assignment.

**Comment by kelenelee** [comment]
Hi Robert, thanks for starting your onboarding checklist! 😃 I have updated the checklist with slightly different reading requirements to hopefully better prepare you. If you have ANY feedback on the checklist, readings, etc, please reach out to me here and/or via Slack – I am SUPER happy to help.
