### ISSUE TITLE
My 1st issue! Learn about design systems and using Github

### ISSUE THREAD

**Issue by ayahabasha** [hackforla/design-systems#443]
# Logistics 
You'll need to complete [Hack for LA onboarding](https://www.hackforla.org/getting-started) before beginning this checklist.
- [ ] In the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q), introduce yourself and request access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663), and Github repo. @ the PM and your team lead in your message. Until you have access, some of the following links will not work.
- [ ] Accept the Google Calendar invites to our recurring meetings. You do not have to go to meetings for a role that isn't yours (e.g., designers don't have to go to research team meetings).
- [ ] Add yourself to [our roster](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1544900430).
- [ ] Update your Slack profile in the HFLA workspace. Under **Title**, type "`Role`, Design Systems" (for example "UX Writer, Design Systems"). Under **Pronunciation**, type your pronouns and any tips on how to say your name. (Bonus: adding your name pronunciation into your Zoom profile [in Zoom settings under "display name"](https://us05web.zoom.us/profile) is recommended.) Under **Status**, type in the days that you are generally free to work / be contacted, i.e. "Tuesday afternoons," "weekdays after 6pm," etc. 
- [ ] In Slack, send a direct message to your team lead to schedule a recurring 1-on-1 meeting.

### GitHub
Doing the following tasks on desktop is recommended.
- [ ] At the top right of this very webpage, you'll see a row of dropdown menus. Click "Pins" and select the "Profile" checkbox. Now, you and all Github members will be able to find DS via your profile (`github.com/yourusername`). 
  - [ ] Click "⭐ Star" at the top right of the page (not the dropdown). The button should turn into `⭐ Starred`. Now, people will be able to find your profile from our repository's homepage.
- [ ] Below the Pins and Star settings, you'll see a list of more settings, starting with "**Assignee**" at the top. Add your Github handle as an assignee.
  - [ ] Select the **label** `role: _` (your role).
  - [ ] Select the **project** `Learning about design systems`.

# About what our team does
- [ ] Learn about [user-centered design](https://www.nist.gov/itl/iad/visualization-and-usability-group/human-factors-human-centered-design) (more [terms and definitions](https://www.iso.org/obp/ui/#iso:std:iso:9241:-210:ed-2:v1:en)) and [task analysis](https://www.youtube.com/watch?v=tEx8R4ePwmk).
- [ ] Read chapter 1 (pages 18-45) of [_Design Systems_ by Alla Kholmatova](https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf). 
- [ ] Listen to the [stakeholder interview](https://drive.google.com/file/d/1npVQG1by8_l5iB7jUmZ9_OzGtQ-6czU0/view?usp=sharing) ([transcript](https://drive.google.com/file/d/1npVQG1by8_l5iB7jUmZ9_OzGtQ-6czU0)).
- [ ] Read about [what Github is and how it works](https://github.com/hackforla/design-systems/wiki/Using-GitHub).

# Role-specific tasks
Find your role, and only complete the tasks under your role.
- [ ] Once you're completely done, comment on this issue and @ the PM or your team lead.

### Designers and Researchers
- [ ] Click the green button `Submit new issue` on [this page](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME). This issue will generate under HfLA's UX/UI community of practice and is meant to track the skills you learn during your time at HfLA. 
- [ ] If you're a designer, watch Figma's [official Figma tutorials](https://www.youtube.com/playlist?list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4). Read about the [differences between frames and groups](https://www.figma.com/best-practices/groups-versus-frames/) ([part 2](https://www.figma.com/best-practices/groups-versus-frames/frames/), [part 3](https://www.figma.com/best-practices/groups-versus-frames/summary/)).
- [ ] If you're a researcher, watch Figma's [official Figjam tutorials](https://www.youtube.com/playlist?list=PLXDU_eVOJTx7yUfX46VEB3VafmkdNpZhq).

### Developer
- [ ] Read the [research from the previous lead developer](https://github.com/hackforla/design-systems/wiki/Appendix).

### Product manager
- [ ] Schedule a meeting with Bonnie.
- [ ] Read [this NNG article on the complexity of defining PM responsibilities](https://www.nngroup.com/articles/pm-ux-different-views-of-responsibilities/).

**Comment by allthatyazz** [comment]
Ayah has moved forward with another team.
