### ISSUE TITLE
HfLA Figma Kit V1 Release

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#445]
# Overview 
Prior to the release of the V1 to CoP, this issue tracks the remaining tasks about to get the product out of the door by the set deadline.  

**ACTION ITEMS**
# General for all Pages
- [x] The Frame should be named correctly
- [x] The template boxes should be grouped properly with every element having an accurate name.
# Cover Page
-  [x] The sizing standard should be aligned with Sandra's research and reflect the recommended dimension by Figma.   
   -  [x] Solution A: " Frame size at least 1200 X 800. The recommended dimensions are 1600 X 960. "
   -  [ ] Solution B: " Frame size at least 1200 X 800. Use our template for best result" + Include Figma's recommended dimensions in action step No.2. 
 -  [x] The name of the template frame should reflect the accurate measurement. 
- [x] Fix the example page's little subtitle to reflect Rachel's comment "the top two examples have a solid noun (frame size) while the bottom two use "it," which is vague. Would you consider rewording to "Cover contains project name and some visual element" and "Cover lacks project name..." for the second row and "Cover page contains only one frame on the first page of your file" and "Cover page contains multiple frames on the first page of your file"? "
# Organize Pages
- [x] On example pages: bring the "Do's" as the first column and create a consistent look with the cover example. Debbie has good justifications for why she opted in for Don'ts as the first column- we can investigate Debbie's version during user feedback sessions. 
- [ ] On example pages rework the subtitles for Do's and Don'ts to create consistency with the Cover examples.
- [x] On Tips pages, reorder tips 4, 5, 3, and 1. Remove tip 2 as it is not a problem related to the organization of the Figma pages inherently. 
# Start Page
- [ ] Fix the screenshots
# Release Logistics 
- [x] The latest iterations should be replaced in this [Figma file](https://www.figma.com/file/XIy3Dciciej4Q6A1TXGMS1/HfLA-Figma-Kit?node-id=2%3A16).
- [x] Add the release to GitHub main page. 
- [x] Attending UX/UI CoP meeting on Wednesday 11/9.

**Comment by sandraberjan** [comment]
I used Solution A but in abbreviated form.

**Comment by sandraberjan** [comment]
I renamed all the frames minus the templates. Please check for any errors.

**Comment by sandraberjan** [comment]
I reordered the tips and deleted tip #2. I did not change the numbers to indicate new order. Asked @kangina-tech to help with that.

**Comment by sandraberjan** [comment]
I put the latest designs I have into the sections. please check for any flaws/visual fixes

**Comment by allthatyazz** [comment]
I made more cleaning and last-minute changes to the file. Everything looks good and we are ready for presenting our work to CoP. 
- Fixing the group names for some of the important elements. 
- Fixing the copy "Start here" across all the sections including the Cover/Thumbnail. 
- Making the text styles of the "start here" standards consistent with other pages. 
- I put the release note at the end of our current pages.

**Comment by allthatyazz** [comment]
The release note and the link to the Figma file have been added to our main GitHub page.

**Comment by allthatyazz** [comment]
Attended the CoP meeting. The leads were super supportive and applauded our work. It seems there is no clear process to advertise the Kit or similar resources to HfLA community.  I raised the question tonight and the leads responded that they plan to work on some processes to advertise work to HfLA.
