### ISSUE TITLE
Creating New Agenda for 2023 Design Meetings

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#462]
### Overview

We need to create an agenda for design meetings so that we can bring more structures to the team meeting.  

### Action Items

- [ ] Research 
   - [ ] Review previous Agenda to determine what has worked in the past and what has not. 
   - [ ] Gather examples from other projects (This can be samples from outside of HfLA)
- [x] Create a New Issue in GitHub Title [ Design Systems: UX/UI - 2023 Agenda] 
  - [x] Create a template in the main body of the issue that can be used for recurring meetings. If you do not know how to do this tag PM. 
      - [x] Include the [attendance sheet](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit?usp=sharing) on top
      - [x] Include the following sections: Task items to be discussed in that meeting, Meeting notes, Action Items for future assignments 
  - [x] Add the Agenda label and Add the Design Role label. 
  - [x] Assign all the active members of the Design team.
  - [x] Add to the DS Team Initiatives project board, Start Here Column   

### Resources/Instructions
- [Fig Jam](https://www.figma.com/file/pNWxXSsxns477rASJjC2KN/Meeting-Agenda?node-id=0%3A1&t=2XYxLngZyOMFqnnI-1) agenda that we can incorporate to the new template for 2023 agenda

**Comment by allthatyazz** [comment]
@kangina-tech @khanhcao17  If you are done with the above items, you can check the box- also, you can add other notes here.

**Comment by khanhcao17** [comment]
2023 Design Agenda has been created - https://github.com/hackforla/design-systems/issues/464#issue-1531409944

**Comment by allthatyazz** [comment]
Great job!

**Comment by allthatyazz** [comment]
The new agenda looks great. I would like to recommend that the 2022 agenda would be only included in the resource section of the first comment and not the template itself.
