### ISSUE TITLE
Documentation Tools Initial Research - Pattern Lab

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#47]
### Overview
Explore Pattern Lab, figure out how easy it is to understand the documentation tool's doc. Figure out how easy is configuration for a React App.

### Action Items
- [ ] How long did exploring take, from research to base template? 
   - [ ] Log time
- [ ] Is the tool’s documentation easy to understand? 
   - [ ] Did you have to use other dev’s GitHub repo to understand the docs
- [ ] Figure out settings:
   - [ ] What is the out of the box setting? 
   - [ ] What addons are available?
- [ ] What are the pros?
   - [ ] What do you like about this tool?
- [ ] What are the cons? 
   - [ ] What are your struggles with this tool?

### Resources/Instructions
* [Pattern Lab Docs](https://patternlab.io/)
* [DS Google Doc - exploring documentation tool](https://docs.google.com/document/d/11P0zerv0kshcd8KtqmKePg20fBv-wczskrM4CUHWngE/edit)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by qiqicodes** [comment]
How long did exploring take, from research to base template?

 * 5-10 minute to set up the base template. However need extra time to learn Handlebars or Twig

 Is the tool’s documentation easy to understand?
 * Documentation is easy to understand and easy to follow.

 Figure out settings:

 * Full pattern template is available out of the box.
 * There are customizable templates.

 What addons are available?
* No addons are needed.

 What are the pros?
* Documentation is clean and well written.

 What are the cons?
* Need time to learn templating language to use this tool.
<details>
<summary>Click to View Screen Captures of Pattern Lab</summary>
<img src="https://user-images.githubusercontent.com/68657634/136642998-4713d519-4010-4793-9bd3-b647693058f2.gif">
</details>
