### ISSUE TITLE
Write a research plan for post-Launch user testing for v.1 

### ISSUE THREAD

**Issue by rachelita2** [hackforla/design-systems#476]
### Overview

These are the opening steps for our research team to focus on in January as we plan conceptual inquiry testing for the Design Systems Figma Kit v.1

### Background

v.1 of the Design Systems Figma kit was released in November, intended for adoption by all 23 organizations in the Hack for LA ecosystem. In January and February we would like to test this kit with several users to determine pain points and what is working. 

### Action Items

- [x] Familiarize yourself with v.1 of the Figma kit, below.

- [x] Think about research methods that you think would be useful for testing this kit, for discussion in our next meeting on 1/18/23.

- [x] Look at the Design Team's questions they are hoping to get answered by our research and consider how we could incorporate these questions into an interview process without biasing the user toward one option over another. (link below)

- [x] Find five users from other Hack for LA teams willing to be interviewed about their opinions on the Figma kit.

### Resources/Instructions

Direct Link to Figma kit v. 1 that will be tested with 5 users:

https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A34&t=OwPz3EBRuT85xBhT-0

Link to GitHub issue #463, design team's questions:

https://github.com/hackforla/design-systems/issues/463)

Link to GitHub announcement of release of Figma Kit, with link to kit and release notes:

https://github.com/hackforla/design-systems/releases/tag/v1.0

**Comment by allthatyazz** [comment]
- Gala created[ a draft](https://docs.google.com/document/d/1u95uWRK_IVvVbChKSdrudCBKXF7oM_mXPfP2H0nGEUI/edit?usp=sharing) of possible questions for the user testing.

**Comment by elimarietta** [comment]
I added comments as well but primarily appreciated learning from your expertise @GalaStojnic and @fuzjan81.

**Comment by fuzjan81** [comment]
Hello everyone, I just created a document for us to work on for questions and tasks. It's here:

https://docs.google.com/document/d/1fwju0nVbA1ijrLvJ4LDlRAXn7xYq58v6iEQVgtL-eWE/edit

**Comment by EvaKw** [comment]
Thanks for creating the doc! I added in some notes.

**Comment by zeaslan** [comment]
Thanks for creating the document! I also added a couple of questions and comments.

**Comment by GalaStojnic** [comment]
Thanks for creating the document, I added some questions and comments.

**Comment by elimarietta** [comment]
Thank you Faezeh! I added comments too.

**Comment by elimarietta** [comment]
I added more questions and comments to Faezeh's document.

**Comment by allthatyazz** [comment]
- Link to [Final Plan Doc](https://docs.google.com/document/d/1fwju0nVbA1ijrLvJ4LDlRAXn7xYq58v6iEQVgtL-eWE/edit?usp=sharing)
- There have been some minor changes after the first two participants and one major change was that we omitted the Likert scale questions. We discussed this in detail in the research meeting notes.https://github.com/hackforla/design-systems/issues/479#issuecomment-1444976943
