### ISSUE TITLE
Update Project One Sheet

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#486]
### Overview

Update the project one sheet so it can be shared with stakeholders and funders.

### Background

HfLA uses the project one-sheet in lieu of sophisticated product roadmaps. This document is used on HfLA's [website, under the link Overview](https://www.hackforla.org/projects/design-systems.html). According to HfLA's website, the last time the DS team updated our project one sheet was September 2021. 

### Action Items

- [x] Make a copy of the one sheet template  
- [x] Review one sheet and check off items on the checklist to see what it might be missing.
- [x] Setup a meeting with the PM to go over the project to confirm what information on the sheet is up to date and what needs revision.
- [ ] Store a copy of the one sheet in the product management google drive/one sheet revisions

###
Checklist
- [x] Include project logo (top right)
- [x] Overview
- [x] History and or last 6 months
- [x] Partners
- [x] Roadmap/next 6 months
- [x] Contact email (footer)
- [x] Github URL (footer)
- [x] Link to project page on hackforla.org (footer)
- [x] Slack channel (footer)
- [x] Last updated date (footer)
- [x] Hack for LA logo (bottom right) 

### Resources/Instructions

Old DS one sheet [Google Doc](https://docs.google.com/document/d/1DsKRts479ibNi2EIdOzGeWv9sEY_eMMmy6mw_x6fFqo/edit#heading=h.n7lqzt5pn1610)

[One Sheet Template](https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit?usp=sharing)
[How to create a One Sheet guide](https://docs.google.com/document/d/14-nYNCjrMrC8lucUNBfLOFQZk2sWbkRlJgigWDAlqlI/edit#heading=h.z4tpbshl55b9)

**Comment by allthatyazz** [comment]
This is the link to the new [Google Doc for One Sheet](https://docs.google.com/document/d/1ZPorVHsczML7oBSCBgox8056deegOjFF9F--By15shI/edit?usp=sharing). 

- On Monday 2/6/23, I shared the document with Bonnie and Josh during the PM and Stakeholder meeting.

**Comment by allthatyazz** [comment]
@ExperimentsInHonesty Based on your feedback, I revised the one sheet. Here is the side-by-side comparison of [the Old](https://docs.google.com/document/d/1DsKRts479ibNi2EIdOzGeWv9sEY_eMMmy6mw_x6fFqo/edit?usp=sharing) Vs [updated](https://docs.google.com/document/d/1ZPorVHsczML7oBSCBgox8056deegOjFF9F--By15shI/edit?usp=sharing) One sheet. Please let me know if you have any additional feedback. Thank you. 
![image](https://user-images.githubusercontent.com/100178353/218562815-d8dbfe82-5edc-4c5a-a92d-e9857a146e39.png)
![image](https://user-images.githubusercontent.com/100178353/218563900-ce2be473-4adc-49c0-83bd-da1e32c1262d.png)

**Comment by ExperimentsInHonesty** [comment]
You tried to take space from the page to use further down in the page (changing the format from 11 lines to 9)
1. The logo is smaller which might be ok, but its not standard across all projects
2. Top portion is missing a space between the paragraphs making it look like a mistake


6 Month Roadmp 
where it says
Update the existing UI assets library to reflect the needs of the developers
Update the existing UI assets library to improve designers/developers collaboration.

**Comment by ExperimentsInHonesty** [comment]
# New version

History 
In August 2020, Hack for LA was in the midst of rapid growth of new volunteers. New designers and developers joined projects without clear systems in place to standardize their work and scale their teams. Leadership recommended developing organization-wide design system guidance to enable all volunteers to learn about, create, and maintain design systems for their HfLA projects. 

In 2021 and early 2022, the DS team built a visual assets library in Figma including the basic element of Design Systems so other projects’ designers can reference the file as a starter template.

In 2022 Q1 and Q2, the DS team’s researchers conducted generative interviews with HfLA’s volunteers in different roles, and the result of the discovery phase revealed the need for a new product initiative called “HfLA Figma Kit.” HfLA Figma Kit serves as an educational platform for designers at HfLA consisting of  Standards, Starter templates, Tutorials and Examples on Figma project governance and Design Systems.  

Recent Progress 
The HfLA Figma Kit v1.0 was released in Nov 2022.

**Comment by ExperimentsInHonesty** [comment]
# old version

History 
In August 2020, Hack for LA was in the midst of rapid growth of new volunteers. New designers and developers joined projects without clear systems in place to standardize their work and scale their teams.
An HfLA website audit revealed that having no clear system resulted in considerable design and development inconsistencies, miscommunication and inefficiencies within the team. Following industry standards, they created a design system to resolve the problem. 
Leadership recommended developing organization-wide design system guidance to enable all volunteers to learn about, create, and maintain design systems for their HfLA projects.

**Comment by allthatyazz** [comment]
- Pull Request was created under Bonnie's supervision on 3/6. 
- Link to commit folder  https://github.com/hackforla/product-management/tree/master/project-one-sheets
