### ISSUE TITLE
Documentation Tools Initial Research - Cupper

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#49]
### Overview
Explore Cupper, figure out how easy it is to understand the documentation tool's doc. Figure out how easy is configuration for a React App.

### Action Items
- [x] How long did exploring take, from research to base template? 
   - [x] Log time
- [x] Is the tool’s documentation easy to understand? 
   - [x] Did you have to use other dev’s GitHub repo to understand the docs
- [x] Figure out settings:
   - [x] What is the out of the box setting? 
   - [x] What addons are available?
- [x] What are the pros?
   - [x] What do you like about this tool?
- [x] What are the cons? 
   - [x] What are your struggles with this tool?

### Resources/Instructions
* [Cupper Docs](https://thepaciellogroup.github.io/cupper/)
* [DS Google Doc - exploring documentation tool](https://docs.google.com/document/d/11P0zerv0kshcd8KtqmKePg20fBv-wczskrM4CUHWngE/edit)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by qiqicodes** [comment]
Implemented in [Documentation Tool Wiki page](https://github.com/hackforla/design-systems/wiki/Documentation-Tools)
