### ISSUE TITLE
Conduct contextual inquiries 

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#492]
### Overview

We need to conduct interviews with the designers at HfLA to solicit data from the end users of the Kit.  

### Background
**Related Issues**
 -   #476
 -  #493
 
| Participant / HfLA Team | Date | Moderator | Live Note Taker |
| - | - | - |- |
|P1 / Access the Data | 2/17/2023 | @elimarietta  | @EvaKw  |
|P2 / FOLA | 2/21/2023 | @zeaslan   |  @elimarietta  |
|P3 / Expunge Assist | 2/23/2023 | @fuzjan81    |  @allthatyazz  |
|P4 / TDM Calculotor | 2/25/2023 | @GalaStojnic     | @khanhcao17  |
|P5 / Home Unite US | 3/7/2023 | @EvaKw  | @zeaslan  |

### Action Items

**Pre-interview** 
- [x] Recruit participants by messaging on Slack using the recruitment message below
> Hello! I am part of the Design Systems research team at Hack for LA and we’re looking for designers to help us out with a new research study. Specifically, we’re in the evaluative phase of research focused on our product, version 1.0 of the HfLA Figma Kit, designed for adoption by all Hack for LA Projects.
We would love your feedback on the existing version of the kit—to know what works well and what may need improvement. This would involve an online session with us, where we’d ask you to interact with the kit and tell us your impressions. The session will take about 45min during which you’d get to directly partake in a user research study that could improve all 20+ Hack for LA Projects that use the kit! 
If you’d be interested in this, let us know by replying to this message and we will contact you about scheduling.
- [x] Coordinate a time with the participant 
- [x] Send the following reminder prior to the interview
> Hi ! We are excited to meet with you today at 6 pm [put the date and time]. In preparation for our session, it would be really great if you could do the following tasks prior to our meeting time in order to have a smooth experience: 1. Have your Figma recent page open in your preferred browser.  As part of our test, you will be asked to create a new design file in your drafts. 2. Have your Hack for LA's Figma file open in a separate browser tab so it would be already loaded.

**On the day of**
If you are the moderator 
- [x] Start the call a few minutes early
- [x] Make sure Otter.ai or the auto transcriber work properly
- [x] Make sure to give the participant permission to share their screen
- [x] Ask for the user's consent to record
- [x] Record (if you are using someone else's zoom pro account save the recording locally on your device)
- [x] Upload the recording afterward to Google Drive

If you are the notetaker,
- [x] Have your mic and video turned off
- [x] Depending on the flow of the conversations and if the time allows, unmute yourself to ask follow-up questions
- [x] Upload your notes to the drive afterward

### Resources/Instructions

[Google Drive ](https://drive.google.com/drive/folders/1ewOmysRQKk9AQxpSMMWZLPvBF0Zh1Y3r?usp=share_link)

**Comment by allthatyazz** [comment]
Do we have the complete transcript for P3? The last 15 mins of the call seem to be missing from the current file.

**Comment by fuzjan81** [comment]
Yes, I noticed the same thing. I am not sure why this has happened. I can't
seem to zoom transcript..I'll look for it and try and upload it.

**Comment by allthatyazz** [comment]
All the interviews have been recorded and saved on Drive.
