### ISSUE TITLE
Analyze contextual inquiries on Figma Kit v1.0 

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#493]
### Overview

We need to analyze the contextual inquiries to produce actionable insights from the end users to improve the Kit.

### Background

Related issues 
- #476 
- #492

### Action Items
**Preliminary observations** 
- [x] Watch the recording and observe participant behavior. You can have the transcript file open and correct the file as you listen. Be ready to pause the video as many times as needed. 
- [x] Take notes (You can add your notes directly as comments to the transcript + take screenshots from the video and add them to the transcript as well).
- [x] [Make slides](https://docs.google.com/presentation/d/1zsR3iOM1MEpcz7Z65-WPZODfIep-ZzpwzL_QGKgxmeI/edit?usp=sharing) here based on your observations 

**In-depth analysis** 
- [x] Comment on this analysis issue who has been doing the video analysis
- [x] Choose a method for analysis 
   - [ ] Code on Google Docs using color-coded themes. See a sample of the previous analysis we did [here.](https://docs.google.com/document/d/1fi-2YEFQcAk-NMb2pJllPR2t91FQ1KItrVttvt1lzBI/edit?usp=sharing)
   - [ ] Do an affinity map or other method. If you choose this method see below.   
- [ ] Revisit analysis findings as more people participate in the user test 
- [ ] Draft an insight report to share with the designers

**If you choose affinity mapping** 
- [x] Copy and paste the template below to the comment section to create a checklist of the possible action items (you can modify the steps later)
```

### Action Items for an affinity mapping exercise

- [ ] Listen to the interview.
- [ ] In preparation of the affinity mapping exercise, generate sticky notes with the themes, ideas, and understandings that you have derived from the [Figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Finish organizing the sticky notes with the team.
- [ ] After the sticky notes organization, funnel the insights into the following elements in order to better prepare for the insight reports: user pain points, user needs, organizational needs (if applicable), themes, key insights, and if applicable other themes that are of research interest for a later point time.
- [ ] Put together the insights in your box in [figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Inform the leads

### Generate sticky notes guidelines
Please, read the following guidelines for the sticky note generation exercise. In this way, we increase our understanding during the sorting.
- [ ] Put -**Q**- on the sticky note if you write down a direct quote from the interview including the regarding time stamp through the following format: -**min: 2.28**-.
- [ ] If you have a larger code and you want to leave out a part or certain words, please indicate that you have done so by replacing that piece of text with the following -**[...]**-. In that way, we at least know that there is a piece of information missing from the quote.
- [ ] Put -**I**- if you write down an insight that you derived from the interview.

### Resources/Instruction
[Nielsen Norman Group article on Affinity mapping](https://www.nngroup.com/articles/affinity-diagram/)
```

 

### Resources/Instructions

- The [Google Slide ](https://docs.google.com/presentation/d/1zsR3iOM1MEpcz7Z65-WPZODfIep-ZzpwzL_QGKgxmeI/edit?usp=sharing)
- The[ FigJam file ](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1)that can be used for affinity mapping exercise

**Comment by allthatyazz** [comment]
### Yas Action Items for an affinity mapping exercise

- [ ] Listen to the interview.
- [ ] In preparation of the affinity mapping exercise, generate sticky notes with the themes, ideas, and understandings that you have derived from the [Figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Finish organizing the sticky notes with the team.
- [ ] After the sticky notes organization, funnel the insights into the following elements in order to better prepare for the insight reports: user pain points, user needs, organizational needs (if applicable), themes, key insights, and if applicable other themes that are of research interest for a later point time.
- [ ] Put together the insights in your box in [figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Inform the leads

### Generate sticky notes guidelines
Please, read the following guidelines for the sticky note generation exercise. In this way, we increase our understanding during the sorting.
- [ ] Put -**Q**- on the sticky note if you write down a direct quote from the interview including the regarding time stamp through the following format: -**min: 2.28**-.
- [ ] If you have a larger code and you want to leave out a part or certain words, please indicate that you have done so by replacing that piece of text with the following -**[...]**-. In that way, we at least know that there is a piece of information missing from the quote.
- [ ] Put -**I**- if you write down an insight that you derived from the interview.

### Resources/Instruction
[Nielsen Norman Group article on Affinity mapping](https://www.nngroup.com/articles/affinity-diagram/)

**Comment by elimarietta** [comment]
I took notes on this for myself and thought other researchers could benefit from having all these links in one place.

### Previous affinity mapping efforts by the Design Systems team pointed out by Yas in the 3/6 All-Hands Meeting:

- [Tutorials→Affinity mapping sessions in the Design Systems Google Drive](https://drive.google.com/drive/u/1/folders/1fdnKM_VqAupotGySqY94XOB-VA-3ktMV)
- [Interviews - Affinity Diagram in the Design Systems Team Folder in Figma](https://www.figma.com/file/rbW89yoCha3ojI7kxaqvil/Interviews---Affinity-Diagram?node-id=0%3A1&t=qy7X6mX2pCzVI4L9-0)
- [Usability test analysis FigJam in the Design Systems Team Folder in Figma](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?t=qy7X6mX2pCzVI4L9-0)

**Comment by GalaStojnic** [comment]
Thanks @elimarietta! This is great. Maybe we can go through these materials tomorrow in the meeting and decide on the plan for our team's affinity diagramming analysis.

**Comment by elimarietta** [comment]
### Eli Action Items for an affinity mapping exercise

- [ ] Listen to the interview.
- [ ] In preparation of the affinity mapping exercise, generate sticky notes with the themes, ideas, and understandings that you have derived from the [Figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Finish organizing the sticky notes with the team.
- [ ] After the sticky notes organization, funnel the insights into the following elements in order to better prepare for the insight reports: user pain points, user needs, organizational needs (if applicable), themes, key insights, and if applicable other themes that are of research interest for a later point time.
- [ ] Put together the insights in your box in [figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1&t=DIb6oI6GC5YXHNhq-1).
- [ ] Inform the leads

### Generate sticky notes guidelines
Please, read the following guidelines for the sticky note generation exercise. In this way, we increase our understanding during the sorting.
- [ ] Put -**Q**- on the sticky note if you write down a direct quote from the interview including the regarding time stamp through the following format: -**min: 2.28**-.
- [ ] If you have a larger code and you want to leave out a part or certain words, please indicate that you have done so by replacing that piece of text with the following -**[...]**-. In that way, we at least know that there is a piece of information missing from the quote.
- [ ] Put -**I**- if you write down an insight that you derived from the interview.

### Resources/Instruction
[Nielsen Norman Group article on Affinity mapping](https://www.nngroup.com/articles/affinity-diagram/)

**Comment by allthatyazz** [comment]
Other updates from Slack communications: 
- **March 22nd**, From Gala "To get everyone on the same page, so far we have 3 big categories (what participants liked, what they didn't like (pain points), what they'd recommend/ expect) and one small, more specific category (illustrations, which were "fine, but generic"). There are also small subcategories within these bigger categories. We're still yet to derive the key insights."
- **March 23rd** Different section of the report has been divided between researchers to work on. Positives by 
@EvaKw | Recommendations by @elimarietta and  @zeaslan | Pain points by @GalaStojnic & @fuzjan81

**Comment by allthatyazz** [comment]
On Monday 3/27 Research team presented their findings. Here are the links to the final products. 
- [ Insights Report ](https://docs.google.com/document/d/1_YHUjSWYT7QPEdXHA21uOfF5QFoYwZE4/edit?usp=share_link&ouid=105768861281432074552&rtpof=true&sd=true)
- [Slide Deck ](https://docs.google.com/presentation/d/1LJ30q2uLS3MX3Oy0QiVlG83mV9lj8WQU/edit?usp=share_link&ouid=105768861281432074552&rtpof=true&sd=true)
- [Live recording of the presentation ](https://drive.google.com/file/d/17vJ87D_RxWeWBjlA5gym25atCTo939vk/view?usp=share_link)
