### ISSUE TITLE
Set up zoom and calendar invite for the Content Weekly meetings 

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#495]
### Overview

We need to set up a new zoom link and a calendar invite for content team weekly meetings. 

### Action Items

- [x] open the Zoom accounts [spreadsheet ](https://docs.google.com/spreadsheets/d/15P3MYyNQ7Xn0pqdrTynDDipjrLl5LCN9xHVLhk9SWa8/edit?usp=sharing)
   - [x] Read the instructions
   - [x] Choose an available zoom link (being mindful of the other teams that might be using the link before or after your team meeting
   - [x] add a new row for the meeting onto the spreadsheet

- [x] log into 1 password
  - [x] go to zoom vault 
 time.
   - [x] Create a new recurring meeting in the zoom account you choose
- [x] Log in to designsystems@hackforla.org
   - [x] Make a calendar  event using the zoom link 
   - [x] Invite people
 
- [x] Add the link in this column Project Info column on the board.
- [ ] Update the link in Kanban board  and add the day to the wiki [Getting Started page](https://github.com/hackforla/design-systems/wiki/Getting-Started)

### Resources/Instructions

Resources are linked above.

**Comment by allthatyazz** [comment]
2/28-  I reserved Zoom3 account for Wednesdays at 3 PM PST. Someone has changed the Zoom setup spreadsheet so it is not as user-friendly as it used to be. I used the filtered for Wednesday to see available zoom spots. I left a comment on the spreadsheet so they would update the instruction. 

> The instructions need to be updated because the Schedule table format has been changed. Now, one needs to use the filter for the Day to figure out the available time. Then Add a row under their team's other meetings.

**Comment by allthatyazz** [comment]
@sandraberjan I submitted a request to the #admin channel on slack to add you to the Zoom vault. Once you gain access, we can close this issue.

**Comment by sandraberjan** [comment]
@allthatyazz Thank you so much! I signed up on 1password and tagged Karen to give me access. Just waiting on that now.
