### ISSUE TITLE
 Create a list of components for Universal Design Systems 

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#507]
### Overview

We need to audit the HfLA projects and determine a list of necessary components to start the universal DS. 

### Action Items

- [x] Create [a spreadsheet] with all possible components base on MUI (https://docs.google.com/spreadsheets/d/1oqDg8cEASJAdpQFKOBcrhDYJyONNONUQbQCS7jq74IQ/edit?usp=sharing)
- [x] Add the name of the teams with a link to their Figma project 
- [x] Review each team's DS and their usage of components 

### Resources/Instructions

- Link to [the spreadsheet](https://docs.google.com/spreadsheets/d/1oqDg8cEASJAdpQFKOBcrhDYJyONNONUQbQCS7jq74IQ/edit?usp=sharing)
-  Note that all the components are linked to guidelines explaining what that component is

**Comment by khanhcao17** [comment]
### Teams to look at

Go through each Figma file or live website and find all the components each uses and mark it down onto the [Google Sheet](https://docs.google.com/spreadsheets/d/1oqDg8cEASJAdpQFKOBcrhDYJyONNONUQbQCS7jq74IQ/edit#gid=0). Check off whatever you've looked through as you go through the different files.

- [x] [HfLA Website Team](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149) FIGMA
- [x] [HfLA Website Team](https://www.hackforla.org/) LIVE SITE
- [x] [Expunge Assist](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=0%3A1) FIGMA
- [x] [Expunge Assist](https://expungeassist.org/#/) LIVE SITE
- [x] [Internship Project](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=0%3A1) FIGMA
- [x] [TDM Calculator](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4041%3A12650) FIGMA
- [x] [Home Unite U S](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Apr2022?node-id=0%3A1) FIGMA
- [x] [FOLA Design](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4953%3A9013) FIGMA
- [x] [FOLA Design](https://foodoasis.la/) WEBSITE
- [x] [Lucky Parking](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=731%3A209) FIGMA
- [x] [Civic tech jobs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A6) FIGMA
- [x] [Access the Data](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=0%3A1) FIGMA
- [x] [100automation](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373) FIGMA
- [x] [311 Data](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=3266%3A1) FIGMA
- [x] [VRMS](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24265%3A2429) FIGMA
- [x] [Ballot Nav](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=264%3A3) FIGMA

**Comment by allthatyazz** [comment]
@TobyShanti Please provide an update:

Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
If you need help, be sure to either: 1) ask for help at your next meeting, or 2) put up a request for assistance on the #design-systems_ux_ui slack channel.

**Comment by TobyShanti** [comment]
Progress: I've started working on the issue, but need to complete the review.
Blockers: None
Availability: 3 hours
ETA: Sunday. Natalie and I are meeting on Friday to work on this issue.

**Comment by khanhcao17** [comment]
### 4/13/2023

SUGGESTED RELEASE SCHEDULE
- Component templates to create for first release:
     - Button
     - Text Field
     - Select
     - Icons
     - Button Group
     - Checkbox
     - Accordion
     - Card
     - Menu
- Component templates for V2:
     - Radio Group
     - Tabs
     - Grid
     - Autocomplete
     - Avatar
     - Chip
     - Divider
     - Material Icons
     - List
     - Tooltip
     - Backdrop
     - Drawer
- Component template release for V3:
     - Floating Action Button
     - Link
     - Badge
     - Bottom Navigation
     - Stack
     - Date & Time Pickers
     - Table
     - Alert
     - Dialog
     - App Bar
     - Pagination
     - Stepper
     - Box
     - Container
- Component template release for V4:
     - Slider
     - Switch
     - Progress
     - Skeleton
     - Paper
     - Breadcrumbs
     - Grid v2NEW
     - Snackbar
     - Click-Away Listener
     - CSS Baseline
     - Modal
     - Data Grid
- Component template release for V5:
     - Rating
     - Transfer List
     - Toggle Button
     - Speed Dial
     - Image List
     - Hidden
