### ISSUE TITLE
Glossary of Terms for Component Library

### ISSUE THREAD

**Issue by ryayyychel** [hackforla/design-systems#508]
### Overview

Provide descriptive definitions for each piece of content in the Component Library

### Action Items

- [ ]  Create a Glossary of terms for Names, Definitions, and References for the Component Library
- [ ]  Glossary of terms for Buttons
- [ ] Discuss Button Glossary with content team
- [ ] Make changes to the Glossary based on feedback from Content Team
- [ ] Share Glossary with Design Systems Team

### Resources/Instructions

All content is in Rachel's Sandbox

**Comment by allthatyazz** [comment]
- This issue was unnecessarily removed from the kanban board and replaced with a new one (#523). I made it back to the board.

**Comment by allthatyazz** [comment]
I investigated why we have a duplicate issue during all-hands on 5/8/23. Content Lead stated she was exploring GitHub and the duplicate issue has more information linked to it.    To be followed at #523
