### ISSUE TITLE
Re-naming of Figma Kit

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#509]
### Overview

We need to decide on the proper naming of our products so we have consistent naming for internal documentation and we set the right expectations for the end users. This issue also serves as a place to document the rationales behind our naming conventions.

### Background
- Related issue #510 

**History:** 
1) Late 2021: Figma Kit's product idea was based on the idea of a tutorial document called Figma Foundations. Figma Foundations started as a result of an organization-wide audit of Figma usage at different HfLA's teams. Figma Foundations was originally meant to cover only proper Figma file setup for HfLA projects. So it was thought of as a prerequisite step before adopting any universal Design Systems.
2) Feb- March 2022: With the new PM (Yas) joining the project and at the direction of the stakeholder, Figma Foundations' vision evolved from a short guide with the slide-deck format to a standalone platform product and long-term initiative that was meant to serve as a one-stop-shop of guidelines and starter templates for other teams to receive guidance on Figma file setup and Design Systems. In a way, the new product vision was our solution to mimic other open-source design systems platforms. We also wanted to eliminate the need for long-format google doc guides and scattered Figma files and bring all things design systems into one place.  
3) April-May 2022: In the early rounds of user testing, users expressed confusion about the naming of Figma Foundations. We realized the word "Foundations" simply has no significant meaning for the users and adds an unnecessary cognitive load for users to remember or repeat it. The research team suggested the name "Figma Kit" because of its simplicity and the expectations the word "Kit" would set for the users about parts(templates) that can be copied and reused. 
4) Jan-March 2023: The organizational priorities required our team to launch a dedicated product initiative to create a component library and DS template in Figma that is dev-friendly too. With the new DS product initiative, our team is no longer recommended to keep using the term "kit" for Figma Kit because the end users would think of components when hearing the word kit and they can mistake our two products. 

### Action Items

- [x] Set a date for the Namestorming session 
- [ ] Each team members create a list of possible names + a short blurb about why that is a good name 
- [x] Discussing the options at the namestorming sessions
- [x] Create a shortlist of the names
- [ ] Plan a quick research study to collect user feedback with open-ended questions about their expectations after hearing each name
- [ ] Send a survey to UX-UI CoP
- [ ] Share the results with the team
- [x] Choose the official name 
- [x] Change the name in GitHub Milestones and working files

### Resources/Instructions

[HfLA Figma Kit](https://www.figma.com/file/XIy3Dciciej4Q6A1TXGMS1/HfLA-Figma-Kit?node-id=2%3A16&t=SAwrdulQxK1A00A7-0)
[Our DS team workspace Figma file](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A54&t=r0qPxeKsx29UQhk6-0)
[Design Systems Template Figma file](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma?node-id=0%3A1&t=iCGOD877P5TUJBSz-0)

**Comment by sandraberjan** [comment]
The process as you outlined it above is not how naming generally happens. I'd like to give a short presentation at the next all hands meeting to inform the entire team of what it should look like. This in particular is problematic: " Each team members create a list of possible names + a short blurb about why that is a good name".

**Comment by allthatyazz** [comment]
### 4/24/2023 
- The content team is leading the Namestorming activity happening during the all-hands meeting https://github.com/hackforla/design-systems/issues/478#issuecomment-1520423216. 
- Content is not recommending the survey idea.

**Comment by michyeh** [comment]
**- 4/26/2023 -**

- Content team voted internally on the top named based on 5 criterion @sandraberjan
- Figma Kit is officially renamed **HfLA Design Compass**  pending approval from @allthatyazz and @bonniewolfe.

(see screenshot of naming criterion below) 
<img width="827" alt="Screenshot 2023-04-27 at 1 05 46 PM" src="https://user-images.githubusercontent.com/125330985/234978772-c97bc0d0-60b7-4c2d-a3c2-bf761607a702.png">

**Comment by allthatyazz** [comment]
-After receiving approval during PMs/ stakeholder meeting https://github.com/hackforla/design-systems/issues/89#issuecomment-1529767452, Figma Kit has been renamed to Figma Compass and all relevant milestones have been adjusted accordingly. However, it should be noted that changing the name in all previous documents may not be possible
