### ISSUE TITLE
My 1st issue! Learn about design systems and using Github

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/design-systems#515]
You'll need to complete [Hack for LA onboarding](https://www.hackforla.org/getting-started) before beginning this checklist. If you're deciding between HFLA teams, you can request in our Slack channel to observe one of our all-hands meetings first. This checklist is meant to get you up to speed by showing you around and introducing our workflow, products and project history.

# Slack
- [x] Introduce yourself in the [#design-systems Slack channel](https://hackforla.slack.com/archives/CH2U1CB9Q). You can attend one of our all-hands meetings or request a 1-on-1 meeting with your team lead, and that the PM grant you access to [our Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=sharing), Google Calendar meetings, [Figma project](https://www.figma.com/files/project/39879901/Team-project?fuid=913139172394832663), and Github repo. (Until you have access, some of the following links will not work.) @ the PM and your team lead in this message. 
  - [x] Check your calendar and accept the invites to our recurring meetings. You might occasionally be asked to attend a meeting outside of your function.
- [x] Update your Slack profile in the HFLA workspace. Under **Title**, type in your role and the name of the team (i.e. "UX Writer, Design Systems"). 
 
# Drive
- [x] In [our Google Drive folder](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp), add yourself to our roster spreadsheet.

# GitHub
Doing the following tasks on desktop is recommended.

### Profile settings 
<img width="300" alt="Screen Shot 2022-08-29 at 1 30 41 PM" src="https://user-images.githubusercontent.com/97491788/187262497-40a362d4-b91b-4eb0-8dc3-804aa8afdc1a.png">

- [x] At the top right of this very webpage, you'll see a row of dropdown menus. Click "⭐ Star" so the button turns into `⭐ Starred`. Now, people will be able to find your profile from [our repository's homepage](https://github.com/hackforla/design-systems).

<img width="150" alt="Screen Shot 2022-08-29 at 1 58 38 PM" src="https://user-images.githubusercontent.com/97491788/187267671-c7f9e82a-de2f-49f2-9b2d-2a22b5ce1d15.png">

### Issue settings
- [x] Below the Pins and Star settings, you'll see a list of more settings, starting with "**Assignee**" at the top. Add your Github username as an assignee.
  - [x] Select the **label** `role: _` (your role).
  - [x] Select the **project** `Learning about design systems`.
  - [x] Click `🚧 BACKLOG` to open a dropdown, and select `✈️ IN PROGRESS`.

# Learning about our Products and the history of the project
Our team is working on two main products related to design systems : HfLA Figma Guide and HfLA Design System template. You can think of the first one as a guide for Figma setup and the 2nd one as HfLA Core UI Library and component systems. 

- [x] Optional Step: Go to our Wiki > Background so you can learn about the history of the project. You can access the background page either from the sidebar pages on right or [here](https://github.com/hackforla/design-systems/wiki/Background). 

### HfLA Figma kit/Guide
- [x] Go to the [releases section](https://github.com/hackforla/design-systems/releases) of our project repository. 
   - [x] First, read the Release Note for "HfLA Figma Kit". You can access the PDF from the above link or [here](https://github.com/hackforla/design-systems/files/9975967/HfLA.Figma.Kit.v.1.0.Release.Note.pdf). 
   - [x] Then you can open the v1.0 in Figma to see the product we released for our external audience who are designers across HfLA. You can access the link to Figma from the release section mentioned above.
### HfLA Design System and UI template
- [x] Watch [this recording with stakeholder and PMs](https://drive.google.com/file/d/1sxx-sRPeHPPZQPlP569E8YSpfrb5ViH3/view?usp=share_link) in our Google Drive folder and under DS Recorderd session. This video will give you an idea what we are building. 

# Other readings
- [x] In [our Google Drive folder](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp), under "Tutorials", find the PDF of Alla Kholmatova's Design Systems book and read chapter 1 (pages 18-45).
- [ ] Optional Step: Learn about [user-centered design](https://www.nist.gov/itl/iad/visualization-and-usability-group/human-factors-human-centered-design) (more [terms and definitions](https://www.iso.org/obp/ui/#iso:std:iso:9241:-210:ed-2:v1:en)) and [task analysis](https://www.youtube.com/watch?v=tEx8R4ePwmk).

### If you are a UXer
- [ ] Click the green button `Submit new issue` on [this page](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME). This issue will generate under HfLA's UX/UI community of practice and is meant to track the skills you learn during your time at HfLA.
### If you are a developer
- [x] Read the [research from the previous lead developer](https://github.com/hackforla/design-systems/wiki/Appendix).
### If you are a product manager
- [ ] Schedule a meeting with Bonnie.
- [ ] Make sure to explore the resources avaiable to you at[ Product managment Community of Practice repository](https://github.com/hackforla/product-management). 
  - [ ] Make sure to subscirbe to #product_management channel on Slack.

# Yay!
- [x] Once you're completely done with all action items on this issue, add a comment below and @ the PM and your team lead.

**Comment by ericvennemeyer** [comment]
@joshfishman @allthatyazz Completed my onboarding issue! The readings on design systems were super interesting.

**Comment by allthatyazz** [comment]
@ericvennemeyer Awesome progress! Welcome to the team!
