### ISSUE TITLE
Exploring problem statements, Assumptions, and goals

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#52]
### Overview

In this document, we explore the problem statements, assumptions, and goals of this project. This will help the team to get clarity on their goal and reflect on effective solutions to the problem.

### Action 
This document explores:

-  What are the problem or issues that this project seeks to address?  Please keep these 4 steps in mind while making your notes:

1. Ideal situation ( What is #goals and scope of this project in your opinion?)
2. Reality (What's wrong now?)
3. Consequences ( How is the reality affecting people?)
4. Proposal (How can we research about the problem? Any solutions?)

- What are your assumptions and unexamined beliefs about the research result? What are you trying to find out?
- What is the research goals? Which kind of research would help us achieve this goal?

Please go ahead and mark your names when you are finished

- [x] Bobby
- [x] Nasim
- [x] Kiki

### Link
[Assumption Document](https://docs.google.com/spreadsheets/d/1G7GvLnvqc7XSIgDNoK2c0NPw0UKcmvkyyduRQY3wXrI/edit#gid=0)

[Assumption Analysis](https://docs.google.com/document/d/181o8-E8v_nlUiTsIbF2jN4Kugi9weH2xhrmzo0e2ul4/edit)

**Comment by nasimbiglari** [comment]
@daniellex0 @anekkk Ladies, I really appreciate if you can put few minutes and write your ideas for this issue. Your insight would be a tremendous help to the research team. We will be discussing the document in our meeting on thursday (8/19, 11:00am pst) so if you can fill it before the meeting it would be fantastic. Thank you again.

**Comment by Hanastevenson** [comment]
@nasimbiglari Please update the following

Progress: How much progress have you made on the issue?
Blocks: Are you facing any blockers?
Availability: How much time do you have to work on it this week?
ETA: When do you think it will be completed?

**Comment by nasimbiglari** [comment]
Progress: Currently scanning the document for keywords and reducing the volume of raw information. After identifying patterns we will draw meaning from data and present the findings.
Blocks: No blockers as of yet. Will communicate if something comes up.
Availability and ETA: The initial analysis of this document will be finished no later than wednesday 08/25.

**Comment by kelenelee** [comment]
Jan 10 #213 
### Overview
After obtaining the first research insights the problem statement needs to be revisited.

### Action Items

- [x] Revisit the current problem statement document.
- [x] Create and fill out a Problem Statement table and add to the Research Plan

### Resources/Instructions
[Problem statement](https://docs.google.com/document/d/16fLMrwmJI6y0Hdh5sij_wKvwGT7eCuBvX9kIswmL7vQ/edit#heading=h.qp2vcpubfz0j)
