### ISSUE TITLE
Prepare research presentation

### ISSUE THREAD

**Issue by BobbyBishopUX** [hackforla/design-systems#54]
### Overview
What do we want to present on Monday to the wider team (our process, way of working, educating them)?

### Action Items
Review and add anything that you think we should present to the wider team about UX Research and our team.

- [x] Bobby

[ ] Nas
[ ] Iris
[ ] KiKi

Edit for the time allotted (20 mins)
[ ] Bobby

### Resources/Instructions
[Drive file](https://docs.google.com/document/d/1I3fEj_XyGmp6M-5O_a9ufx9tkp9yKU-qSzJD_1rJxSg/edit?usp=sharing)

[ ] Create a presentation, if needed

**Comment by Hanastevenson** [comment]
@BobbyBishopUX I'm moving this to the In Progress column, since you are working on it for tonight.
