### ISSUE TITLE
UX Research Team - Consent-based Consensus Document

### ISSUE THREAD

**Issue by irisxie** [hackforla/design-systems#55]
### Overview
The goal of this document is to make sure that everyone has a chance to introduce themselves, and also have shared understanding of said roles, times, and hours, in order to level and norm what is going on within the team, and what we understand each of the roles are. Please feel free to suggest or modify to improve the document, but I suggest this as a first step so we can all be on the same page. 

### Action Items
Fill out the form here:  https://docs.google.com/document/d/1Oq88NgZBN2nuUJqRyUACsVohlRMtwqJUh007Kuk8qNI/edit?usp=sharing

Copy of the Document here for reference:

(This is a work in progress, I am currently asking for permission from other workplaces I’ve been at if I am able to adapt their template for our needs, will update as I heard back - Iris)

The goal of this document is to make sure that everyone has a chance to introduce themselves, and also have shared understanding of said roles, times, and hours, in order to level and norm what is going on within the team, and what we understand each of the roles are. Please feel free to suggest or modify to improve the document, but I suggest this as a first step so we can all be on the same page. -- Iris

--

Introduction 1 - Name, (including phonetic pronunciation) pronouns, what’s something you’re known for among your friends (hobby, skill, talent, quirk, etc)?
Introduction 2 - Why do you want to work as a user researcher for HfLA-Design Systems? What’s exciting to you about this work?
Introduction 3 - What do you bring to this group, in terms of skills, expertise, training, prior experience, prior coursework, etc? What strengths do you bring to this type of environment? 
Introduction 4 - What supports will you rely on from your teammates to be successful in this type of environment? 

Intentions for Next 6 Months: 
Description of Volunteer Position:
What general time(s) or what specific schedule would you like to keep?
How many hours would you like to work (on average) a week?
Preferred Communication Methods / When to Expect Replies
What feels like a good accountability/motivation/support structure for you?

**Comment by nasimbiglari** [comment]
All done, can't wait to read everyone's introduction.

**Comment by BobbyBishopUX** [comment]
Finished.
