### ISSUE TITLE
Design Colors section of Figma Design System

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#57]
### Dependency
Complete issues #79, #80, #81

### Overview
We need to create the Colors section of the Design Systems Figma file so that volunteers from other projects will be able to follow its example when they work on their own design systems' colors sections, and so that it can accompany the Design Systems guide.

### Action Items
- [x] Design Colors section in Design Systems Figma. Determine:
   - [x] Naming / categorization (primary/secondary, by usage CTA/warning/etc, light-100/light-200...)
   - [x] Variables / design tokens (names for each color that will match Devs' color names ($color-pink, etc.)
   - [x] Which colors to include
   - [x] How many colors to include
   - [x] Layout of section
   - [x] Annotations in section
- [x] Add colors to Figma Styles

### Resources/Instructions
[Design Systems Figma
](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=0%3A1)[Design Systems guide -  Colors section](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.ufnv4cmwfd1k)

**Comment by daniellex0** [comment]
This has been broken down into smaller issues / assignments for designers for v2 drafts:

#79 
#80 
#81

**Comment by kelenelee** [comment]
- [ ] #79 
- [ ] #80 
- [ ] #81 
- [ ] #83 
- [ ] #92 
- [ ] #96
