### ISSUE TITLE
Second draft of the Design System guide.

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#58]
### Overview
The Design Systems team have all read the 1st draft of the guide #17 The current content needs to be edited as well new links and images are to be added. These edits have also highlighted research goals and future backlog Issues.

### Action Items

- [x] Attach team members who commented on the document. Ask them to review the response and implement the action.

- [x] Assigned team members make changes

- [x] Create backlog tickets from the comments
- [x] Discuss the Research comments with Research team

### Resources/Instructions
[Google Document](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#)

**Comment by Hanastevenson** [comment]
@salmonciara @anekkk @rcurtis2 please take look at my response to your comments and make the changes. Thanks.

**Comment by rcurtis2** [comment]
Changes have been made in the guide. Added a link to the figma plugin.

**Comment by kelenelee** [comment]
- [ ] #312 
- [ ] #305 
- [ ] #60 
- [ ] #16 
- [ ] #67 
- [ ] #343
- [ ] #15
- [ ] #21
