### ISSUE TITLE
V2: Design Component Library & Icons portion of Figma Design System 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#59]
### Overview
We need to create the Component Library and Icons portions of the Design Systems Figma file so that volunteers from other projects will be able to follow its example when they work on their own design systems' component libraries/icons sections, and so that it can accompany the Design Systems guide.

### Action Items
- [ ] Design Component Library in Design Systems Figma. Determine:
   - [ ] How closely (if at all) to follow the existing Button component example. Make any changes as needed.
   - [ ] Which components to include
   - [ ] How many components to include
   - [ ] How to design new components / where to get them from (if there aren't examples of them in the HfLA website DS)
   - [ ] Layout
   - [ ] Component naming
   - [ ] Which component variants/states to include
   - [ ] Whether to auto-layout all components
   - [ ] Whether to include radius/shadow/spacing
      - [ ] How to name them
      - [ ] Add them to Figma Styles
- [ ] Design Icons section of Component Library in Design Systems Figma. Determine:
   - [ ] How many icons to include
   - [ ] Which icons to include/where to get them from
   - [ ] What size icons should be
   - [ ] How to layout icons
- [ ] Turn all components and icons into Figma components, variants, and states

### Resources/Instructions
[Design Systems Figma
](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=0%3A1)[Design Systems guide - Component Library section](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.60f8ta4wynqb)
[Design Systems guide - Icons section](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.3mnxbwkq6iod)

**Comment by allthatyazz** [comment]
- This issue has evolved into #487.
