### ISSUE TITLE
Weekly UI/UX Design Systems Figma Agenda

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#62]
## Overview
This issue tracks the agenda and Milestone for the UX/UI meetings.

## Milestone Typography
**Typography**
   - #56

##  Milestone Colors
**Colors** (P1)
   - #57 
    
## Milestone Colors
**Colors** (P2)
   - #57 

** Milestone Component Library** (P1)
   - #59 
   - #61
   
## Milestone Component Library
** Component Library** (P2)
   - #59 
   - #61
   
   ## Milestone Component Library
**Component Library** (P3)
   - #59 
   - #61

**Misc. Design System Figma Organization and Documentation**

##Agendas and Meeting Notes: 
[2021/08/25](https://github.com/hackforla/design-systems/issues/62#issuecomment-907547763)

**Comment by daniellex0** [comment]
**Assignment before Wed 8/18 Meeting** (for those who have time)
- Re-read [Typography section](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.3oc2pef8ew5t) of Design Systems guide, and any other online resources about typography
- Find more good examples of Design System Typography sections and add them to the [Typography tab](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A4) of the Design Systems Figma (on the left side, under 'Examples from other companies')
   - Examples can be found in [Design Systems for Figma](https://www.designsystemsforfigma.com/), [Design Systems Repo](https://designsystemsrepo.com/design-systems/), and any companies' design system websites (just paste a screenshot if it's not Figma file)
   - Feel free to annotate any sections you think are important to point out/potentially emulate
- Design your own draft(s) of a Typography section for the Design System based on common trends you notice or trends that you feel can be effective/good to emulate. Design your draft in the [Typography tab](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A4) of the Design Systems Figma (on the right side, under 'Our Drafts')

**Meeting Agenda - Wed 8/18**

1. Review and discussion of typography examples and trends from other companies' design systems
   - Focusing on both content (how many font sizes, which font sizes) and format (layout, categorization)
2. Review and discussion of our own Typography drafts (those who have)
3. Consolidate and design our own official Typography draft using our combined findings and preferences
4. Assign issue: (1) Add typography to Figma Styles, and finish/polish up typography section
5. Intro to next section: Colors

**Comment by daniellex0** [comment]
**Assignment before Wed 8/25 Meeting** 
- Re-read [Colors section](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.ufnv4cmwfd1k) of Design Systems guide, and any other online resources about design system colors
- Find more good examples of Design System Colors sections and add them to the [Colors tab](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A3) of the Design Systems Figma (on the left side, under 'Examples from other companies')
   - Examples can be found in [Design Systems for Figma](https://www.designsystemsforfigma.com/), [Design Systems Repo](https://designsystemsrepo.com/design-systems/), and any companies' design system websites (just paste a screenshot if it's not Figma file)
   - Feel free to annotate any sections you think are important to point out/potentially emulate
- Design your own draft(s) of a Colors section for the Design System based on common trends you notice or trends that you feel can be effective/good to emulate. Design your draft in the [Colors tab](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A3) of the Design Systems Figma (on the right side, under 'Our Drafts')

**Meeting Agenda - Wed 8/25**

#57 

1. Review and discussion of Colors section examples and trends from other companies' design systems
   - Focusing on how colors are categorized (naming) and layout
2. Review and discussion of our own Colors drafts 
3. Consolidate and design our own official Colors draft using our combined findings and preferences
4. Assign issue: (1) Add colors to Figma Styles, and finish/polish up colors section
5. Intro to next section: Component Library

**Comment by daniellex0** [comment]
Assignment before Wed 9/1 Meeting:
- Those assigned to issues to adjust the Colors section work on those and use the details in issues for guidance, or ask for any clarification/input (issues: Anh #79, Ryan #80, Bernard #81)
- Re-read the Component Library section and Icons section of the Design System guide, and any other online resources about design system component libraries if you want
- Find more good examples of Design System component library sections and add them to the Component Libraries tab of the Design Systems Figma (on the left side, under ‘Examples from other companies’)
   - Examples can be found in Design Systems for Figma, Design Systems Repo, Figma’s ‘Community’ section, and any companies’ public design system websites (just paste a screenshot if it’s not Figma file)
   - Feel free to annotate any sections you think are important to point out/potentially emulate

Meeting Agenda - Wed 9/1

- Review and discussion of new Colors section drafts
   - Vote on final options and decide if any other edits/iterations are needed- 
- Review and discussion of Component Library / Icons section examples and trends from other companies' design systems. Focusing on:
   - Component library sections categorization and layout
   - Icons section layout
   - How we will approach creating our component library and icons sections

**Comment by Hanastevenson** [comment]
@rcurtis2 has confirmed that he has taken all of this information and place it in the history of this project which will be on the Wiki.
