### ISSUE TITLE
Literature Review

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#63]
### Overview

This Document overviews a comprehensive summary of previous published books and researches done about design system.
This will include sources regarding the design system and the topics that are covered in HfLA Design System Guide for Designers.

### Action

- Contribute ≈5 resources by 08/26. We will discuss our findings in our meeting and continue expanding it over the following weeks.

### Link
[Literature Review](https://docs.google.com/document/d/1VB1oUgium_9N2hit0pskNJ9lRgxU392fJHsfbP3Fc5E/edit#)

**Comment by Hanastevenson** [comment]
From Medium article [How building a design system empowers your team to focus on people — not pixels.](https://medium.com/hubspot-product/people-over-pixels-b962c359a14d)

“We started this process knowing that we weren’t setting out to redesign just our product — we needed to entirely rethink the way we designed and built products”

This is why we are focusing on the research
“We needed to understand what inefficiencies in our organizational structure and workflows had led us to create a fragmented user experience in the first place, and replace them with practices and systems that worked.”

“This would free our designers and developers from obsessing over pixels so they could spend more time obsessing over people.”


Each component that exists in the Sketch kit also exists as a React component, making it easy to translate any mockup into a code the same way you assemble legos.
That means our designers don’t spend their days pushing pixels, drawing up spec sheets, or worrying about the responsiveness of their layouts. It means our developers don’t spend hours tweaking custom CSS (in fact, they write almost none at all).

It means our developers spend more time building. And it means our designers spend more time researching, ideating, and iterating, quickly and in high fidelity.
