### ISSUE TITLE
Format the 1st draft of the Guide

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#67]
### Overview
We need to format the guide in the Hack for LA branding so that it aligns with the other HfLA guides.

### Action Items

- [ ] Read the How to format guide and the slide deck
- [ ] Format the second drafts of #312 

### Resources/Instructions
 [How to format Guide](https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310/edit#)
[How to format the guide slide deck](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/edit#slide=id.ge51db8eb96_0_76)
[The Design Systems Guide](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#)

**Comment by kelenelee** [comment]
closed because we already [need to do this for the second draft](https://github.com/hackforla/design-systems/issues/60)
