### ISSUE TITLE
Export Design Systems Logo

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#69]
### Overview
The Design systems logo has been designed and now we need to export the logo's for the team to use. 

### Action Items

- [x] Export the individual logos
- [x] Add exports to this [Branding and Assets folder]( https://drive.google.com/drive/folders/1Fbqa5nAgt1KoOsIAYgfQXwGBRPCTnjOd?usp=sharing)

### Resources/Instructions
[Branding and Assets folder]( https://drive.google.com/drive/folders/1Fbqa5nAgt1KoOsIAYgfQXwGBRPCTnjOd?usp=sharing)

**Comment by ahoang94** [comment]
@Hanastevenson I have exported the logos and uploaded them to the Assets folder on Google Drive.

Please note that there are two erroneously uploaded files labelled "MOVE TO TRASH"; I do not have permission to delete them from the folder and am requesting that they be removed for me.

**Comment by Hanastevenson** [comment]
@ahoang94 Thanks for this. I have just downloaded the dark background logo's, the text is in white but there is no dark blue background.  Please could you add the two dark background logos to the Shared Drive.


<img width="1419" alt="Screenshot 2021-08-30 at 12 07 40" src="https://user-images.githubusercontent.com/6236085/131391798-f68a5ef4-3b3e-474a-9bf1-dac7a7744b87.png">

**Comment by ahoang94** [comment]
@Hanastevenson I have uploaded new files with the dark blue background. However, I would like to keep the previous files with the transparent background in the folder should there be a need to place the logo on a dark background that is not HfLA's dark blue (e.g., a black or image BG).
