### ISSUE TITLE
DS: All team Meeting Agenda 2021

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#7]
### Overview
This issue tracks the agenda for the design systems meetings and weekly roll call for projects.

Please check in on the [Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=0)

### Weekly Agenda

[Week of July 12 2021](https://github.com/hackforla/design-systems/issues/8)
[Week of July 19 2021](https://github.com/hackforla/design-systems/issues/14)
[Week of August 9 2021](#38 )
[Week of August 16th 2021](https://github.com/hackforla/design-systems/issues/53)
[Week of August 23rd 2021](https://github.com/hackforla/design-systems/issues/65)
[Week of  September 13th 2021](https://github.com/hackforla/design-systems/projects/1#card-68704139)
[Week of September 20th 2021](https://github.com/hackforla/design-systems/projects/1#card-69171954)
[Week of September 27th 2021](https://github.com/hackforla/design-systems/issues/118)
[Week of October 4th](https://github.com/hackforla/design-systems/issues/138)
[Week of October 18th 2021](https://github.com/hackforla/design-systems/issues/144)
[Week of October 25th 2021](https://github.com/hackforla/design-systems/issues/172)
[Week of November 1st 2021](https://github.com/hackforla/design-systems/issues/201)
[Week of November 15th 2021]()

### Reference/Link
[Weekly Agenda Stakeholder and PM](https://github.com/hackforla/design-systems/issues/72)
[Oliva's Weekly Agenda](https://github.com/hackforla/product-management/issues/210#issuecomment-799929433)

**Comment by ExperimentsInHonesty** [comment]
Where is the agenda for this weeks meeting? 
Please add this to the agenda for next meeting

> Hi Design Systems team.  I am working with the #guides team to develop a tracker for all the guides across the org and develop our ideation to publication pipeline.  During this time I am cleaning up some guide issues that are not formatted like the rest (they were early).  I cam across this one, and wanted to know how this material fits into the design system you all are building.  https://github.com/hackforla/product-management/issues/20

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty I will take a look at this. This week I will be catching up Issues and developments over the last couple of weeks.
