### ISSUE TITLE
PM and UX/UI Lead to create Issues post weekly meeting

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#76]
### Overview
We need to create a number of Issues as an outcome of the weekly UX/UI meeting so the team are held accountable for tasks.

### Action Items
- [x] Hold a meeting to discuss the following.
- [x]  Danielle to create Issues for option 1, 2, and 3 and set deadline for next Wednesday
- [x] Edit #57 and set the requirements for the MVP Figma Color section.
- [x] Danielle to create for adding Design Token information to the DS Guide
- [x] Danielle to create an Issue for adding colours to the MVP Figma Color section 

### Resources/Instructions
[Design Systems Figma
](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=0%3A1)

**Comment by daniellex0** [comment]
Updated, all items have been completed 👍
