### ISSUE TITLE
Review and finalized Figma Typography section drafts 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#82]
### Dependency
Finish Component Library drafts of Figma Design System file

### Overview
We need to review and finalize the Figma Typography section design system drafts so that they are ready before we launch the Figma design system.

### Action Items
- [x] Review Typography section of Design System Figma
   - [x] Make sure it is consistent with the rest of the design system
   - [x] Make sure it isn't missing anything
- [x] Make any necessary final edits 

### Resources/Instructions
[Figma Typography section](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A4)

**Comment by ahoang94** [comment]
The typography has been finalized and has been input as Figma styles: https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma?node-id=553%3A39041
