### ISSUE TITLE
Add Colors to Figma Styles

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#84]
### Dependency
Finalize colors once Component Library section of Design System Figma is finished

### Overview
We need to add the Figma Design System colors to the Figma Styles so that projects and designers can see an example of how this is done (as this is explained in the Design System guide)

### Action Items
- [x] Get final colors from Color section in Figma Design System (after final component library colors are added)
- [x] Add final colors to Figma Styles column
   - [x] See instructions for Figma Styles in Design System guide [here](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.ggt1mgcdzq8v) 

### Resources/Instructions
[Design System Figma file - Colors section
](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A3)[Instructions for adding Figma Styles in Design System guide](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.ggt1mgcdzq8v)

**Comment by ahoang94** [comment]
The colors have been finalized and added as styles in Figma. Here is the relevant artboard: https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma?node-id=553%3A38879

**Comment by Hanastevenson** [comment]
@ahoang94 Thank you for this, are you available on the 8th of February for a UX/UI meeting where @rcurtis2 is going to go through this. He may have some questions.

**Comment by ahoang94** [comment]
@Hanastevenson @rcurtis2 I may have a conflict on that date. If so, is it possible to have a 1-on-1 meeting another night?

**Comment by kelenelee** [comment]
- [ ] #57
- [ ] #79 
- [ ] #80 
- [ ] #81 
- [ ] #83 
- [ ] #92
- [ ] #93
- [ ] #96
