### ISSUE TITLE
Add Design Tokens to Design Systems guide

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#85]
### Overview
We need to add information about Design Tokens to the Design Systems guide (2nd draft) so that it is consistent with the Figma file (where design tokens i.e. variables are used in the colors section) and so that we provide comprehensive design system information to readers.

### Action Items
- [ ] Research information about design tokens in design systems
- [ ] Figure out where to include information about design tokens in Design Systems guide
- [ ] Draft information about design tokens in the Design Systems guide
- [ ] Get approval from Design team and PM

### Resources/Instructions
[Design Systems guide
](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit)

**Comment by Hanastevenson** [comment]
Article to read - https://medium.com/eightshapes-llc/naming-tokens-in-design-systems-9e86c7444676
