### ISSUE TITLE
Research Interview Recording

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#87]
### Overview
This document is a complete guide on the process of interview recording for this project.

- [x] Tools that we use for recording
- [x] what needs to be saved
- [x] location of the recording
- [x] Provide resources

### Links
[Interview Recording](https://docs.google.com/document/d/1TLG1mmzImDCRcyLpktrTSHUb5nJB7xP4AsMNeE0PCG4/edit)

**Comment by Hanastevenson** [comment]
@nasimbiglari @anekkk @navarroliuanthony to discuss.
