### ISSUE TITLE
Create draft Figma file for component library

### ISSUE THREAD

**Issue by daniellex0** [hackforla/design-systems#9]
### Overview
We need to create a draft component library in Figma so that users will be able to reference a sample component library. This is the MVP which we will need to test with users.

### Action Items
- [ ] Review components on designated component library page
- [ ] Organize components
- [ ] Links with the following Issues - #56 #57 (#62) 

### Resources/Instructions
Figma (add link when Figma back up)

**Comment by allthatyazz** [comment]
- This issue has evolved into #487.
