### ISSUE TITLE
Update ReadMe File

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/design-systems#91]
### Overview
We need to update a ReadMe file.

### Action Items

- [x] PM update readme file
- [ ] Developer to Include Installation instructions.

### Resources/Instructions
[Create ReadMe File](https://github.com/hackforla/design-systems/issues/3)

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.
