### ISSUE TITLE
Iterate MVP option 1 of Figma Design System Colors section

### ISSUE THREAD

**Issue by ahoang94** [hackforla/design-systems#96]
### Overview
We need to further iterate MVP option # 1 of the Design System Colors section in Figma, based on our discussions and preference votes in the Wed 9/1 meeting, in order to create 1 of 2 layouts/formats to potentially be used in A/B testing.

### Action Items
- [x] Resize the artboard and color swatches to make them smaller.
- [x] Add a "Neutral Colors" section.

### Resources/Instructions
[Figma Design System Colors section](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=311%3A3)

**Comment by ahoang94** [comment]
@Hanastevenson The design work has been completed and we reviewed the draft during last night's UX meeting. Should this issue be marked as Done?

**Comment by Hanastevenson** [comment]
@ahoang94 Thank you for the update I shall close this now.
