### ISSUE TITLE
Design Sliders, Filters, and Dropdowns for Figma Design System Components Section 

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/design-systems#97]
### Overview
We need to design sliders, filters, and dropdowns for the Design System Components in Figma. This is based on our Design Systems guide so that projects and designers can see an example of how this is done

### Action Items

- [x] Sliders
- [x] Filters
- [x] Dropdowns

### Resources/Instructions
[Figma Design System Components Section
](https://www.figma.com/file/ly2kOpJc98oPbSIc181F2l/HfLA-Design-Systems?node-id=315%3A3)

**Comment by rcurtis2** [comment]
Main tasks completed, but further iterations may be required i.e. adding a different style of slider and including a checked box version for filter types

**Comment by Hanastevenson** [comment]
Please provide an update:

1. Progress: "What is the current status of this ticket? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue or 3) put up a request for assistance on the #design-systems slack channel.

**Comment by rcurtis2** [comment]
This issue is completed
